### ISSUE TITLE
Nuggets and plates

### ISSUE THREAD

**Issue by Xorbah** [Davoleo/Metallurgy-4-Reforged#103]
Title. Are you guys planning on including these? Especially the nuggets, those of us who use things like Better With Mods need that for balance sake. I love the metals your mod includes, I just can't implement them because of that small barricade.

**Comment by HurtsAsHell** [comment]
it's not planned for the moment but i think we'll add it after beta release

**Comment by Xorbah** [comment]
Fantastic. Looking forward to it.

**Comment by Davoleo** [comment]
We're not adding plates since we're counting on integrating JAOPCA (that also adds plates, gears and things like that)

**Comment by Xorbah** [comment]
That's fine. So are nuggets making their way into the fold, then?
