### ISSUE TITLE
[Urgent] Game crash

### ISSUE THREAD

**Issue by Klazkin** [Davoleo/Metallurgy-4-Reforged#112]
Opening alloyer crashes the game
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2/18/19 3:44 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at it.hurts.metallurgy_reforged.gui.GuiContainerHelper.drawSlot(GuiContainerHelper.java:115)
	at it.hurts.metallurgy_reforged.gui.GuiAlloyer.func_73863_a(GuiAlloyer.java:76)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at it.hurts.metallurgy_reforged.gui.GuiContainerHelper.drawSlot(GuiContainerHelper.java:115)
	at it.hurts.metallurgy_reforged.gui.GuiAlloyer.func_73863_a(GuiAlloyer.java:76)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)

-- Screen render details --
Details:
	Screen name: it.hurts.metallurgy_reforged.gui.GuiAlloyer
	Mouse location: Scaled: (480, 269). Absolute: (960, 540)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Matpac'/27, l='MpServer', x=-695.50, y=4.00, z=-549.50]]
	Chunk stats: MultiplayerChunkCache: 529, 529
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-700,4,-553), Chunk: (at 4,0,7 in -44,-35; contains blocks -704,0,-560 to -689,255,-545), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
	Level time: 374 game time, 374 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 11 total; [EntitySlime['Slime'/14688, l='MpServer', x=-717.30, y=4.00, z=-474.14], EntityPlayerSP['Matpac'/27, l='MpServer', x=-695.50, y=4.00, z=-549.50], EntitySlime['Slime'/62177, l='MpServer', x=-675.06, y=4.00, z=-580.04], EntitySlime['Slime'/1794, l='MpServer', x=-621.28, y=4.00, z=-485.78], EntitySlime['Slime'/229, l='MpServer', x=-740.42, y=5.17, z=-575.28], EntitySlime['Slime'/28871, l='MpServer', x=-687.24, y=4.00, z=-483.86], EntitySlime['Slime'/122, l='MpServer', x=-673.69, y=4.50, z=-610.65], EntitySlime['Slime'/26125, l='MpServer', x=-689.44, y=4.50, z=-583.41], EntitySlime['Slime'/49790, l='MpServer', x=-739.47, y=4.75, z=-579.30], EntitySlime['Slime'/26127, l='MpServer', x=-698.34, y=4.00, z=-577.58], EntitySlime['Slime'/26559, l='MpServer', x=-675.92, y=4.00, z=-603.22]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 704989088 bytes (672 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID         | Version           | Source                           | Signature                                |
	|:--------- |:---------- |:----------------- |:-------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft  | 1.12.2            | minecraft.jar                    | None                                     |
	| UCHIJAAAA | mcp        | 9.42              | minecraft.jar                    | None                                     |
	| UCHIJAAAA | FML        | 8.0.99.99         | forge-1.12.2-14.23.5.2768.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge      | 14.23.5.2768      | forge-1.12.2-14.23.5.2768.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | jei        | 4.13.1.225        | jei_1.12.2-4.13.1.225 (2).jar    | None                                     |
	| UCHIJAAAA | mantle     | 1.12-1.3.3.39     | Mantle-1.12-1.3.3.39.jar         | None                                     |
	| UCHIJAAAA | metallurgy | 0.1.0             | Metallurgy-4-Reforged-0.1.0.jar  | None                                     |
	| UCHIJAAAA | tconstruct | 1.12.2-2.12.0.113 | TConstruct-1.12.2-2.12.0.113.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.82' Renderer: 'GeForce GTX 1060 3GB/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.82, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: testing pack3.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 2600X Six-Core Processor `

**Comment by Davoleo** [comment]
that's probably my fault

**Comment by HurtsAsHell** [comment]
Next time use pastebin or we Will close the issues
