### ISSUE TITLE
Utility Ores generation config

### ISSUE THREAD

**Issue by Davoleo** [Davoleo/Metallurgy-4-Reforged#113]
**Describe the solution you'd like**
Add ore generation configuration for utility ores

**Tell us about the reason(s) why you would implement this feature.**
Someone requested it :P

**Comment by Tschipp** [comment]
It seems to me that bitumen was forgotten when this was implemented, I can't find it anywhere in the config

**Comment by HurtsAsHell** [comment]
it isn't forgotten
we have changed the creation of bitumen and knowing that we would do it, we didn't add it

**Comment by HurtsAsHell** [comment]
anyway, thanks for reporting @Tschipp

**Comment by Tschipp** [comment]
Ah I see
