### ISSUE TITLE
metallurgy crash when bewitchment and better with mod are present

### ISSUE THREAD

**Issue by collwee** [Davoleo/Metallurgy-4-Reforged#114]
**Describe the bug**
crash on world load.

**To Reproduce**
Steps to reproduce the behavior:crash when i add metallurgy 4 reforged with better with mod and bewitchment 

**Versions:**
 - Metallurgy 4: Reforged: 0.1.1
 - Forge: 2811
 - Minecraft: 1.12.2

**Crash Report** 
https://paste.dimdev.org/uzahegorav.mccrash

**Additional context**
all mod present
applecore              AppleCore-mc1.12.2-3.1.4.jar
 jei                         jei_1.12.2-4.14.4.264.jar
ctm                       CTM-MC1.12.2-0.3.3.22.jar
baubles                 Baubles-1.12-1.5.2.jar
thaumcraft            Thaumcraft-1.12.2-6.1.BETA26.jar
betterwithmods     BetterWithMods-1.12-2.3.20-1027.jar
appleskin               AppleSkin-mc1.12-1.0.9.jar
betterwithaddons  Better+With+Addons-0.47-hotfix.jar
patchouli               Patchouli-1.0-16.jar
llibrary                   llibrary-1.7.17-1.12.2.jar
bewitchment         Bewitchment-1.12.2-0.0.19.6-indev.jar
chisel                    Chisel-MC1.12.2-0.2.1.35.jar
extraalchemy        extraalchemy-0.3.8.6.1-release.jar
 jeid                      JustEnoughIDs-1.0.2-26.jar
metallurgy           Metallurgy-4-Reforged-0.1.1.jar
vanillafix               VanillaFix-1.0.10-99.jar

**Comment by HurtsAsHell** [comment]
Is it a already created world?
does the crash happen as soon as you enter the world?
Did you have gauntlet in your hand?

**Comment by collwee** [comment]
it also happen on a new world

**Comment by HurtsAsHell** [comment]
I am testing and I have created a world, I have not received any crashes, could you answer the other questions?

Creating a new world continues the crash?

**Comment by collwee** [comment]
https://drive.google.com/file/d/1YF-yAG0oRCwvuIgSI9vjMOgu72ve7DqB/view?usp=sharing

here is my test mod pack with multimc it will crash every time you try to enter or create a world

**Comment by HurtsAsHell** [comment]
I havent crash.
Could you try to statrt the game with Twitch Launcher?

**Comment by collwee** [comment]
im unable to connect with the twitch launcher it seam blocked where i am

**Comment by HurtsAsHell** [comment]
use the normal minecraft launcher, i can't help you if you don't try

**Comment by collwee** [comment]
i managed to connect with the twitch launcher with the same mod and same config 
i got this new crash on world creation https://paste.dimdev.org/wizadujeko.mccrash
then when i tried to enter the world again it crashed again https://paste.dimdev.org/lohiburoqo.mccrash

**Comment by collwee** [comment]
i think i found the problem in the better with mod config there this config 
   
 # Rework chicken breeding. Chickens don't breed in pairs. You feed a single chicken 1 seed, and it craps         out an egg that can be thrown. The egg either makes a chicken, or drops raw egg.
    B:HCChickens=true

if i set it to B:HCChickens=false Witch is needed for my big modpack then metallurgy crash

**Comment by HurtsAsHell** [comment]
Try to contact the creator of better with mods

**Comment by collwee** [comment]
https://gitlab.com/BetterWithMods/BetterWithMods/issues/1305

**Comment by Xorbah** [comment]
Just letting you know BwM authors won't fix this. I believe they've stated they're done with 1.12 and are waiting for forge to move on.

**Comment by Davoleo** [comment]
oof, the could've at least told us :P
Anyways I guess I could look into some way to force the gauntlet to not load at all when BWM is loaded
that would be my last bet

**Comment by Davoleo** [comment]
Fixed in https://github.com/Davoleo/Metallurgy-4-Reforged/commit/c6dee3fe9b3e805d8fb130c1d3b7fb45b2435744
