### ISSUE TITLE
Crash when you create a bucket of Thermite with Tinker

### ISSUE THREAD

**Issue by HurtsAsHell** [Davoleo/Metallurgy-4-Reforged#115]
Unreported exception thrown! java.lang.ClassCastException: slimeknights.tconstruct.library.smeltery.BucketCastingRecipe cannot be cast to slimeknights.tconstruct.library.smeltery.CastingRecipe at com.mjr.tinkersextras.EventHandlerMain.onSmelteryPartCreation(EventHandlerMain.java:121) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1161_EventHandlerMain_onSmelteryPartCreation_OnCasting.invoke(.dynamic) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) at slimeknights.tconstruct.smeltery.events.TinkerCastingEvent$OnCasting.fire(TinkerCastingEvent.java:36) at slimeknights.tconstruct.smeltery.tileentity.TileCasting.findRecipe(TileCasting.java:205) at slimeknights.tconstruct.smeltery.tileentity.TileCasting.initNewCasting(TileCasting.java:214) at slimeknights.tconstruct.library.fluid.FluidHandlerCasting.fill(FluidHandlerCasting.java:39) at slimeknights.tconstruct.smeltery.tileentity.TileFaucet.doTransfer(TileFaucet.java:111) at slimeknights.tconstruct.smeltery.tileentity.TileFaucet.activate(TileFaucet.java:57) at slimeknights.tconstruct.smeltery.block.BlockFaucet.func_180639_a(BlockFaucet.java:84) at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423) at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579) at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254) at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020) at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808) at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) at net.minecraft.client.main.Main.main(SourceFile:123) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
21:50:09
monitor
Process Monitor
fatal
Process crashed with exit code -1

**Comment by HurtsAsHell** [comment]
Solved

**Comment by Davoleo** [comment]
Ref https://github.com/MJRLegends/TinkersExtras/issues/8
