### ISSUE TITLE
Suggestion : Tinkers Construct Armory integration

### ISSUE THREAD

**Issue by ToucanCalex** [Davoleo/Metallurgy-4-Reforged#117]
armor effects from metallurgy armors should also be modifiers for tinkers construct armory

**Comment by HurtsAsHell** [comment]
[Ok](https://github.com/TheIllusiveC4/ConstructsArmory/issues/147)

**Comment by HurtsAsHell** [comment]
https://github.com/Davoleo/Metallurgy-4-Reforged/commit/511cb974809f5cb32af261f11b9eee5aaeb1ca12

**Comment by HurtsAsHell** [comment]
https://github.com/Davoleo/Metallurgy-4-Reforged/commit/511cb974809f5cb32af261f11b9eee5aaeb1ca12 @ToucanCalex

**Comment by HurtsAsHell** [comment]
@Davoleo you Need to remove the only armor traits from the tools trait and viceversa

**Comment by Davoleo** [comment]
How am i supposed to do this?
Implementing a new empty trait for everything seems bs to me

**Comment by HurtsAsHell** [comment]
Open an issues on Construct Armory or creat your method. without this we can't publish the new version

**Comment by Davoleo** [comment]
Yeah, I'm asking C4
