### ISSUE TITLE
Some "minor" bugs

### ISSUE THREAD

**Issue by HurtsAsHell** [Davoleo/Metallurgy-4-Reforged#120]
Fix lang tooltip platinum helmet
Fix quicksilver tooltip lang

**Comment by Davoleo** [comment]
It's for me Mario!

**Comment by Davoleo** [comment]
u aware that "Strongly"  0 and 1 both don't, right? @HurtsAsHell

**Comment by Davoleo** [comment]
uhm, this is beautiful, isn't it? 
![G1w9VvlSxd](https://user-images.githubusercontent.com/24458276/54060937-eb7f5500-41fe-11e9-951e-120d37355b67.gif)

**Comment by Davoleo** [comment]
omg, the "Deeply" trait is so fucking broken

**Comment by HurtsAsHell** [comment]
you can fix they :D

**Comment by Davoleo** [comment]
them*

**Comment by HurtsAsHell** [comment]
-.-

**Comment by Davoleo** [comment]
You are assigned here as well y'know? 😂

**Comment by HurtsAsHell** [comment]
not anymore :p

**Comment by HurtsAsHell** [comment]
Ops
https://github.com/Davoleo/Metallurgy-4-Reforged/commit/7f7c4afb77d1c247383a8228cdb43f2a7d80266f

**Comment by Davoleo** [comment]
Are all traits fixed rn?

**Comment by HurtsAsHell** [comment]
Kalendrite and Amordrine didn't work
