### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by thiakil** [Davoleo/Metallurgy-4-Reforged#121]
It looks like there used to be an api in the v3 mod, but I can't see anything here. Is it planned?

(see https://github.com/aidancbrady/Mekanism/commit/a42eb1623109997228573f68a8e2750336e9778a)

**Comment by Davoleo** [comment]
Still haven't look into how mod APIs work, but, from what I understand they're used by other mods to create compatibility with the mod you make the API of

Although materials should be integrated into other mods through oreDict and other than that I don't know what it could be useful for...
so, I'm open for suggestions and discussions about this topic

In the meantime @HurtsAsHell and I will also chat about this

**Comment by thiakil** [comment]
Largely what it would be useful for is to get the list of added metals, which could be then added by oredict if needed. e.g. you add a metal 'foobar', this would then be automatically picked up and recipes added for oreFoobar, ingotFoobar, etc. Otherwise it'd need an updated release of Mek to support it.

Basically there are 2 ways to proceed
* With some way to get a list of metals, Mekanism (and any other mod) could add integration recipes
* You use Mekanism's api to add recipes yourself

I'm happy with either

**Comment by Davoleo** [comment]
it sounds like a good feature, we'll look into it, thanks for the suggestion! =)

**Comment by HurtsAsHell** [comment]
We have added this feature in the checklist, i close this issues.
