### ISSUE TITLE
Block Duplication using Tinkers integration

### ISSUE THREAD

**Issue by Caralamelia** [Davoleo/Metallurgy-4-Reforged#122]
**Describe the bug**
When a tinkers tool/weapon gains the "Duplication" trait it gains the ability to duplicate any drop from a block when broken using the tool this extends to the block dropping twice if it drops itself. This can create a massive duplication issue if the tool is used to break any block that has an inventory that is kept on break as one could store any item inside the block and proceed to break it repeatedly until the block drops twice creating a duplicate of its inventory. The modifier can be gain by applying a Midasium piece into the tool/weapon

**To Reproduce**
Create a Tinkers tool that gains the "Duplication" trait and then proceed to break a block that will drop anything (including itself) repeatedly, eventually the block will drop at least 2 of itself instead of the usual one with frequency.

**Expected behavior**
Increased drops similar to a fortune enchantment but not straight out duplication of any possible harvest-able block

**Screenshots**
https://imgur.com/qGQhlxL

**Versions:** _DO NOT write "the latest"_
- Metallurgy 4: Reforged: 0.1.1
- Forge: 14.23.5.2815
- Minecraft: 1.12.2

**Additional context**
-Tested on an environment containing only JEI, Tinkers construct (12.0.115.) and Metallurgy 4 (0.1.1)
-Doesnt seem to work on certain blocks such as the shulker box but its capable of doing so in other item-storing blocks such as Ender-IO machines or valuable ones such as iron/diamond block.
-Changing the behavior to only working on blocks that dont drop themselves can still cause issues with other mods such as machines that dont keep their energy when broken

**Comment by HurtsAsHell** [comment]
We knew already

**Comment by Davoleo** [comment]
That's overpowered yeah, I'll work out a solution to make it a bit more balanced, thanks for the report!

**Comment by Davoleo** [comment]
This is a partial fix, we might need to rework the whole trait in the future
