### ISSUE TITLE
Crash on world join.

### ISSUE THREAD

**Issue by DragonmasterDJ** [Davoleo/Metallurgy-4-Reforged#123]
**Describe the bug**
Last night I crashed while walking around, the problem was said to be unknown, but the next day I tried to rejoin the world for making my recipes for my modpack, but it says metallurgy 4 reforged has something to do with a crash 'preventing me from joining the world.

**To Reproduce**
join a already created world
crash, simple as that.

**Expected behavior**
to join the world with ease.

**Screenshots**
none

**Versions:** _DO NOT write "the latest"_
- Metallurgy 4: Reforged:  0.1.1
- Forge: 14.23.5.2796
- Minecraft:1.12.2
- Modpack _(if avaliable)_: none, its my own creation with no set release date yet.
- Conflicting mod _(if regarding mod integration)_: none in mind
- Other mods you think could cause issues:  
none in mind

**Crash Report** _if avaliable_ 
https://paste.dimdev.org/ixujejofun.mccrash

**Log** _if needed_
(will supply if needed)

**Additional context**
-

**Comment by Davoleo** [comment]
Ooh nice, that's another NPE caused by the gauntlet's capability
Do you happen to have BWM installed?

**Comment by DragonmasterDJ** [comment]
Infact I do. @Davoleo

**Comment by DragonmasterDJ** [comment]
* AND Better with addons
