### ISSUE TITLE
No ores in aroma mining dimension

### ISSUE THREAD

**Issue by kotelkonrad** [Davoleo/Metallurgy-4-Reforged#126]
Aroma1997s Dimensional World

**Comment by HurtsAsHell** [comment]
I imagined it. I can try to see if it is possible to create a pseudo integration otherwise it will have to be brought back to the creator of the mod (Obviously there would be only the minerals of the overworld)

**Comment by HurtsAsHell** [comment]
could you give me the dimension id of aroma? @kotelkonrad
