### ISSUE TITLE
Manyullyn pickaxe head incorrectly set as cobalt tier

### ISSUE THREAD

**Issue by GoldenFlame0** [Davoleo/Metallurgy-4-Reforged#128]
![2019-03-30_11 50 17](https://user-images.githubusercontent.com/49082712/55268874-06b32100-52e2-11e9-976a-464420e0f5e5.png)

**Expected behavior**
Manyullyn pickaxe head should probably be manyullyn tier.

**Versions:**
- Metallurgy 4: Reforged: 0.1.1
- Forge: 14.23.5.2820 (Loader: 8.0.99.99)
- Minecraft: 1.12.2
- Modpack _(if avaliable)_: N/A
- Conflicting mod _(if regarding mod integration)_: N/A
- Other mods you think could cause issues:  Maybe Thermal Foundation?

**Comment by HurtsAsHell** [comment]
![Cattura](https://user-images.githubusercontent.com/37914234/55275024-087be500-52e0-11e9-88d0-9f0fcbece037.PNG)
we have not changed any stat of the tinker base.

Next time check that it is really a bug
