### ISSUE TITLE
Metallurgy Tinker's parts have low durability compared to other Tinker's Metals

### ISSUE THREAD

**Issue by GoldenFlame0** [Davoleo/Metallurgy-4-Reforged#129]
**Describe the solution you'd like**
Most metallurgy tinker's parts feel like their durability is set incorrectly, leading to parts of equal damage/mining tier with Thermal Foundation or vanilla tinker's parts having dramatically lower values. Adamantine pickaxe heads have lower durability than iron ones, for god's sake. That can't be right.

**Describe alternatives you've considered**
There is a chance I've completely missed the point and metallurgy metals should not be used as tool heads, however this would rule out the pickaxe head tier issue. It also seems like a pretty bad trap for new players in that instance.

**Why would you like this to be implemented?**
It feels pretty bad to upgrade from a cobalt or manyullyn pickaxe head in order to mine end game metallurgy ores, only to have your durability take a ridiculous nosedive (~600 durability).

**Additional context**
Upgrading from manyullyn parts to orichalcum parts and further show a massive drop in durability.  Most telling is the jump from high end tinkers (Cobalt, Ardite, Manyullyn) to high end metallurgy (Orichalcum, Adamantine)
![2019-03-30_12 10 17](https://user-images.githubusercontent.com/49082712/55269218-2435ba00-52e5-11e9-9ee9-a03270732800.png)
![2019-03-30_12 10 06](https://user-images.githubusercontent.com/49082712/55269221-27c94100-52e5-11e9-96b0-cb03b67acb66.png)

**This is also an issue in the early game**, metals such as Shadow Iron have absolutely no reason to be used over metals like iron or even common stone.
![2019-03-30_12 10 34](https://user-images.githubusercontent.com/49082712/55269184-e3d63c00-52e4-11e9-91f8-99f4b610fac4.png)
![2019-03-30_12 10 29](https://user-images.githubusercontent.com/49082712/55269185-e3d63c00-52e4-11e9-810b-c17c4029b562.png)

Black steel and carmot have laughably low durability values for what tier they are. **It looks like most of the values are defaults, suggesting there's an incorrect config somewhere.**
![2019-03-30_12 21 25](https://user-images.githubusercontent.com/49082712/55269365-5c89c800-52e6-11e9-9422-ea4738b649ab.png)

**Comment by HurtsAsHell** [comment]
The metallurgy materials will always have lower stats than the tinker base. anyway, I upgraded them a little bit.
