### ISSUE TITLE
Remove different materials in tinkers constructs error

### ISSUE THREAD

**Issue by kotelkonrad** [Davoleo/Metallurgy-4-Reforged#130]
https://paste.dimdev.org/emagomewes.mccrash
conflics in greg's constructs

**Comment by Davoleo** [comment]
could you give us some more info about the versions of the conflicting mods and when the bug occurs?

**Comment by kotelkonrad** [comment]
uno momento

**Comment by kotelkonrad** [comment]
https://paste.dimdev.org/uqoyuqeqey.mccrash

**Comment by Davoleo** [comment]
what version are you playing on?

**Comment by kotelkonrad** [comment]
new

**Comment by kotelkonrad** [comment]
i always updating

**Comment by Davoleo** [comment]
ok, but I need the version number to know if you have the latest fixes...

by the way, I'll also need the mods you're playing with, so that I can try to reproduce the same bug in my dev environment

**Comment by kotelkonrad** [comment]
download gregtech, greg constucts metallurgy

**Comment by kotelkonrad** [comment]
or
[modlist_30-03-2019_10-24-04.zip](https://github.com/Davoleo/Metallurgy-4-Reforged/files/3025481/modlist_30-03-2019_10-24-04.zip)

**Comment by Davoleo** [comment]
ok, I'll take a look into this

**Comment by HurtsAsHell** [comment]
@kotelkonrad i need the log file (latest)

**Comment by kotelkonrad** [comment]
[latest.log](https://github.com/Davoleo/Metallurgy-4-Reforged/files/3025493/latest.log)

**Comment by HurtsAsHell** [comment]
Okay, isn't our problem. contact the creator of Gregtech

**Comment by kotelkonrad** [comment]
[2019-03-30-5.log](https://github.com/Davoleo/Metallurgy-4-Reforged/files/3025496/2019-03-30-5.log)

**Comment by kotelkonrad** [comment]
nope greg constructs

**Comment by HurtsAsHell** [comment]
ok, report to creator of greg constructs

**Comment by kotelkonrad** [comment]
https://github.com/EmosewaPixel/GregsConstruct/issues/1

**Comment by kotelkonrad** [comment]
i reported

**Comment by kotelkonrad** [comment]
7 days ago

**Comment by kotelkonrad** [comment]
similar

**Comment by HurtsAsHell** [comment]
I can't do anything our mod checks if the material already exists in the tinker, in case it doesn't create it. Furthermore we do not have manganese tinker material

**Comment by kotelkonrad** [comment]
plustic and nuclearcraft haves in config 
example:
materials {
    # Set to false to prevent Aethium from being loaded [default: true]
    B:"Enable material aethium"=true

**Comment by kotelkonrad** [comment]
tinker extras removes generally

**Comment by ItHurtsLikeHell** [comment]
I repeat, we do NOT have the manganese material

**Comment by Davoleo** [comment]
we do @ItHurtsLikeHell :P

**Comment by kotelkonrad** [comment]
liquid manganese ?

**Comment by HurtsAsHell** [comment]
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not register Material "manganese".

It isn't our problem.

**Comment by kotelkonrad** [comment]
adds in config delete metals

**Comment by kotelkonrad** [comment]
I do not know

**Comment by HurtsAsHell** [comment]
okay, go to the creator of gregtech creator and tell "adds in config delete metals"

**Comment by kotelkonrad** [comment]
ahh

**Comment by kotelkonrad** [comment]
# Sets to true for disable
    B:"Disable the tinker integration"=true
I've had enough

**Comment by Davoleo** [comment]
after all this argument I intentionally completely ignored...
as I said before I'll look into this issue, thanks for reporting it tho

**Comment by kotelkonrad** [comment]
thank you

**Comment by Davoleo** [comment]
Ok so, the issue is indeed between our mod and GregsConstruct
although we have a method that checks if a material was already added to Tinkers' registry

The only clue I have is that GregsConstruct's tinker materials are registered later than ours, and in that case we wouldn't be able to do anything about it

I'll open an issue related to this on their project so that we can discuss it

**Comment by Davoleo** [comment]
wrong issue sorry :P
