### ISSUE TITLE
Industrial Foregoing & Environmental Tech integration

### ISSUE THREAD

**Issue by kotelkonrad** [Davoleo/Metallurgy-4-Reforged#131]
metallurgy ores in void ore miner
ps. and laser drill from industrial foregoing

**Comment by HurtsAsHell** [comment]
For the time being use the craftweaker. we will add it asap.

P.S. follow the issues templates or I will close the issues without reviewing them next time

**Comment by kotelkonrad** [comment]
crafttweaker is very hard

**Comment by HurtsAsHell** [comment]
it isn't my problem

**Comment by kotelkonrad** [comment]
ok

**Comment by HurtsAsHell** [comment]
IDK if i can create the integration with the ET. The creator is like death

**Comment by HurtsAsHell** [comment]
https://github.com/ValkyrieofNight/EnvironmentalTech/issues/181

**Comment by Davoleo** [comment]
![image](https://user-images.githubusercontent.com/24458276/56619645-910f4c00-6626-11e9-9b56-fc80d247bc21.png)
And with this I can consider this issue completely implemented so I'll go ahead and close it
