### ISSUE TITLE
Suggestion: move tar config to worldgen.cfg, lower default value

### ISSUE THREAD

**Issue by Partonetrain** [Davoleo/Metallurgy-4-Reforged#133]
I'm using build #423, I realize this is unreleased version but I figured I'd point it out.

The frequency of tar pits config is currently in general.cfg
`I:"The spawnrate percentage of tar lake in the overworld"=25`
I think it would make more sense to have it in worldgen.cfg

Also, the default value (25) is way too high. They are more frequent then water pools (see screenshot)

![2019-04-03_22 31 10](https://user-images.githubusercontent.com/19861808/55528495-afef7380-5662-11e9-9226-77f7f881a98d.png)

**Comment by Davoleo** [comment]
Yeah it's a bit unbalanced imo, I told @HurtsAsHell some time ago. We'll talk again about it

About the config entry: I'll move it eventually

Thanks for the report!

**Comment by HurtsAsHell** [comment]
I'm playing metallurgy with the dame percentance and i haven't much bitumen lake. Could you tell me what percentance Is the best one?

Remember that the fluid tar governo only the Tar and bitumen ( one for the Road and One like the coal )

**Comment by Davoleo** [comment]
I refactored the cofig entry and
I tried lowering spawn chance to 20 ~
this issue will close as soon as I push the commit although this issue is open to further feedback

**Comment by LemADEC** [comment]
Water lake defaults to 4%.
As of 0.2.1 Tar lake defaults to 20%, which is way too frequent.
I feel tar should be less frequent than water lake, maybe like 0.5% or something.

**Comment by Davoleo** [comment]
mmh, 0.5 might really be too low, I'll make it 1% at first, and then I'll release a testing build so that people can tell me what they think about it

**Comment by scribbler957** [comment]
I just installed M4 and the config generated with tar at 250, which was way too high. It was a navigation hazard, it filled the basement of an Astral Temple. FYI.

**Comment by HurtsAsHell** [comment]
For me 250 for the tar it's ok but if you want you can change the config value @scribbler957 .

**Comment by scribbler957** [comment]
@HurtsAsHell I turned it down to 25 and I'll test it out tomorrow. I just wanted you to know how dense it was for me in case this was unintended.
Sometimes I like to commandeer pregen structures for my first base and every single one was sitting in a tar lake. I'll investigate more and taken a couple of pics; maybe it's a mod interaction. Or maybe I'll just add some dinosaur mods. ;)

**Comment by LemADEC** [comment]
10 is good for us

**Comment by scribbler957** [comment]
I created a fresh pack with only M4 and Journey map and took a screenshot. Github's not letting me post pics right now for some reason, but it looked like the one above.

PS I'm guessing you're reusing the lake code from vanilla, but I think rarer, larger lakes would be cool.
