### ISSUE TITLE
Wiki updates + mod progression helpers

### ISSUE THREAD

**Issue by Davoleo** [Davoleo/Metallurgy-4-Reforged#134]
We should really update the wiki - it's starting to be quite outdated

Furthermore we should maybe implement hints and some other kind of advice to help people find they're way through the mod

**Comment by Davoleo** [comment]
_ok this is so much more needed than I first thought_

**Comment by Davoleo** [comment]
- TODO: Write a Wiki page which contains info about ore generation info

**Comment by HurtsAsHell** [comment]
We need to add a screen/table of the new Metallurgy crafting ( i.g. gauntlet, crusher [...] )

**Comment by Davoleo** [comment]
[ ] TODO: Merge Pickaxe and Blocks Harvest Levels pages
[ ] Harvest Levels Reliability check
