### ISSUE TITLE
Things to add in the 0.2.0

### ISSUE THREAD

**Issue by HurtsAsHell** [Davoleo/Metallurgy-4-Reforged#135]
- [x] Add config to all effects
- [ ] Add config to all tinker traits
- [ ] Add config to all construct armor
- [x] Fix con trait ( from tinker to armor trait )
- [x] Update .lang
- [x] Add Osmium-Lutetium to World Gen
- [x] Fix krik-osmium-lutetium fluid color
- [x] Add crafting for krik,osmium,lutetium item

**Comment by Davoleo** [comment]
moving the 2nd and the 3rd task to #47
