### ISSUE TITLE
Suggestion: Add Etherium as an alloy of Sanguinite and Carmot

### ISSUE THREAD

**Issue by GoldenFlame0** [Davoleo/Metallurgy-4-Reforged#137]
I noticed a bit of a cool coincidence between the metals in metallurgy and some of the fluff in another game I play.

In the setting of Esper in the card game Magic: the Gathering, most people have augmented their bodies with the rare metal Etherium. It is super strong, malleable, easily sharpened, and has the ability to straight up replace body parts. When it first appeared, however, it was in limited supply. Etherium is an alloy of sangrite, the fossilised blood of a dead dragon, and carmot. Both of those minerals aren't found on Esper, and nor are the dragons you need to make it; Sangrite and Carmot are native to Esper's sister planes of Naya and Jund, those three planes once being part of a mega-plane called Alara.

![](http://wizards.com//mtg/images/daily/ftl/ftl22_trans.jpg)

Fluff aside, Carmot exists in metallurgy, and Sangrite sounds pretty close to Sanguinite. This is why I think the metal would be a pretty good fit for Metallurgy. It's not the strongest reason, but it makes sense.

I'd imagine Etherium to carry over the traits of Sanguinite into its tools; giving them all a life-stealing property. This ties back to how Esper is associated in the card game, connected to the same sort of magic that encourages vampiric or life stealing effects.

![](https://66.media.tumblr.com/7bc7e29b904cdc26b29d9d206fe5be2f/tumblr_nboo9mciCE1thxsmlo1_1280.jpg)

In terms of tinker's armoury, I'd imagine due to how easily shaped and easily enchanted Etherium is that its property would be the same as paper; writable. Obviously you need end game equipment to get Sanguinite, so giving players two sets of writable on their armour doesn't sound too overpowering.

![](https://static1.squarespace.com/static/5671dc294bf11835678d6eaa/t/5672ef77dc5cb4b9e2dddff4/1450372985460/?format=1500w)

For art, MTG has tons of unique art to show off its world. [Here are some examples of cards that feature Etherium in their art.](https://scryfall.com/search?q=Lore%3AEthersworn+or+Lore%3AEtherium+or+t%3ATezzeret+or+%22Silas+Renn%22&unique=art&as=grid&order=name)

If this idea is accepted and the team needs any assistance with programming or testing, I'm happy to help out. I'm also happy to suggest ideas for stats if need be.

**Comment by HurtsAsHell** [comment]
I think that the Ethereum could be a new bow / crossbow material that does low damage but is very fast:
For the armor, I think we could add a modifier ( like paper but with more level ) and add a low armor point.
For the sword I think we could add the vampirism effect plus an effect that ignores the armor enchant
