### ISSUE TITLE
Blank tooltip for Metallurgy effects in Materials and You

### ISSUE THREAD

**Issue by GoldenFlame0** [Davoleo/Metallurgy-4-Reforged#138]
**Describe the bug**
Tooltips regarding Metallurgy exclusive effects are blank.

![2019-04-14_14 35 39](https://user-images.githubusercontent.com/49082712/56088405-62c19c00-5ec3-11e9-9349-32d1ae61ff49.png)
![2019-04-14_14 35 32](https://user-images.githubusercontent.com/49082712/56088406-66552300-5ec3-11e9-9e7e-0ae296a56274.png)
![2019-04-14_14 34 39](https://user-images.githubusercontent.com/49082712/56088414-956b9480-5ec3-11e9-8550-f87f7b9ee0e2.png)
![2019-04-14_14 35 42](https://user-images.githubusercontent.com/49082712/56088416-a9af9180-5ec3-11e9-8f8d-f69f9ab3b4d8.png)

I can provide additional screenshots of the other effects if needed but the bug applies to almost all of them.

**Versions:** _DO NOT write "the latest"_
- Metallurgy 4: Reforged: 0.1.1
- Forge: 14.23.5.2820
- Minecraft: 1.12.2
- Other mods you think could cause issues:  Tinker's Construct

**Additional context**
Standard TConstruct effects (such as Duritae on Damascus Steel) work fine.
![2019-04-14_14 34 52](https://user-images.githubusercontent.com/49082712/56088412-87b60f00-5ec3-11e9-9018-dd5602a6fce6.png)
![2019-04-14_14 35 17](https://user-images.githubusercontent.com/49082712/56088407-740aa880-5ec3-11e9-9546-a248607e9d27.png)

**Comment by HurtsAsHell** [comment]
it isn't a bug

**Comment by GoldenFlame0** [comment]
> it isn't a bug

I don't understand. Virtually every other material effect, both in vanilla TConstruct and other mods have labels such as these. If it's not "the labels aren't showing" it's "the labels are missing". Should this be re-labelled as a suggestion?

**Comment by Davoleo** [comment]
I left them empty intentionally, cause the title of the trait is pretty self-explaining

**Comment by Davoleo** [comment]
actually, obscure and duplication are not very self-explaining, I'll take a look at the various traits and I'll add a tooltip desc if they need it to be understood better

**Comment by GoldenFlame0** [comment]
In addition, the empty tooltip looks kinda broken and not uniform with the rest of TConstruct's style. It also misses an opportunity to explain the trait better to players - ie, does life steal sometimes work, or always work? How big is the magnitude? Does it grant the life instantly or a drain over time? Is the amount proportional to the damage?

Also I have no idea what Volcanic does lol.

**Comment by Davoleo** [comment]
This is weird, in my dev environment all the tooltips have a description except life steal that I intentionally removed before

**Comment by Davoleo** [comment]
K, I've tried improving traits' descriptions, when you have some time please check this commit here ^
and if you have any other suggestions concerning this topic feel free to tell me about it

otherwise if everything else's fine I'd go ahead and close this
