### ISSUE TITLE
Crash while equipping conarm steel armor

### ISSUE THREAD

**Issue by Syphenion** [Davoleo/Metallurgy-4-Reforged#142]
After launching the server and using /fml confirm, I get a timed-out error after logging in and the server freezes.

Metallurgy 4: Reforged: V0.2.0
Forge: forge-1.12.2-14.23.5.2836-universal
Minecraft: 1.12.2

There is no crash log.

**Comment by Syphenion** [comment]
https://gist.github.com/Syphenion/dcbdcd50dff4ceee9f143a10c1b9a0b8

Latest.log attached.

**Comment by Syphenion** [comment]
https://gist.github.com/Syphenion/c98c50c513e93fcad70531727c595f92

Latest.log before the update, if that helps.

**Comment by HurtsAsHell** [comment]
i need the crash log too

**Comment by HurtsAsHell** [comment]
could you give your pack?

**Comment by HurtsAsHell** [comment]
`Attempting connection with missing mods [ivtoolkit, reccomplex, ruins, stg, worldedit, worleycaves] at CLIENT`

Could you try installing these mods and tests?

**Comment by Syphenion** [comment]
The mods are server sided, so they shouldn't affect it client side. And I'm using a custom pack, but I can upload it if you need.

**Comment by HurtsAsHell** [comment]
Send me it in pvt message on discord or i can't help you more than that

**Comment by Syphenion** [comment]
Issue resolved, unrelated to this mod. It had something to do with the playerdata files.

**Comment by Syphenion** [comment]
Upon further testing, steel armor made with construct's armory pre Metallurgy 2.0 crashes the game.

**Comment by Davoleo** [comment]
could you tell us how was this armor crafted?
this time do you have some kind of crash report?

**Comment by Syphenion** [comment]
Still no report, but I crafted the armor on construct armory's armor forge previously. A working set of steel armor was spawned in via JEI.

**Comment by HurtsAsHell** [comment]
i'm sorry but isn't metallurgy :(
