### ISSUE TITLE
Cannot repair tools and armor in the anvil

### ISSUE THREAD

**Issue by cobaltrogue1998** [Davoleo/Metallurgy-4-Reforged#143]
**Describe the bug**
You cannot repair metallurgy tools and armor in the anvil.

**To Reproduce**
Place a damaged tool or armor piece in the anvil with the ingot that it's made from.

**Expected behavior**
One ingot partially repairs the item

**Screenshots**
![2019-04-20 12_51_02-Minecraft 1 12 2](https://user-images.githubusercontent.com/49817594/56460097-21ba0380-636b-11e9-8717-08c42d437d40.png)

**Versions:** 
- Metallurgy 4: Reforged: 0.2.0
- Forge: 14.23.5.2836
- Minecraft: 1.12.2
- Modpack: custom

**Comment by HurtsAsHell** [comment]
I know there is this lack but on the one hand I believe it is better. for example, there is the midasium pick that has very little durability so it could be repaired with an ingot, I think it is very op.
Anyway, I'll talk to davo about it

**Comment by Davoleo** [comment]
Will be implemented as a side feature you will be able to turn on in config.

**It will not be enabled as default**
