### ISSUE TITLE
Suggestion: Integration with Project E

### ISSUE THREAD

**Issue by EMartinez92** [Davoleo/Metallurgy-4-Reforged#149]
Project E allows for a player to create more of an item by generating EMC equal to the value assigned to an item. An iron ingot has a value of 256, a diamond has a value of 8,096 or so. Also, any items made from multiple base ingredients have an EMC equal to the sum of their parts. An iron helmet, for example, is made from five iron ingots and has an EMC value of 1,280. If possible, I would suggest adding EMC values to some or all of the items in the mod.

Super basic setup for generating items:
![image](https://user-images.githubusercontent.com/11161892/56873077-c12b6600-69fd-11e9-8098-87676d6f3ab4.png)

GUI for Item Duplication:
![image](https://user-images.githubusercontent.com/11161892/56873081-c8eb0a80-69fd-11e9-883b-8da30d199984.png)

Sample HWYLA Tooltip:
![image](https://user-images.githubusercontent.com/11161892/56873117-1f584900-69fe-11e9-996b-39ef355430ff.png)

**Comment by Davoleo** [comment]
fyi you can add EMC values to items that don't have it by yourself in ProjectE
Although I'm guessing you would like to have a default value implemented by us right?

**Comment by EMartinez92** [comment]
I would! Mostly because I'm liable to set them lower than would be fair just to make it easier on myself.

**Comment by Davoleo** [comment]
This is implemented for the next version, it might still need a few tweaks but other than that it's complete
