### ISSUE TITLE
[Bug] Game Crashes when dealing with the gauntlets

### ISSUE THREAD

**Issue by Kudan7** [Davoleo/Metallurgy-4-Reforged#150]
Mod Version: 0.2.0
Is it repeatable? kinda (crashes on normal world but not on test world)
reports: https://hastebin.com/soyoyokani.rb
https://hastebin.com/yoninoyara.rb

Issue: when the gauntlets are equipping or swinging the game freezes before crashes. I tested with everything that was on my character at time of crashes and apparently (with help from someone) the crashes was dealing with the sounds conflicting with something else causing the crashes.

**Comment by HurtsAsHell** [comment]
what do you mean `crashes on normal world but not on test world`?

**Comment by HurtsAsHell** [comment]
I can't see you hastebin, they are clear

**Comment by Davoleo** [comment]
I can see your logs but there's nothing concerning metallurgy in them, so it's likely a problem from another mod / forge / minecraft  
I'll go ahead and close this ticket
