### ISSUE TITLE
Silver Nuggets do not craft back into Silver Ingots.

### ISSUE THREAD

**Issue by stylzm** [Davoleo/Metallurgy-4-Reforged#151]
You can craft a Silver Ingot into 9 Silver Nuggets just fine, but putting 9 Silver Nuggets in the crafting grid does not craft into anything, when it should craft into a Silver Ingot.

**Comment by HurtsAsHell** [comment]
![2019-05-05_19 56 16](https://user-images.githubusercontent.com/37914234/57198160-e2490500-6f6f-11e9-9658-596d9cfc7f97.png)
I haven't this problem, if you have installed the CraftTweaker, check the .zs
