### ISSUE TITLE
Gamecrash in Combination with Base Metals and Construct's Armory

### ISSUE THREAD

**Issue by McLenwe** [Davoleo/Metallurgy-4-Reforged#154]
**Describe the bug**
Bug causes the Game to crash at the mod loading sequence while Base Metals, Construct's Armory and Metallurgy are active.

**To Reproduce**

- Install Base Metals (including Install Base Metals (including MMDLib and MMD OreSpawn) Mod
- Install Tinkers Construct Mod and Construct's Armory
- Run the Game

**Expected behavior**
Loading without crashing

**Versions:**
- Metallurgy 4: Reforged: 0.2.0
- Forge: 14.23.5.2768
- Minecraft: 1.12.2
- Conflicting mod _(if regarding mod integration)_: BaseMetals-1.12-2.5.0-rc1.322 (MMDLib-1.12-1.0.0-rc1.28; OreSpawn-1.12-3.3.1.172); TConstruct-1.12.2-2.12.0.135; conarm-1.12.2-1.2.3.4

**Crash Report**  
[pastebin](https://pastebin.com/dm8PBbBa)

**Additional context**

In Part similar to Issue [#98 ](https://github.com/Davoleo/Metallurgy-4-Reforged/issues/98)

Materials that cause Errors are Adamantine, Mithril and Platinum

**Comment by HurtsAsHell** [comment]
Okay, i know what is the problem. We'll fix it in the 0.2.1, thanks for report

**Comment by Davoleo** [comment]
I can't reproduce this in my dev env,  I'll consider it fixed for 0.2.1, if anyone else is experience this and is able to to provide some more information feel free to do so below here
