### ISSUE TITLE
Vulcanite & Vyroxeres tools aren't registered

### ISSUE THREAD

**Issue by Davoleo** [Davoleo/Metallurgy-4-Reforged#155]
**Describe the bug**
Vulcanite & Vyroxeres tool sets don't get regisered for some reasons

**To Reproduce**
Load the game

**Expected behavior**
These tools to register

**Screenshots**
![image](https://user-images.githubusercontent.com/24458276/57809124-25bc2400-7765-11e9-938c-244aadb7f635.png)

**Versions:** _DO NOT write "the latest"_
- Metallurgy 4: Reforged: DEV
- Forge: 14.23.5.2814
- Minecraft: 1.12.2
- Modpack _(if avaliable)_: dev workspace

**Log** 
https://gist.github.com/420890e933a2d8a384a7799b377ee199

**Comment by HurtsAsHell** [comment]
The problem is the config file

**Comment by Davoleo** [comment]
I know, we opted for a codebase rework, it's going to be fixed as soon as #156 is merged into the master branch
