### ISSUE TITLE
An apology for my behavior.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Davoleo/Metallurgy-4-Reforged#157]
@Davoleo I want to apologize for my attitude yesterday - I was just getting extremely frustrated with testing and I lashed out on you and your team. I just want to apologize - you did not do anything wrong I just lashed out. At any rate I will stay of bug report forums when my bipolar kicks in.

**Comment by HurtsAsHell** [comment]
Remember that we are also people.
As soon as possible release the new version, for the moment remove the Con Armory or the metallurgy
