### ISSUE TITLE
Road texture could use an update

### ISSUE THREAD

**Issue by LemADEC** [Davoleo/Metallurgy-4-Reforged#159]
**Describe the bug**
The bitumen texture isn't completely seamless as we can see transition lines in it:
![image](https://user-images.githubusercontent.com/4776032/58485635-b41ca680-8164-11e9-9b38-38dc4dee218d.png)

**To Reproduce**
Place several road blocks in the same orientation next to each others.

**Expected behavior**
A seamless textures as we step away from the blocks.

**Screenshots**
Here's an example with one of the transition lines, a similar issue exist in orthogonal direction
![image](https://user-images.githubusercontent.com/4776032/58485759-ee864380-8164-11e9-8d69-dead7a4a6fcf.png)

**Versions:**
- Metallurgy 4: Reforged: 0.2.0
- Forge: 14.23.5.2838
- Minecraft: 1.12.2

**Comment by Klazkin** [comment]
@LemADEC 
![image](https://user-images.githubusercontent.com/44501483/58488777-a66e1d80-8172-11e9-81f9-8c81d851406c.png)
this will be the new texture
