### ISSUE TITLE
Invalid Tool/Armor Materials?

### ISSUE THREAD

**Issue by MisterOddfellow** [Davoleo/Metallurgy-4-Reforged#161]
I apologize if this ends up being a bit outside of the realm of Metallurgy 4 Reforged, but recently while giving the Material Changer mod a spin, I've found that it's unable to edit tools or armor from the Metallurgy 4 Reforged mod, usually bringing up errors about how vanilla Minecraft air is not a valid tool/armor material for editing purposes. This might possibly be Material Changer's fault, but that mod usually has little trouble editing modded tools and armor, so there's a distinct possibility that something is amiss with the way Metallurgy 4 handles its materials.

An example of a typical error log is linked below, illustrating what happens when attempting to use Material Changer to edit Metallurgy 4 Reforged's copper armor:
[gist](https://gist.github.com/MisterOddfellow/f7cf60c5a3dba32c4dd9e427ce044f73)

As per carbotaniuman's request, a screenshot of the error log as it appears in-game has also been provided:
![Screenshot 2019-06-03 18 08 14](https://user-images.githubusercontent.com/51343160/58837905-efb6e500-862a-11e9-9be1-ebaf9c2d7840.png)

These errors occur using the following versions of Minecraft and related mods:
- Metallurgy 4: Reforged: 0.2.0
- Forge: 14.23.5.2768
- Minecraft: 1.12.2
- Material Changer: 1.0.3

It may be worth looking into how Metallurgy 4 is handling its materials, as problems there would impact not only compatibility with Material Changer, but a number of other tweaker-type mods as well.

**Comment by HurtsAsHell** [comment]
@carbotaniuman

**Comment by carbotaniuman** [comment]
I can reproduce this bug. I just pushed a minor change (#165) to the Metal system but I'm not sure if that caused the problem. The big problem is that the mod names chestplates "_chest" and leggings "_legs".
