### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by hazerddex** [Davoleo/Metallurgy-4-Reforged#166]
**Describe the bug**
game crashes on loading world tick error with different custom mob entities each time

**To Reproduce**
create new world 

**Expected behavior**
world loads

- Metallurgy 4: Reforged: 0.2.0
- Forge: 1.12.2-14.23.5.2838
- Minecraft: 12.2
none just a bunch of mods installed.
- Other mods you think could cause issues:  so far on loading  a mob from ember and a mob from Animania

https://pastebin.com/jwS8N2Ft 1st crash 
https://pastebin.com/xvB1PzSg 2nd crash

i don't think the problem is exclusive to the two mods i posted i was able to use both with this mod just fine a few months ago i am not sure what has changed. other then the fact that i did a complete re-download/reinstall of all the mods i had.

**Comment by Davoleo** [comment]
oh, so this doesn't happen just with BWV --- COOL :D

Related topics: #141 #87

**Comment by Davoleo** [comment]
Caused by Aether 2
