### ISSUE TITLE
Tickin' Memory Connecction (MCA x Metallurgy 4 x Tinkers' set)

### ISSUE THREAD

**Issue by shiningHatsya** [Davoleo/Metallurgy-4-Reforged#168]
**Describe the bug**
Upon spawning in the Novam Terram-generated world, game freezes for a while then get kicked out. Alas, "Ticking Memory Connection" error.

**To Reproduce**
Play the game as normal, but in my case: Try it with Novam Terram + Tinkers' Construct (along with its addons), Minecraft Comes Alive, and this Metallurgy mod. [Mod List at the Crash Report]

**Expected behavior**
Play the game normally, the moment the game handed me two of Tinkers' related books.

**Screenshots**

**Versions:** _DO NOT write "the latest"_
- Metallurgy 4: Reforged: 0.20
- Forge: 1.12.2-14.23.5.2838
- Minecraft: 1.12.2
- Modpack _(if avaliable)_:
- Conflicting mod _(if regarding mod integration)_:
- Other mods you think could cause issues:
Quark r1.5-158 (1.12.2) + Charm 1.12.2-1.1.10
Tinkers' Add-on Mods (ConArm, Armory Expansion, PlusTiC)
Novam Terram 1.12.2 - 7.2 (Biomes O'Plenty rival biome mod)
Minecraft Comes Alive 6.0.0 beta (!?)

**Crash Report** _(if avaliable)_ 
https://gist.github.com/shiningHatsya/dfe391af2efa682e4319bca3c7e5ce01

**Comment by Davoleo** [comment]
lmao literally no information about anything

**Comment by shiningHatsya** [comment]
The first time I wrote this, whatever I've typed in got erased. It got me editing it thrice somehow.

**Comment by Davoleo** [comment]
oof, feelsBad

**Comment by shiningHatsya** [comment]
Tried running the game again, but taken from the official error message (before crash report)

**The game crashed whilst ticking memory connection**

The game crashed whilst ticking memory connection
Error: java.lang.ClassCastException: net.minecraftforge.items.wrapper.PlayerMainInvWrapper cannot be cast to net.minecraftforge.items.wrapper.InvWrapper

**Comment by HurtsAsHell** [comment]
I think it's Quark but i need to check

**Comment by Davoleo** [comment]
Update "Charm" to 1.1.12 
Bug reference: https://github.com/svenhjol/Charm/issues/84
