### ISSUE TITLE
[1.12.2] Gauntlet Saturation usage & Dupe bug.

### ISSUE THREAD

**Issue by Z-Tunic** [Davoleo/Metallurgy-4-Reforged#175]
Minecraft: 1.12.2
Forge: 14.23.5.2838

Mods: 4
AppleCore-mc1.12.2-3.2.0
AppleSkin-mc1.12-1.0.9
jei_1.12.2-4.15.0.279
Metallurgy-4-Reforged-0.2.1

-----

Bug 1:
Gauntlets uses 2 Saturation per hit, which can actually roll Saturation into the negatives. Here's and example using Appleskin's Debug Info.

I have "0.6 Saturation & 20 Hunger" I punch a mob with the gauntlets and now the info shows as "-1.4 Saturation & 20 Hunger". The next punch with that will still drain Hunger as normal based on the config.

Speaking of the config... I am unsure if it syncs correctly if you change the hunger usage. Like... say I set it to use 5 per hit. Would it still only use 2 Saturation?

*Edit*
I set it to 0 in the config for testing purposes and it doesn't drain either saturation or hunger... so I guess currently it's... "1 = 1 Hunger / 2 Saturation, 2 = 2 Hunger / 4 Saturation, etc."

-----

Bug 2:
You can dupe gauntlets if you leave/rejoin the world or respawn after dying with "keepInventory = true". For some reason you will be allowed to un-equip the gauntlet in your off-hand while having a gauntlet in your main-hand after doing the above. Normally you cannot remove the gauntlet in your off-hand when you equip a gauntlet in your main-hand.

**Comment by Davoleo** [comment]
Fixed by @PierKnight100 in #177
