### ISSUE TITLE
Phosphorus Lamps causing server to crash

### ISSUE THREAD

**Issue by darkphan** [Davoleo/Metallurgy-4-Reforged#176]
**Describe the bug**
After placing phosphorus lamps the server will crash with a ticking entity.

**To Reproduce**
Place lamp down and wait.

**Versions:**
- Metallurgy 4: Reforged: 0.2.1
- Forge: 14.23.5.2838
- Minecraft: 1.12.2
- Modpack _(if avaliable)_:

**Crash Report** _(if avaliable)_ https://pste.me/#/k0mem

**Comment by Davoleo** [comment]
fixed in the next "patch" version
