### ISSUE TITLE
is this one on you?

### ISSUE THREAD

**Issue by border999** [Davoleo/Metallurgy-4-Reforged#178]
**Describe the bug**
try to log into my world, crash. just from what little I can understand from the crash report. There might be some conflicts between this mod or common capabilities and how Galacticraft
alters player information.

**To Reproduce**
Steps to reproduce the behavior: Well, since I'm not really certain why it's happening. Steps to
reproduce, try loading up a world. That's all.

**Expected behavior**

- Metallurgy 4: Reforged: Metallurgy-4-Reforged-0.2.1
- Forge: 14.23.5.2838
- Minecraft: 1.12.2

**Crash Report** _(if avaliable)_ 
https://gist.github.com/border999/0ff48ff222cac6f22350c6329e6b2505

**Comment by HurtsAsHell** [comment]
I need the latest log.

**Comment by Davoleo** [comment]
oh, shit here we go again @PierKnight100 xP

**Comment by Davoleo** [comment]
Reference: #87

**Comment by Davoleo** [comment]
now fixed by @PierKnight100 in #179

**Comment by border999** [comment]
[16:32:54]  is the time you will be looking for in the log.
https://gist.github.com/border999/c08eea866f3cbb9c40b72f5483c3fda7

**Comment by border999** [comment]
@HurtsAsHell @Davoleo  do you have any ETA when this update would be public?

**Comment by HurtsAsHell** [comment]
it is out. If you join in our discord you can notified on when new releases is out :D

**Comment by Davoleo** [comment]
no, it's not out yet, it'll be out with the other bug patches as well as the server crash fix >.>
