### ISSUE TITLE
Metallurgy and Armory Expansion break Plustic Project E materials.

### ISSUE THREAD

**Issue by Keb911** [Davoleo/Metallurgy-4-Reforged#180]
**Describe the bug**
Metallurgy and Armory Expansion break Plustic Project E materials (dark/red matter tool parts disappear.) Armory Expansion and plustic work fine together but as soon as metallurgy is added, it seems to break armory expansion. (Disabling Armory Expansion fixes the problem but only after metallurgy is installed does it break in the first place.)

**To Reproduce**
Install all listed mods except for metallurgy, start game, search for dark/red matter parts, quit game. Install metallurgy, start game again and search for dark/red matter parts. 
**Screenshots**

**Versions:** _DO NOT write "the latest"_
- Metallurgy 4: Reforged: 0.2.1
- Forge: 14.23.5.2838
- Minecraft: 1.12.2
- Modpack _(if available)_:
- Conflicting mod _(if regarding mod integration)_:
armoryexpansion 1.3.1
plustic 7.0.7.0
ProjectE 1.12.2 PE1.4.1
- Other mods you think could cause issues:
Dependant mod versions for conflicting mods:
Mantle 1.12 1.3.3.55
Tinkers Construct 1.12.2 2.12.0.135
construct's armory 1.12.2 1.2.4

**Crash log**
None

**Log** _(latest.log)_ 
https://paste.ee/p/Z4X4W

**Additional context** _(if needed)_

**Comment by HurtsAsHell** [comment]
![2019-06-25_09 43 36](https://user-images.githubusercontent.com/37914234/60081734-aaba3600-9732-11e9-8bb3-9a200b89fcd5.png)
![2019-06-25_09 47 39](https://user-images.githubusercontent.com/37914234/60081735-aaba3600-9732-11e9-98ba-0c4c32dcc724.png)
What are you talking about precisely?

**Comment by Keb911** [comment]
I figured it out, armory expansion just needed it's configs deleted. This is what I get for trying to do stuff at 1am.
