### ISSUE TITLE
v3 Textures

### ISSUE THREAD

**Issue by HurtsAsHell** [Davoleo/Metallurgy-4-Reforged#181]
~Create a config and methods that implements the choosing of texture~

**Comment by stormbringerGT** [comment]
Yes! My server is split on whether they love it or hate it (I love the new texture!)

**Comment by Davoleo** [comment]
@Klazkin (our artist) is actually working on a 3rd version of the textures that is another take of the v2 texture that in some way resembles v1, so we're probably just going to implement those

**Comment by Davoleo** [comment]
This is implemented in dev as of https://github.com/Davoleo/Metallurgy-4-Reforged/commit/288b9abca9758b566233ac41ca9e2923aacf50f9
