### ISSUE TITLE
Metallurgy reforged crashes game, conflict with tinkers compendium?

### ISSUE THREAD

**Issue by Nano1778** [Davoleo/Metallurgy-4-Reforged#183]
Heres the crash report I got, https://pastebin.com/Jfc6yxB2

Crashes upon loading.

**Comment by Nano1778** [comment]
Heres the latest.log: https://pastebin.com/ZEPZUANk

Metallurgy version: Metallurgy-4-Reforged-0.2.0

Tinkers Compendium version: tinkersdefense-1.4.2.26.2

**Comment by HurtsAsHell** [comment]
This bug did not depend on metallurgy, is a `java.lang.NullPointerException` so the crash depends by Tinker compendium furthermore it's already reported

https://github.com/Lance5057/Tinkers-Compendium/issues/112
