### ISSUE TITLE
Crash at boot with Lucraft and Tinker's Construct

### ISSUE THREAD

**Issue by LemADEC** [Davoleo/Metallurgy-4-Reforged#184]
**Describe the bug**
Crash at boot when Metallurgy force registration of an already registered liquid by Lucraft.
As initially reported here: https://www.curseforge.com/minecraft/mc-mods/lucraft-core/issues/118

**To Reproduce**
Boot the game

**Versions:**
- Metallurgy 4: Reforged: 0.2.1
- Forge: 14.23.5.2838
- Minecraft: 1.12.2
- Conflicting mod:
LucraftCore-1.12.2-2.4.4
- Other mods you think could cause issues:  
Mantle-1.12-1.3.3.55
TConstruct-1.12.2-2.12.0.157

https://gist.github.com/LemADEC/aa63deee558e515d226408a05c8b4bd9

**Comment by HurtsAsHell** [comment]
i need the latest log

**Comment by LemADEC** [comment]
https://gist.github.com/LemADEC/2c2a7b3d624203143576427be3b7b09f

**Comment by HurtsAsHell** [comment]
Okay, the problem is that in the Lucraft exist the osmium fluid for the tinker and this make the crash. i will work on it asap

**Comment by HurtsAsHell** [comment]
I recive this message : `Could not register Material "osmium": It was already registered by Metallurgy 4: Reforged`, so, i think the problem could be of Lucraft
