### ISSUE TITLE
Adding old machines and chests

### ISSUE THREAD

**Issue by hasman2** [Davoleo/Metallurgy-4-Reforged#185]
Add old Great chests and machines like smelter

**Comment by Davoleo** [comment]
Chests were not from in the original metallurgy but in some companion mod that added them, and since there are a lot of storage mods we feel like chests for every material in the mod are not really needed

about the smelter, could you expand a bit on it?
for instance, what does it do? could you provide screenshots to see what it looks like?

**Comment by hasman2** [comment]
the chests were very cool because the ores were more useful and did not only apply to tools and armor. As for the smelters, they were lava-powered stoves, which were improved and the ores burned faster

**Comment by Davoleo** [comment]
Well, don't worry about the uses of metals, we'll eventually add unique gadgets and items you can craft with ingot of specific metals!
as for the smelters it's not a bad idea at all, we'll consider adding them in one of the future updates!

**Comment by Davoleo** [comment]
if you don't mind I'll keep this open to keep track of it 😅

**Comment by HurtsAsHell** [comment]
I think that we can made an addon, a cool addon for this suggestion

**Comment by stormbringerGT** [comment]
I would avoid adding yet another Smeltery to the game. Tinkers has one that is done very well and immersive and works with yours out of the box.

Of course if someone JUST uses Tinkers in a vacuum that is fine, but I assume many people play with larger modpacks when they can and we already have 3 to 4 different smelteries as a result, adding to loading time bloat and memory usage.

If you do add a smeltery, I would really appreciate the option to disable it during loading to save me some more blocks from loading in the game!

Cheers!

**Comment by Davoleo** [comment]
Hey, this kind of smeltery is not meant to melt materials into their molten form but, if I understood properly they are meant to cook ores faster into they're ingot form, at a cost of some molten fuel

**Comment by stormbringerGT** [comment]
Which a few other tech mods also add! No worries, I'm interested to see how you guys iterate on the idea, but I am also a big fan of options!

**Comment by Davoleo** [comment]
I'll close this in favour of https://github.com/Davoleo/Metallurgy-4-Reforged/projects/1#card-31300668
You can also already use lava bucket in vanilla furnaces, in the crusher as well as the alloyer
