### ISSUE TITLE
Biomes O' Plenty Conflict

### ISSUE THREAD

**Issue by Slammyyyy** [Davoleo/Metallurgy-4-Reforged#186]
**Describe the bug**
When using Biomes O' Plenty's world generation options, tar lakes do not generate at all, making it impossible to get the ore.

**To Reproduce**
1. Create a new world with Biomes O' Plenty's world gen option. Optionally, set tar lake generation as high as possible to try and make them show up.
2. Look for tar lakes.
3. Find nothing.
4. Try not to cry.
5. Cry a lot.

**Versions:**
- Metallurgy 4: Reforged:  0.22
- Forge: 14.21.1.2387
- Minecraft: 1.12.2
- Conflicting mod _(if regarding mod integration)_: Biomes O' Plenty 7.0.1

**Comment by HurtsAsHell** [comment]
I really like 4 and 5, lol. I will test
