### ISSUE TITLE
Metallurgy axes are underpowered under the current combat system

### ISSUE THREAD

**Issue by MemedHams** [Davoleo/Metallurgy-4-Reforged#187]
**Describe the bug**
In minecraft's current charge-attack based combat, axes fill the role of heavy weapons, doing significantly higher damage then swords but taking several seconds to wind up. The damage of metallurgy's axes has not yet been modified to cope with this change. For reference, the vanilla wooden and iron axes do 7(versus 4 on a sword) and 9(versus 6 on a sword) damage, respectively. Metallurgy's axes significantly reduced damage, with all axes doing 1 less damage then a sword instead of the new combat precedent of +3, which compensates for their slow recovery.
**To Reproduce**
Static code-based issue, reproducible with a basic installation of the mod. I learned the damage levels of these items using walia, but if this is unavailable one could probably check for the discrepancy in-code.

**Comment by HurtsAsHell** [comment]
This isn't a bug.

I hate the new combat system and for this reason we have't changed the attack damage.

I think that this report is a suggestion and we could make a config that makes the axes more powerful then swords
