### ISSUE TITLE
Memory leak in onSwordTick()

### ISSUE THREAD

**Issue by LemADEC** [Davoleo/Metallurgy-4-Reforged#189]
**Describe the bug**
As of 0.2.2, a memory leak is observed in onSwordTick() as it creates 4 ItemStacks per player and per tick.
Consider caching those ItemStacks to save resources.

Also, the event is called twice, once during PreTick, another during PostTick.
Consider filtering to only process the Pre or Post, not both.

**Versions:**
- Metallurgy 4: Reforged: Reforged: 0.2.2
- Forge: 14.23.5.2838
- Minecraft: 1.12.2
- Modpack _(if available)_: n/a
- Conflicting mod _(if regarding mod integration)_: n/a
- Other mods you think could cause issues: n/a

**Additional context**
Found during a code review looking for another mod's issue.

**Comment by Davoleo** [comment]
oh, thanks for pointing this out!

**Comment by Davoleo** [comment]
addressed here: https://github.com/Davoleo/Metallurgy-4-Reforged/commit/78943fdf2ab84e177ff823fde28eecf38f462326
