### ISSUE TITLE
Lag with Phosphorus lamp handler

### ISSUE THREAD

**Issue by LemADEC** [Davoleo/Metallurgy-4-Reforged#190]
**Describe the bug**
Whenever an mob is spawning, the mod check all blocks around for a phosphorus lamp. When said lamp is nest to a Vanilla spawner block, the latest keeps on trying to spawn mobs, causing lag. Here's a profiling result from a single spawner:
![image](https://user-images.githubusercontent.com/4776032/61256121-cb8f0d80-a76b-11e9-86df-792a35eec2ac.png)

Consider caching the lamp coordinates to avoid scanning the whole area each time a mob tries to spawn.

**To Reproduce**
1- Find a natural vanilla spawn room
2- Place a phosphorus lamp inside a wall
3- Profile

**Screenshots**
![image](https://user-images.githubusercontent.com/4776032/61256134-dba6ed00-a76b-11e9-9014-91efdf91cbc5.png)

**Versions:**
- Metallurgy 4: Reforged: Reforged: Reforged: 0.2.2
- Forge: 14.23.5.2838
- Minecraft: 1.12.2
- Modpack: small custom modpack
- Conflicting mod : none?
- Other mods you think could cause issues:  
this was measured on SpongeForge dedicated server (1.12.2-2838-7.1.7-RC3841).

**Additional context**
https://github.com/Davoleo/Metallurgy-4-Reforged/blob/b2ea9fbde2785196b57b80159d1e7bc909fc0e3f/src/main/java/it/hurts/metallurgy_reforged/handler/GadgetsHandler.java#L79

**Comment by LemADEC** [comment]
Issue isn't reproduced when the lamp is removed since the spawner is on cooldown at that point.

**Comment by HurtsAsHell** [comment]
IDK :/
![2019-07-16_20 06 20](https://user-images.githubusercontent.com/37914234/61318367-32143a00-a805-11e9-9282-b028fc2e06d0.png)

**Comment by Davoleo** [comment]
they're not talking about fps drops @HurtsAsHell

**Comment by HurtsAsHell** [comment]
I think I didn't understand then, then explain to me on discord

**Comment by Davoleo** [comment]
out of curiosity, what's the profiler you're using to scan for methods leaking on performance? @LemADEC

**Comment by LemADEC** [comment]
That one is from Spark, you can get the Forge version here: https://ci.lucko.me/job/spark/

Acquire 5 mn to get a decent result with `/spark start -timeout 300`. It'll give you a link at the end to the result page. Remember to select the MC version before opening the tree.
You might want to amplify the results to more easily catch the lag sources in your code (imagine what 50 players online at the same time would do).
