### ISSUE TITLE
Pre 1.9 combat - with this mod installed there is no hit cooldown.

### ISSUE THREAD

**Issue by KittyKitCatCat** [Davoleo/Metallurgy-4-Reforged#191]
Hitting an enemy resets their hurtTime to 0

Spam click an enemy to reproduce

No needed screenshots, and i don't think i can upload a video

- Metallurgy 4: Reforged:  0.2.1
- Forge:  forge-1.12.2-14.23.5.2836-universal
- Minecraft: 1.12.2
- Modpack _(if available)_: just the mod alone

I'm assuming the cause is one of your events that handles the rubecanium gauntlet attack speed isn't restricted to the gauntlet. Getting an auto clicker allows me to punch A LOT of times a second.

**Comment by HurtsAsHell** [comment]
I don't understand, what is the problem with the gauntlet?

**Comment by KittyKitCatCat** [comment]
Since i installed metallurgy, no maatter what when i punch an enemy i can immediatelly punch the enemy again.

**Comment by HurtsAsHell** [comment]
it's correct

**Comment by KittyKitCatCat** [comment]
Can that not be toggled? this leads to an insanely high damage output potential even with fists.

**Comment by HurtsAsHell** [comment]
Have you tried to check the config?

**Comment by KittyKitCatCat** [comment]
I have, just checked again now too. Nothing about disabling immunity frames for hit enemies.

**Comment by HurtsAsHell** [comment]
"immunity frames"?

```
gauntlet {
    # Sets the gauntlet attack damage
    D:"Attack Modifier"=3.0

    # We suggest to set the value to 16 or else the process bar will be rendered
    # Min: -3.0
    # Max: 16.0
    D:"Attack Speed Modifier"=16.0

    # Sets the damage dealt to the target by being hit on the block
    # Min: 0.0
    # Max: 1.7976931348623157E308
    D:"Gauntlet Block Damage"=0.5

    # Sets the gauntlet hunger modifier [ 1 = 0.5 ]
    # Min: 0
    # Max: 2147483647
    I:"Gauntlet Hunger Modifier"=1

    # Sets the Maximum Damage value for the Rubracium Gauntlet
    I:"Gauntlet Max Damage"=500

    # Set to true for disable block griefing
    B:"Gauntlet disable block griefing"=false
}
```

**Comment by KittyKitCatCat** [comment]
Again, this isn't an issue with the gauntlet. Whenever i punch an enemy i can punch the enemy the frame after. There is no cooldowns between attacks on EVERYTHING.

**Comment by HurtsAsHell** [comment]
But you have installed "Pre 1.9 combat" and this mod remove the cooldowns, what you want?
The problem isn't made by metallurgy

**Comment by KittyKitCatCat** [comment]
I did not install Pre 1.9 combat. I don't even know if that's a mod, i just made a description of whats happening - spam clicking just like before the 1.9 changes is the way to deal the highest amount of damage.

**Comment by HurtsAsHell** [comment]
Could you share the modlist?

**Comment by KittyKitCatCat** [comment]
![image](https://user-images.githubusercontent.com/49001423/61579305-d77c2600-ab03-11e9-9c05-92c7c336302f.png)
![image](https://user-images.githubusercontent.com/49001423/61579307-dfd46100-ab03-11e9-82b4-8654a428b0e1.png)
![image](https://user-images.githubusercontent.com/49001423/61579313-e82c9c00-ab03-11e9-9723-ab5b9dd1c669.png)
closest thing to a modlist i have

**Comment by KittyKitCatCat** [comment]
Then again, i've tested it wiwth just the mod alone. Same thing

**Comment by HurtsAsHell** [comment]
So the problem is that the gauntlet is a "spammer method" and that the combat system is equals to pre 1.9?

Can you spam with the sword?

**Comment by HurtsAsHell** [comment]
I have tested now and i haven't this problem.
I have the cooldown on diamond sword like the adamantine sword.
The gauntlet haven't a cooldown

**Comment by KittyKitCatCat** [comment]
in my case, nothing has a cooldown. I can setup an auto clicker and punch an enemy every frame

**Comment by HurtsAsHell** [comment]
Idk, check your mod.

Metallurgy don't make this problem

**Comment by TBiscuit1** [comment]
I will try to reproduce the bug with the same forge version and the same metallurgy version, I will post the video if I found it

**Comment by TBiscuit1** [comment]
Didn't find anything in the normal version. I try to find how you install the universal version but it's a version that I never install so it takes a lot of time to do it. I think I found how you install it and I will try to see if the bug is there

**Comment by TBiscuit1** [comment]
Finally I have the universal version (takes me 30 minute to install it X(

**Comment by TBiscuit1** [comment]
Nope, I didn't find how to reproduce the bug sadly :( You will nee to post a video with the bug, this bug is so hard to reproduce that you just have a really specific condition that made this. Even if I didn't reproduce the bug, I've found an other bug! When you have two rubracium gaunlet, if you place one at the off hand and after you chose the rubracium gauntlet in your hotbar, you will lose the second gaunlet!

**Comment by HurtsAsHell** [comment]
Okay, thanks
