### ISSUE TITLE
Add ability to edit all material stats like the old Metallurgy

### ISSUE THREAD

**Issue by Questwizard** [Davoleo/Metallurgy-4-Reforged#197]
**Describe the solution you'd like** <br>
The ability to configure all of the material stats, like the old Metallurgy 4 mod had. You could adjust everything from durability to the mining levels of various materials.

**Why would you like this to be implemented?** <br>
It would give modpack authors an easy way to balance the mod around the rest of the mods in their packs.

**Additional context** (optional) <br>
The configuration sections would be something like this excerpt from the old Metallurgy config:

    sanguinite {
        I:armour_enchantability=25
        I:armour_multiplier=36
        I:block_harvest_level=13
        I:boots_reduction=4
        I:chestplate_reduction=7
        I:helmet_reduction=5
        I:leggings_reduction=6
        I:pick_harvest_level=14
        B:sword_effects=true
        I:tool_attack_damage=4
        I:tool_durability=1750
        I:tool_efficiency=12
        I:tool_enchantability=25
    }

**Comment by Klazkin** [comment]
Note to @Davoleo, add extra variable for armor toughness and tool attack speed, health values, movement speed, knockback resistance and attack knockback strength, this is already easily possible through item attributes in [Minecraft's vanilla NBT](https://minecraft.gamepedia.com/Attribute), so I doubt it should require a lot (if any) custom code. :)
