### ISSUE TITLE
CraftTweaker support for the alloyer and crusher

### ISSUE THREAD

**Issue by SureenInk** [Davoleo/Metallurgy-4-Reforged#200]
I'd like to be able to adjust, modify, and input my own recipes into the alloyer and crusher.

For instance, if I have a mod that allows me to smelt gold and iron together to create an alloy, I could add that to the alloyer. Or, if I'm not using metallurgy metals (since it seems like every other mod adds copper, tin, etc.) I could implement a CrT recipe that lets me have access to the other ingots.

Or, perhaps, for the crusher, it could be that I want an ore not from Metallurgy to be usable in the crusher, so that the player can use the crusher for that as well.

**Comment by Davoleo** [comment]
It's already implemented in testing builds, it'll be released with the next new version

**Comment by SureenInk** [comment]
Oh, neat!

**Comment by Davoleo** [comment]
released on 0.2.3

**Comment by Breadabix** [comment]
Hi, could anyone please tell me how to add and remove recipes from the alloyer, this clearly says its possible  but anything I try doesnt work. Thanks
