### ISSUE TITLE
Molten Thermite not fueling Tinkers' Smeltery

### ISSUE THREAD

**Issue by Todeskuzz** [Davoleo/Metallurgy-4-Reforged#202]
I smelted the thermite dust in the Tinkers' smeltery and drained them into buckets, then drained the seared tanks of lava and filled them with molten thermite. However, it won't fuel the smeltery. In the smeltery controller, the gauge just says "Lava 0b".

**Comment by Davoleo** [comment]
Have you tried breaking and replacing the tinkers' smeltery controller?
that's usually the issue when using custom smeltery fuels

**Comment by Davoleo** [comment]
Being stale for more than a month I'm going to close this issue, feel free to comment again if you're still experiencing this issue
