### ISSUE TITLE
a way to automate or better way to harvest Tar/Bitumen.

### ISSUE THREAD

**Issue by chyper111** [Davoleo/Metallurgy-4-Reforged#208]
**Describe the solution you'd like** <br>

**Why would you like this to be implemented?** <br>
Tell us about the reason(s) why you would implement this feature

**Additional context** (optional) <br>

**Comment by Davoleo** [comment]
I think you should already be able to automate tar ore harvesting, using a fluid placer and a block breaker and some timing device

by the way do you have any suggestions or thoughts on this `better way to harvest` you mentioned?
cause you've been quite generic with this issue

**Comment by chyper111** [comment]
ll I've been playing with it and so far I can automate it with sticky pistons a daylight sensor and observer along with quarks iron rods as the block breaker. I'm running a vanilla improvement pack that I made myself and the idea is to only add mods that improve the game not take away such as IC2, Thermal Expansion, "All the Magic Mods because there all broken in my opinion." An so forth. I like Metallurgy Reforged Because It adds to the mining and to exploring side of Minecraft along with the building site of the game and honestly I want to see a use for all your items and tar is one that I find cool but at the same time difficult. Personally I know there are machines that can place buckets of tar and can be set up to break it and all that but I feel like it would be so much cooler if you had a machine kinda like a  furnace but instead it displayed the tar in its liquid form then lets it dry inside the container and then when coal it applied have a piston pressing it into tar/bitumen. Kinda like a tind 1 block forged but more for the processing side of metallurgy, it would be cool if you could make it's interface much like you alloyer but with  glass so you can see all the business happening   > the only thing that tar needs it away to pick up/store the tar and place it which I Know other mods can do that but players like me that don't want to take from the game and that hate to have 1 mod like IC2 for just one thing for nothing is a waste of my computers time and ram. As an added plus the tar machine can use a material that you currently don't use as a bonus to make one more gadget to your line of awesome stuff.

**Comment by chyper111** [comment]
also, id be happy to suggest a few more ideas but thats as far as I can contribute since I'm not java friendly.

**Comment by Davoleo** [comment]
oh, that's a cool suggestion
anyways yeah, feel free to put down your ideas here or on our discord server to discuss them
your idea of a drying machine seems a good addition for the mod, I'll discuss it with the other members of the team on our discord

**Comment by chyper111** [comment]
thanks for considering my idea.

**Comment by Davoleo** [comment]
I've decided I won't expand on the processing side of things in Metallurgy 4: Reforged, I will after rewriting for 1.14
so I'm gonna close this issue now - thanks for taking the time to suggest this though

**Comment by chyper111** [comment]
thats oki i found another way to make tar with extra utilities 2 so its not
much of an issue anymore. I'll still keep suggesting tho
