### ISSUE TITLE
Krik armor and aether armor menu interaction bug

### ISSUE THREAD

**Issue by gregest** [Davoleo/Metallurgy-4-Reforged#209]
**Describe the bug**
The bug happens between the Krik armor set and the Aether mod. Normally you can't unequip the krik armor while you are floating but if you do it through the Aether's armor menu then it will allow you to unequip it even when you are floating but if you do this then you can no longer equip the Krik armor by clicking on it and placing it in the armor slot, only by shift clicking the armor BUT you can still normally equip the armor through the aether menu

**To Reproduce**
Equip the krik armor, open the Aether armor menu and simply unequip the armor like you normally would

**Versions:** _DO NOT write "the latest"_
- Metallurgy 4: Reforged: Metallurgy-4-Reforged-0.2.3.jar
- Forge: I am not sure, whichever Twitch happens to come with
- Minecraft: 1.12
- Conflicting mod _(if regarding mod integration)_: Aether legacy

**Comment by Davoleo** [comment]
This is probably due to the difference between the slots that we use to lock krik armor and the slots that aether uses, which probably are just normal slots, I'll have to investigate a bit more, but I guess this can be fixed while reworking the whole effect

**Comment by Davoleo** [comment]
This will be fixed in the next realase thanks to a complete rework of the krik armor effect
