### ISSUE TITLE
Ignatus Tool Improvement

### ISSUE THREAD

**Issue by chyper111** [Davoleo/Metallurgy-4-Reforged#210]
**Describe the solution you'd like** <br>
A clear and concise description of what you want to happen. I think you should make the different tools made of this metal do different things related to fire. Have the shovel when harvesting sand has a chance to turn it directly into a glass. when enchanted with fortune it will be more likely with fortune 3 making it alway glass. Have the Axe when chopping down trees have a chance to make a log into charcoal has the same fortune applied here. The sword should be able to have a firey sweeping attack that can lightly damage but set on fire targets from a block's distance away. The Pickaxe could melt metals into a  liquid form which would double them and give more use to the heat press I mentioned earlier in my tar/bitumen post which also makes other parts of your mod obtainable without tinkers construct or other melting mods"not that they are very useful but just a cool little extra. In fact, I would use Ignatius as a fuel for the heat press to do this that way users can have temperature do just add the ores to the press and presto change-o a neat little gadget that can double the ores and make tar/bitumen. I know you have a dust system already that does this but some people like myself like being able to use 100 percent of the mod and this could open up item casting for certain gadgets in the future such as that osmium revolver that someone else mentioned.

**Why would you like this to be implemented?** <br>cuase it sounds awesome!!!
Tell us about the reason(s) why you would implement this feature

**Additional context** (optional) <br>

**Comment by chyper111** [comment]
I just realized that the tools in question have fire aspect 1 on them but id still think that this would be cooler and really you would just have to tell Minecraft what drops when you chop down a tree or mine an ore. I hope this idea helps in your dream of making this mod 100% useful.

**Comment by Davoleo** [comment]
not bad, this is definitely doable!
I'll work on this feature before working on #208 
so at first I'd make the pickaxe drop directly the ingots from the ores, later when I impement the heat press, I'll definitely integrate Ignatius or Vulcanite tools with it

**Comment by chyper111** [comment]
I'm glad you like it I would have just had auto-smelt into ingots but I feel like it would be cooler to have the liquids instead so that way your tools are more original rather then a copy of tinkers construct for the have auto-smelt already as one of its basic building materials.

**Comment by Davoleo** [comment]
I'll wait on the ignatius sword, since it already has an effect, and I think the sword effect you described fits more vulcanite than ignatius

**Comment by chyper111** [comment]
ether sounds nice to me since they both have fire damage I only didn't say vulcanite because I feel that the armor is really op like just drop protection 4 on 3 pieces and then blast on the other with the fixings like feather fall and all that and boom "like seriously it's the best armor in the mod." but its cool ether way.

**Comment by Davoleo** [comment]
alright @PierKnight100 will work on this, he will buff the ignatius fire aspect effect to have an higher chance and we'll implement the fire sweeping effect on vulcanite's sword

**Comment by chyper111** [comment]
yay cant wait to see it
