### ISSUE TITLE
Deep Iron/Armor Upgrade/Improvement

### ISSUE THREAD

**Issue by chyper111** [Davoleo/Metallurgy-4-Reforged#212]
**Describe the solution you'd like** <br>
A clear and concise description of what you want to happen. So I've been playing with this one a bit and I've noticed its a bit hard to more with at such high speeds I'd suggest adding a config to lower the speed for those of us that want to explore mods like "Better Diving " along with other underwater mods. That way if we want to swim like a dolphin we can. Personally I love everything else about the armor. 
 For the Upgrade id make tanks which have varying effects like filling a shadow iron tank with lava will cause fire damage to stop or decrease. This would give the pickaxe a good partner to bring with it and since you're great at adding effects to items like armor with things like your chamber it hopefully won't be too difficult. 
Lastly, I suggest a Siphon or Vaccum from Tar and metals like iron to suck up all the liquids. If Not that then have the tools that metal metals to auto add metals to tanks and just add a siphon as a small side to "a Just in case so to speak."

**Why would you like this to be implemented?** <br>
Tell us about the reason(s) why you would implement this feature

**Additional context** (optional) <br>
Add any other context or screenshots about the feature request here. If you go with the tanks I'd make the size of the tanks differ based on the metal you choose and some not all of the effects Like fireproof for shadow iron or just a constant light for normal iron or for deep iron you get the deep iron effects while the tank has water in it.  I love this last one about deep iron getting the effect of deep iron by simply having a tank with water in it.

**Comment by Davoleo** [comment]
We'll think about balancing the speed of the deep iron armor effect, although the rest of the suggestion is kind of over-complicated for what I want to achieve with Metallurgy 4: Reforged

**Comment by chyper111** [comment]
Eh its cool the speed is the problem for me I cant see any or that better diving ha because its like Sonic the blue burr down there. A bullet moves slower then i do, I can out run and Enderman in the rain although he would normally just leave due to water. a config would be great.

**Comment by Davoleo** [comment]
Ok we're keeping this into account, when reworking the metal effects for 1.3.0
