### ISSUE TITLE
Some features to help and steady mod progression

### ISSUE THREAD

**Issue by keeganBoiii** [Davoleo/Metallurgy-4-Reforged#214]
Thanks guys the mod is incredible. I love the multi mod interoperability.
 

To address some things:

- I suggest an in-game handbook maybe crafted by a book and any one the mod's ores, or given at spawn or something

 

- I also think a consumable detector to help find materials, made from alloys;

e.g. An Amordrine-made one-time-use detector that points in the direction of the nearest ore that is part of the sum of that alloy, so Platinum or kalendrite.
Or a Tartarite one that finds Adamantine or Atlarus, whichever's closer.
Nice because it can potentially save time, and balanced because you have to have already made the alloy before you can track the components of said alloy, and it's not always guaranteed you'll make a profit. Always the chance you'll end up finding the less valuable of the two ores. It truly gets tiring scouring the twilight forest, believe it or not XD. I also think this'll help fend off other ore detector mods.
 

- Lastly, I do feel that all the armour sets need some sort of niche use that they possess to actually give people a reason to wear them that help you traverse and survive in yourcurrent or near future environment.

e.g. Water breathing/walking for Aredrite,
or potion resistance to Infusecolium,
or wither protection for the Vyroxeres,
or fast Soul Sand traversal for the Shadow Iron,
or increased damage while on fire for Ceruclase
or as you progress in the twilight forest, your Tartarite armour gains Twlilight forest-only boons.
 
This would be really nice, because I want a reason to use all these cool armour sets for a purpose other than purposefully slowing down mod progression (which I did actually do, believe it or not. I really wanted to try all the armour and even though I knew it'd hinder me, I did it). They just don't seem to have a purpose other than looking nice on an armour stand right now.
 
Again, love the mod, this is just how I think it can be improved.

**Comment by Davoleo** [comment]
These seem some really neat additions, I'll take them into account

**Comment by Davoleo** [comment]
I'll be working on the ore detector on the same branch of the registry rework, so it might actually take some time before you can use it in a public release

**Comment by keeganBoiii** [comment]
Omg that is so awesome! Can’t wait to see what you guys do with the mod in future!!!

>

**Comment by keeganBoiii** [comment]
Wow!! This is amazing! I’m so excited to see how you implement the addition(s) to the mod. And I’m so happy that you think it’s a valid implementation to the mod. Will wait patiently while you work your magic.
