### ISSUE TITLE
Integration with NetherEx and Better Nether

### ISSUE THREAD

**Issue by happybandit360** [Davoleo/Metallurgy-4-Reforged#217]
**Describe the solution you'd like** <br>
I would like to see Metallurgy ores spawn in biomes created by NetherEx and Better Nether. They currently do not. I assume it is because they do not have normal Netherrack.

**Why would you like this to be implemented?** <br>
It would help make Metallurgy ores available throughout the Nether, instead of only in "vanilla" Nether areas.

**Additional context** (optional) <br>
Love this mods. Keep up the great work.

**Comment by Davoleo** [comment]
Better nether doesn't add nether biomes so and doesn't replace vanilla netherrack with a modded version so metallurgy should work just fine with it.
We've integrated netherrack block variants from NetherEx to work as well, will be released in the next alpha or stable version
