### ISSUE TITLE
[Suggestion] Trait idea for Quicksilver Tool Materials. For Bow-Type tools.

### ISSUE THREAD

**Issue by Z-Tunic** [Davoleo/Metallurgy-4-Reforged#218]
Some ideas to think of...

1. The trait will allow Bows/Crossbows to 'auto-fire'... basically only needing to hold down the button to load & fire.

2. The trait directly affects the Drawspeed stat, much like how the Lightweight trait affects it.

If going with option 2, you may need to tweak the Quick Action for the armor to exclude tinker's bows/crossbows... unless you want both of them to stack together leading to insane speeds.

In terms of names... 'Quick-Fire' for option 1, 'Quick-Draw' for option 2. Also... these traits shouldn't stack. *Ex. 2+ Quick-Fire & 2+ Quick-Draw.*

**Comment by Davoleo** [comment]
Note to Self: _check out how "Level Up Reloaded" does this kind of thing_
