### ISSUE TITLE
Standards for Materials from Other Dimensions

### ISSUE THREAD

**Issue by Rensik** [Davoleo/Metallurgy-4-Reforged#219]
**Describe the solution you'd like** <br>
Metals from other Dimensions should be either better than Diamond or be required to be used in alloys that make metals better than Diamond. No metal from another dimension should be worse than Diamond.

**Why would you like this to be implemented?** <br>
Diamonds are the go-to standard for materials in other dimensions. Why use material from another dimension if it is worse than the material required to enter said dimension?

**Comment by Davoleo** [comment]
You have a point there, as of right now material stats are straight based on Metallurgy 4 material stats, changing materials harvest levels would need me to go over all the other harvest levels to see if the change fits without conflicts, but if you know changes that you know would fit well feel free to share them below :P

**Comment by Davoleo** [comment]
While you work on armor and tools baalnce you could also do a pass on ore generation and harvest levels @Klazkin :)

**Comment by Klazkin** [comment]
implemented in https://github.com/Davoleo/Metallurgy-4-Reforged/commit/5e1746afa9d7293c0b2c82bbef4a02d49f24ec52#
