### ISSUE TITLE
celenegil's conarm stats a bit to good?

### ISSUE THREAD

**Issue by jarjarpfeil** [Davoleo/Metallurgy-4-Reforged#221]
I noticed that the armor stats on celenegil conarm armor is notably higher than the normal armor stats? is this intended?

I also noticed that this combined with its resistance 4 and plates with Kirk level toughness makes the player nearly invincible, maybe needs debuff?

**Comment by Davoleo** [comment]
yup, that's true, I'll balance it in the next update
