### ISSUE TITLE
Shields / gauntlet

### ISSUE THREAD

**Issue by Zack7292** [Davoleo/Metallurgy-4-Reforged#223]
**Describe the solution you'd like** <br>
i'll like to see unique shield for each and every ingots, like the lemurite shield (but with other models/looks) and the same for gauntlet

**Why would you like this to be implemented?** <br>
to add a lot of new variety of new shield that will add some way to defend yourself
and because gauntlet is a pretty awesome way to defend yourself and i'll like to see more of just the rubracium one

**Comment by Davoleo** [comment]
I'd be happy to add more of them, but I would need some special feature for each one of these gauntlets/shields, that is why I prefer more specific suggestion that focus on a few items

There's the idea of making a haderoth gauntlet, which would be an enhanced rubracium gauntlet
however gadgets are meant to be special items made of specific materials

I'm gonna close this ticket, although if you have more ideas for specific gadgets feel free to share them, they're really appreciated
