### ISSUE TITLE
Atlarus Armor Improvement/Weapon

### ISSUE THREAD

**Issue by chyper111** [Davoleo/Metallurgy-4-Reforged#224]
**Describe the solution you'd like** <br>
A clear and concise description of what you want to happen. So I was thinking about that Atlarus armor should stop fall damage by causing a whirlwind right before you hit the ground to save you at the last sec. The sword I'd have a whirlwind when used to block or "Right Click" will send all enemies to be knocked back all around you. For the tools have the axe blow away the leaves of a tree or the hoe to break lots of weeds or flowers. this way this set has a Unique set of abilities.

**Why would you like this to be implemented?** <br>
Tell us about the reason(s) why you would implement this feature

**Additional context** (optional) <br>
Add any other context or screenshots about the feature request here. I'd Also like for silk touch to apply to anything you break if you want to enchant it for that.

**Comment by Davoleo** [comment]
We'll implement:
- The armor whirlwind effect
- The sword whirlwind effect
- The axe leaves removing effect
- The hoe grass removing effect 
+ The silk touch addition
