### ISSUE TITLE
Black Steel Armor/Tool Improvement

### ISSUE THREAD

**Issue by chyper111** [Davoleo/Metallurgy-4-Reforged#225]
**Describe the solution you'd like** <br>
A clear and concise description of what you want to happen. So for this set I'd make it highly blast resistant because in real life its used to carry gases to homes. I'd make all the tool cause explosive damage at the cost of a lower durable. Although if you ask me I might just remove the armor and make a shield out of this one that stop all expulsive damage and on contact blows up the attacker without damaging you.

**Why would you like this to be implemented?** <br>
Tell us about the reason(s) why you would implement this feature

**Additional context** (optional) <br>

**Comment by Davoleo** [comment]
We'll implement:
- High Blast resistance on the armor set
- Explosive tools
- A gadget shield that creates explosions on hit
