### ISSUE TITLE
Brass Improvement 

### ISSUE THREAD

**Issue by chyper111** [Davoleo/Metallurgy-4-Reforged#226]
**Describe the solution you'd like** <br>
You could make music instruments or casings for the osmium revolver. You could make a pump or a vacuum gadget. In real life it has lots of electrical applications so you could make the tool throw or use lightning or the armor admit it light thorns does.
**Why would you like this to be implemented?** <br>
Tell us about the reason(s) why you would implement this feature

**Additional context** (optional) <br>

**Comment by Davoleo** [comment]
I'll go for the osmium revolver casing, I'll close this issue and reference it from the other one

**Comment by chyper111** [comment]
oh oki i just suggested the bullets themselves be made from brass not the
revolver.

**Comment by Davoleo** [comment]
oh that's what you meant with casings, and yeah I'm fine with it!

**Comment by chyper111** [comment]
yea it would be cool to apply you negative metal effects to the bullets and using brass as the caseins then you could pick them up and reuse them like you would in real life.
