### ISSUE TITLE
 Desichalkos Improvement

### ISSUE THREAD

**Issue by chyper111** [Davoleo/Metallurgy-4-Reforged#228]
**Describe the solution you'd like** <br>
So if I could pick an ability for this set of armor I might make a full set make you blink like the ender-men do so you can go though walls to other caves or into secret places that don't have a door O.O. The tools should have a filter to void block you don't want to pick up that can be turned off or on. Lastly ender-men should give you the blocks there holding or trade with you something rare like a gadget or end city loot if you have this armor on.
**Why would you like this to be implemented?** <br>
Tell us about the reason(s) why you would implement this feature

**Additional context** (optional) <br>

**Comment by Davoleo** [comment]
We'll implement:
- Armor that lets you blink in the direction you're looking
And we'll discuss later about the other suggestions
