### ISSUE TITLE
Electrum Improvement

### ISSUE THREAD

**Issue by chyper111** [Davoleo/Metallurgy-4-Reforged#229]
**Describe the solution you'd like** <br>
this Armor could charge Batteries and anything that can hold a charge or could discharge energy at enemies. It could pull items into a player inventory ether with the armor or a magnet gadget. Tools add items directly into the players inventory.

**Why would you like this to be implemented?** <br>
Tell us about the reason(s) why you would implement this feature

**Additional context** (optional) <br>

**Comment by Davoleo** [comment]
I like the gadget idea of an electrum magnet :)

**Comment by chyper111** [comment]
Thanks ill keep tossing ideas out as they come to me. I know there a lot of
mods that add a magnet but I feel since your mod ads lots of ore's it would
be most helpful if your mod just had one to save everyone the bother of
having another mod just for it.

**Comment by Davoleo** [comment]
We'll implement:
- an electrum magnet that pulls item entities to the player's inventory
- a sword effect that charges inventory items on hit
