### ISSUE TITLE
Add Alloyer Side Inventory Integration | Fix process restarting when the count of items in input slot increase

### ISSUE THREAD

**Issue by HurtsAsHell** [Davoleo/Metallurgy-4-Reforged#23]
Not being implemented, Crash

**Comment by HurtsAsHell** [comment]
The problem is the "getCapatibility" method, we need to return an instance of IItemHandler; See "TileEntityCrusher".

We need to fix the process when is added a resource in "input slot" @Davoleo Please, TEST

**Comment by carbotaniuman** [comment]
Can't reproduce the "Fix process restarting when the count of items in input slot increase" part. Can you give me a step by step to follow?

**Comment by Davoleo** [comment]
Place a crusher and fill it with fuel, then put a hopper on the top and let items flow inside,
Note that every time an object gets into the TE the process gets reset @carbotaniuman
