### ISSUE TITLE
Server crashes with latest version of Metallurgy

### ISSUE THREAD

**Issue by MarioSMB** [Davoleo/Metallurgy-4-Reforged#230]
Using the latest version (0.3.1) of Metallurgy on a dedicated server produces this crash:

[https://paste.ubuntu.com/p/ThF9Q3kf7s/](url)

**Comment by Davoleo** [comment]
I'm probably trying to spawn ore particles on the server, sorry for this, I'm gonna publish 0.3.2 asap to fix this crash
