### ISSUE TITLE
Etherium Armor/Tools Improvement

### ISSUE THREAD

**Issue by chyper111** [Davoleo/Metallurgy-4-Reforged#231]
**Describe the solution you'd like** <br>
So kinda like Alacard from Castlevania this armor should be able to becume Ethereal to pass through transluscent blocks. The tools could have an ability to hit or mine blocks behind other blocks or to pirce targets and hit another behind one target. A neat tool could be like a set of googles that let you see Redstone through walls or to interact with it. 

**Why would you like this to be implemented?** <br>
Tell us about the reason(s) why you would implement this feature

**Additional context** (optional) <br>

**Comment by Davoleo** [comment]
I'll see what I can do of this suggestion

**Comment by chyper111** [comment]
Well this metal is kinda new to me so its hard to think of anything too
crazy but I know that seeing through block's to help find Redstone a plus
or another idea i had was a monocle that does that or that can find
specific ores particles. that would be awesome.

**Comment by Davoleo** [comment]
We'll implement:
- an armor effect that allows you to go through blocks (with a slowness debuff)
- a monocle that allows you to see redstone related blocks through walls

**Comment by Davoleo** [comment]
This has been already completed
