### ISSUE TITLE
New Endgame Alloy

### ISSUE THREAD

**Issue by Late-Night** [Davoleo/Metallurgy-4-Reforged#232]
**Describe the solution you'd like** <br>
a new alloy made from Plutorite(there'll be a suggestion for that soon) and Desichalkos called Soulsteel
Armor Effect(for both ConArm and regular armors) would be Soulbound, Knockback Resistance, and Haste 2
Weapon effect(TiCon and otherwise) would be on hit, a chance to either heal you for 1/3 to 1/2 the damage dealt OR repair a random tool/armor piece in the inventory, prioritizing items with lower durability
items made with this material cannot be destroyed by lava or fire
**Why would you like this to be implemented?** <br>
Tell us about the reason(s) why you would implement this feature

**Additional context** (optional) <br>
i want the armor to look kinda like Thanos' from Endgame

**Comment by Davoleo** [comment]
My priority is not adding metals anymore, but making Metallurgy a stable and complete mod.
Cause just bloating it with more metals would make it only more and more unmanageable, that's why me and Matpac have decided to stop adding new metals

gonna close this issue sorry :(
