### ISSUE TITLE
Plutorite

### ISSUE THREAD

**Issue by Late-Night** [Davoleo/Metallurgy-4-Reforged#233]
**Describe the solution you'd like** <br>
a "bridging" alloy made from Tartarite and Shadow Steel, however, it has its own effects
weapon effect: deals a flat 5% damage rate, with an extra 1% added for every level of sharpness enchant, and when the target mob reaches a certain percentage of health, the mob is instantly killed, but drops no loot
armor effect: just knockback resistance, really
**Why would you like this to be implemented?** <br>
Tell us about the reason(s) why you would implement this feature
so you don't have to code an extra slot into the alloyer to make Soulsteel Possible
**Additional context** (optional) <br>

**Comment by Davoleo** [comment]
closing for the same reason as #232
