### ISSUE TITLE
Platinum Helmut Not giving night Vison anymore since 0.3.2 update

### ISSUE THREAD

**Issue by chyper111** [Davoleo/Metallurgy-4-Reforged#234]
### General Information

**Describe the bug:**
 night vison just wore off.

**To Reproduce:**

1. First Step
2. First Step
3. First Step

**Expected behavior:**

***

### Environment Versions

**Versions:**
- Metallurgy: 0.3.2
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge:14.23.5.2838
- Minecraft:1.12.2
- Modpack (if available):

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by Davoleo** [comment]
This is actually a pretty serious issue since, not only it disables the platinum night vision effect, but disables whatever effect is after celenegil's one in code
I'll release a fix for this as soon as possible, sorry for the trouble

**Comment by chyper111** [comment]
Thanks for the help I hope my suggestions and bug reports are of some help
to give you something to do with every metal.

**Comment by chyper111** [comment]
Question do you need a full set to use night vision now? I thought any one piece would give you night vision?

**Comment by Davoleo** [comment]
yup, it was a design choice:
- to balance the effect
- to put it at the same level of other armor effects 
- to avoid technical complication related to the effect system

**Comment by chyper111** [comment]
Ah good to know I suddenly wondered why mt helment stopped working i
figured but I decided to ask.
