### ISSUE TITLE
Wiki Updates and Additions

### ISSUE THREAD

**Issue by Davoleo** [Davoleo/Metallurgy-4-Reforged#239]
Effort to update [the wiki](https://github.com/Davoleo/Metallurgy-4-Reforged/wiki) with new and up to date information:
- [x] gadget page/s 
- [x] page about Tar
- [x] page about Thermite
- [x] Miscellaneous Resources
  - [x] Road Blocks
  - [x] Electrum Magnet
  - [x] Brass Knuckles
  - [x] Phosphorus Lamp
- make sure all the other pages are up to date with the mod content
  - [x] Alloying Page
  - [x] Crusher Page
  - [x] Getting Started Guide
  - [x] Harvest Levels (+ new Progression Chart)
  - [x] Material Stats (Decide if linking directly to `materials.json`)
  - [x] Sublimation Chamber Page
  - [x] Armor Effects
  - [x] Tool Effects (Maybe also merge it with the other page)
- [x] make it clearer for the end user to know what you can do with each material (Add information about mod progression in Getting-Started)
- [x] special ore generation + update ore gen information according to the new values
- [x] new shields and bucklers

Please comment below if you feel like I'm missing something in this checklist.

_Anyone can contribute by editing the wiki themselves, you just need Github Account and [Basic Markdown](https://guides.github.com/features/mastering-markdown/) knoweledge_
Join the [discord server](http://discord.davoleo.net) for help and support or if you have question about contributing or missing information

**Comment by Tigerdemigoddess** [comment]
Would have helped without me needing to add "Just enough items" an extending the ram usage to 3gigs.
