### ISSUE TITLE
Invalid Tooltip.

### ISSUE THREAD

**Issue by molaggZ** [Davoleo/Metallurgy-4-Reforged#244]
Invalid tooltip on all of the parts of eximite armor. Other armors are fine.
![image](https://user-images.githubusercontent.com/63704886/80917958-7371d800-8d8c-11ea-95db-3c3c1201a69e.png)
![image](https://user-images.githubusercontent.com/63704886/80917973-91d7d380-8d8c-11ea-96f6-359e7dfe8450.png)
![image](https://user-images.githubusercontent.com/63704886/80917977-9d2aff00-8d8c-11ea-8f9b-5198826c554a.png)
![image](https://user-images.githubusercontent.com/63704886/80917984-a6b46700-8d8c-11ea-8209-e71e4ff9446d.png)

**Comment by molaggZ** [comment]
oh, i found another one
![image](https://user-images.githubusercontent.com/63704886/80920965-6b6e6400-8d9d-11ea-9bf2-9197d4d208c2.png)

**Comment by Davoleo** [comment]
Fixed in the main branch
