### ISSUE TITLE
Metallurgy registering molten metals later than Crafttweaker

### ISSUE THREAD

**Issue by SureenInk** [Davoleo/Metallurgy-4-Reforged#246]
### General Information

**Describe the bug:**
When I am registering fluids using crafttweaker (in this case, I'm registering things in the Embers Melter), it tells me that the script is running before the fluid exist. Here's the exact error: Liquid <liquid:molten_silver> has not been found, trying to use a ghost representative. This message will only be printed once, all subsequent missing fluids will be handled the same way.

**Expected behavior:**
To be able to register the fluids properly.

***

### Environment Versions

**Versions:**
- Metallurgy: Metallurgy-4-Reforged-0.3.3.jar
- Conflicting mod (if regarding mod integration): EmbersRekindled-1.13-hotfix2.jar
- Other mods you think could cause issues: CraftTweaker2-1.12-4.1.20.562.jar
- Forge: 14.23.5.2847
- Minecraft: 1.12.2

**Comment by Davoleo** [comment]
this was fixed together with the codebase rework (#242)
should be working fine in 1.0.0 
please tell me if you encounter any other issues
