### ISSUE TITLE
Minor bugs report

### ISSUE THREAD

**Issue by Klazkin** [Davoleo/Metallurgy-4-Reforged#25]
- Crusher doesn't accept vanilla ores (iron/gold)
- Crusher (and Alloyer) don't remember their states (on/off) when reentering game. 

- Machines don't give off light when on.
- And this:
![feaf15319fdb820c07b62ba88fb138c4](https://user-images.githubusercontent.com/44501483/48569943-baa3a900-e90b-11e8-9ed1-fce03b54a9a4.png)
![0ad9ffe248050cec5c395fc58db99f02](https://user-images.githubusercontent.com/44501483/48570177-71078e00-e90c-11e8-8812-e70e58305d08.png)
Seems like for some reason the texture of the fire above the furnace extends too far up, happens after feeding the machine and then disconnecting from the game instantly, when reconnecting it will show like this. (happens almost always with alloyer, rarer with crushers)

**Comment by HurtsAsHell** [comment]
Process end animation (liquid). Implementation required

**Comment by carbotaniuman** [comment]
@Klazkin What do you mean states aren't remembered? Reload on SSP works fine.

**Comment by Klazkin** [comment]
@carbotaniuman the texture resets back to off state after rejoining

**Comment by Davoleo** [comment]
About "Crusher (and Alloyer) don't remember their states (on/off) when reentering game."

It happens especially when the fuel is burning and the machine is idle

doesn't effect machine lighting

![2018-11-19_00 11 56](https://user-images.githubusercontent.com/24458276/48679403-1a11eb00-eb90-11e8-985d-7aa7580e7322.png)

**Comment by Davoleo** [comment]
Also linked with burning texture extension bug

when the first one happens the second one does too
