### ISSUE TITLE
Server crash when disable and change ore spawn

### ISSUE THREAD

**Issue by QKou** [Davoleo/Metallurgy-4-Reforged#250]
### General Information

**Describe the bug:**

Server can't start when i change the ore spawn

**To Reproduce:**

1. Change the ore gen to stop spawning
2. Server doesn't start anymore and always crash

**Expected behavior:**

looks like it doesn't work with biomes o plenty

***

### Environment Versions

**Versions:**
- Metallurgy: Metallurgy-4-Reforged-0.3.3
- Conflicting mod (if regarding mod integration): biomes o plenty
- Other mods you think could cause issues:
- Forge: forge-1.12.2-14.23.5.2847-installer-win
- Minecraft: 1.12.2
- Modpack (if available):

**Crash Report (if available):**

---- Minecraft Crash Report ----

[crash-2020-05-21_02.09.17-server.txt](https://github.com/Davoleo/Metallurgy-4-Reforged/files/4681533/crash-2020-05-21_02.09.17-server.txt)

**Comment by Davoleo** [comment]
could you upload a copy of your ore gen configuration?

**Comment by Davoleo** [comment]
So, apparently the only way that exception can be thrown is if you either:
- use a number greater than 256 as maximum Y level

**Comment by Davoleo** [comment]
If you need to disable some world ore gen I'd suggest you to set the veinSize to 0 instead of tinkering with heights
