### ISSUE TITLE
new update crash some mods i use

### ISSUE THREAD

**Issue by RioSenpai** [Davoleo/Metallurgy-4-Reforged#254]
### General Information

**Describe the bug:**

**To Reproduce:**

1.start
2. crashed
3. cut metalallury to different place 
4-fixed idk why

**Expected behavior:**

***

### Environment Versions

**Versions:**
- Metallurgy: newer
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge:1-industrialcraft 
        2-harvest pam
- Minecraft:1.12.2
- Modpack (if available):RedKnigh

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by Bravarly** [comment]
Can you replicate the crash again and then after the crash, post the log via gist, paste.ee, Pastebin, or some other log sharing service. If you don't know:
1. Go to your .minecraft folder
2. Then go to your log folder
3. Then open the file named latest
4. Copy and paste the contents of the file into Pastebin
5. After creating the Pastebin post, put the Pastebin link here

**Comment by RioSenpai** [comment]
give me a min gonna do it

**Comment by RioSenpai** [comment]
https://pastebin.com/FeVuTvkt 
there

**Comment by Davoleo** [comment]
Unfortunately adding many decorative blocks causes the usage of many new ids, in your case they exceeded the maximum number of possible ids, you can either remove some of the mods or install not enough ids

in a future update I'll also add an option to disable decorative blocks in case you don't want them and want to save some ids
