### ISSUE TITLE
Tools not repairable in anvil in latest update

### ISSUE THREAD

**Issue by Kenja-mc** [Davoleo/Metallurgy-4-Reforged#255]
### General Information

**Describe the bug:**
You cannot use the ingot to repair Metallurgy tools in Anvils.

**To Reproduce:**

1. Give yourself a tool such as a pickaxe, an anvil, and some ingots the tool is made out of.
2. Break some blocks with the tool to get it below 100% durability.
3. Try to repair the tool in the anvil, it won't work.
4. Try again with other tools.

**Expected behavior:**
All tools should have their respective ingot registered as the material to repair in an anvil.

***

### Environment Versions

**Versions:**
- Metallurgy: 1.0.0
- Forge: 14.23.5.2854
- Minecraft: 1.12.2

***
### Additional Information
**Screenshots (if available):**
![Image](https://i.imgur.com/3xPhah4.png)

**Additional context (optional):**
I discovered this when trying to use Pickle Tweaks in my modpack to repair tools. In previous versions I believe this was not an issue.

**Comment by Kenja-mc** [comment]
Sorry, didnt mean to press enter, editing now

**Comment by Davoleo** [comment]
Could you checked whether this option is set to true or false in general.cfg? @Kenja-mc 
![image](https://user-images.githubusercontent.com/24458276/86749974-ed009d80-c03d-11ea-8db6-0ac08e2a959b.png)

**Comment by Kenja-mc** [comment]
Oh my bad, I didn't realize it was a config setting, sorry.
![image](https://i.imgur.com/FlbBLek.png)

**Comment by Davoleo** [comment]
yeah it's a bit strange that it's disabled by default, I may change it in a future update
