### ISSUE TITLE
Adding metals to metal detector while in a Tinkers' Construct Crafting Station Crashes the game

### ISSUE THREAD

**Issue by SioN-wynncraft** [Davoleo/Metallurgy-4-Reforged#260]
I'm playing in my own server 1.12.2, metallurgy 1.0.1 and when I tried to put iron into metal detector in a crafting bench. My game crashed and it always crashes when I try entering the server. 

Crash Report:
[crash-2020-07-09_17.52.34-client.txt](https://github.com/Davoleo/Metallurgy-4-Reforged/files/4897626/crash-2020-07-09_17.52.34-client.txt)

**Comment by Davoleo** [comment]
Is it a normal crafting table or is it another mod's crafting table?
if it's vanilla's do you have any mod that customize / mess with vanilla's crafting bench?
