### ISSUE TITLE
Add Cobalt as a Metal to alloy with or just as another metal. 

### ISSUE THREAD

**Issue by chyper111** [Davoleo/Metallurgy-4-Reforged#262]
**Describe the solution you'd like** <br 
     Its in alot of mods and it can make batteries better. It can also make light heat resistant tools even lava proof. It makes for a cool alloy in real life for mixing stuff and another cool idea is to make a chest that uses electrum and cobalt in the recipe and any item that gets put in the gets recharged. its also a byproduct from alot of other metals so you can make your alloyer discharge it as a byproduct or find it in the wild. Another idea its boots that let you walk on lava or swim through it.

**Why would you like this to be implemented?**  To make a place to sort items to recharge them. To traverse lava lakes and help build on them.
Tell us about the reason(s) why you would implement this feature

**Additional context** (optional) <br>
https://www.cobaltinstitute.org/alloys.html

**Comment by Davoleo** [comment]
I'm sorry, but we won't add anymore metals to the mod due to this reason: https://github.com/Davoleo/Metallurgy-4-Reforged/issues/232#issuecomment-594920951
As such, I'm closing this thread

**Comment by chyper111** [comment]
oh sorry i didnt see that my fault

**Comment by Davoleo** [comment]
No worries, and thanks for understanding
