### ISSUE TITLE
Haderoth lets you walk on lava.

### ISSUE THREAD

**Issue by chyper111** [Davoleo/Metallurgy-4-Reforged#263]
**Describe the solution you'd like** <br>
You could make boots that allow you to traverse over lava or a ring to have in your inventory. its would be great for building and I saw you had the idea already and being a fantasy metal I thought id subject it.

**Why would you like this to be implemented?** <br>
Tell us about the reason(s) why you would implement this feature

**Additional context** (optional) <br>

**Comment by Davoleo** [comment]
uh, yeah we were thinking of making a gadget that allowed you to walk on lava lakes, however making it an armor effect could be interesting as well, although, like other armor effects it will take place only when you're wearing a full armor set of haderoth

**Comment by chyper111** [comment]
Exactly and this armor has no effects plus haderoth kinda makes me think
Hades so i figured it would with well.
