### ISSUE TITLE
Sanguinite should restore health in fire or lava.

### ISSUE THREAD

**Issue by chyper111** [Davoleo/Metallurgy-4-Reforged#264]
**Describe the solution you'd like** <br>
When entering lava or fire you should gain health and while in water lose it like it was lava or at a faster rate. Fireball attacks just heal you and do zero knockback or damage,

**Why would you like this to be implemented?** <br>
Tell us about the reason(s) why you would implement this feature

**Additional context** (optional) <br>

**Comment by Davoleo** [comment]
Sanguinite already has some sort of a life steal effect, although since it's a late-game material it could use a revamp

**Comment by chyper111** [comment]
Hay just saying since its in the nether and im only talking about the armor
I know the sword has life steal.

**Comment by PierKnight100** [comment]
what about the idea of gaining health when killing mobs?
This way this effect makes more sense
@chyper111

**Comment by chyper111** [comment]
Vulcanite cant heal damage from fire attacks and also it's enchatablity makes it very broken. I ment to request to lower it's enchatablity to make it fair with tou other armors. All Vulcantie needs it protection on three pieces and blast protection on the last piece and the you have a ridculas set or armor that makes all the others kinda pointless. Why get tartarrite armor when i could be fire proof blast resistant and have all the enchantments or normal armor. That's to OP in my opinion. Also this armor cool have a cool down to make it not 100% fire proof but have better enchatablity. That would make it fair and different.

**Comment by Davoleo** [comment]
Umh so, both Sanguinite and Vulcanite themes are going to get a new reworked theme based on #277 so they will get different effects, we'll keep this one in mind for Ignatius which is a Fire themed metal
