### ISSUE TITLE
Tartarite should spawn a wither skeleton to aid you as an ally.

### ISSUE THREAD

**Issue by chyper111** [Davoleo/Metallurgy-4-Reforged#265]
**Describe the solution you'd like** <br>
This armor should spawn a freindly wither skeleton to aid you against other enemies when you are attacked or if you draw your Tartarite sword. There should be a time limit for them depending on how much of that armor you are wearing. I would totally call mine "Comrade" as we stop all who dare to challenge us!

**Why would you like this to be implemented?** <br>
Tell us about the reason(s) why you would implement this feature

**Additional context** (optional) <br>

**Comment by Davoleo** [comment]
A similar feature may be implemented in 1.3.0 for Damascus Steel according to #277
