### ISSUE TITLE
Brass TC tools parts | Brass Knuckles Gadget

### ISSUE THREAD

**Issue by Contramalum** [Davoleo/Metallurgy-4-Reforged#267]
It looks like TC no longer recognises brass as a metal - was that intentional, or something on TC's end?

Using Metallurgy Reforged 1.0.1, TC 2.13.0.183. 

Also, just an idea - brass knuckles, as a much weaker version of the Rubacium Gauntlet.

**Comment by Davoleo** [comment]
if I recall correctly tinker has some kind of brass alloy  (that you can use to make casts) although I don't really know why our brass is not recognized I'll investigate more later

**Comment by Davoleo** [comment]
I'm guessing you meant that you couldn't cast armor pieces and tools made with brass, and that's true, I'll push the fix to the repository today (will be released with 1.1.0)

About the knuckles, we'll implement them in a later version
