### ISSUE TITLE
Crafttweaker support regression

### ISSUE THREAD

**Issue by LemADEC** [Davoleo/Metallurgy-4-Reforged#269]
### General Information

**Describe the bug:**
When upgrading from Metallurgy-4-Reforged-0.3.3 to Metallurgy-4-Reforged-1.0.2, recipes have no more IDs and we can't use crafttweaker scripts to change them.

**To Reproduce:**
1. Add CraftTweaker2-1.12-4.1.20.581
2. Have a zs script to remove copper recipes: 
	var ingot = itemUtils.getItem("metallurgy:copper_ingot");
		oreDict.get("ingot" + material).remove(ingot);
		recipes.remove(ingot);
		furnace.remove(ingot);
		mods.jei.JEI.removeAndHide(ingot);
3. Boot the game and check recipes
=> ore dictionary was removed, ok
=> recipes are still present and have no recipeID, NOK
=> furnace recipe is removed, ok
=> item is hidden in JEI, ok

**Expected behavior:**
Ability to change recipes to unity outputs.

### Environment Versions

**Versions:**
- Metallurgy: 1.0.2
- Conflicting mod (if regarding mod integration): CraftTweaker2-1.12-4.1.20.581
- Other mods you think could cause issues: -
- Forge: 14.23.5.2854
- Minecraft: 1.12.2
- Modpack (if available): 14.23.5.2854

### Logging Information
**Crash Report (if available):**
n/a

**Latest Log (if necessary):**
n/a

### Additional Information
**Screenshots (if available):**
n/a

**Additional context (optional):**
n/a

**Comment by Davoleo** [comment]
I've fixed this by returning to basic json recipes although generated by a groovy script, this will be released with 1.1.0
Thanks for reporting it!
