### ISSUE TITLE
Same recipe?

### ISSUE THREAD

**Issue by Klazkin** [Davoleo/Metallurgy-4-Reforged#27]
![42101985bfd4f70bd0b51b0adfc0ab4b](https://user-images.githubusercontent.com/44501483/48676536-d0fe6e80-eb70-11e8-8844-170df4bf4f35.png)
![f428d7f8be8afcee3009b95a23aa12fb](https://user-images.githubusercontent.com/44501483/48676538-d360c880-eb70-11e8-920d-615c3ddeab30.png)
pretty sure electrum was made from silver

**Comment by Davoleo** [comment]
are those 2 the same file or what?

**Comment by Davoleo** [comment]
It is, I often mistake iron with silver, my bad will fix this right now
