### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by Bravarly** [Davoleo/Metallurgy-4-Reforged#273]
I'm looking for further clarification on whether the license for the mod is either `GPL 3.0 only` or `GPL 3.0 or later`.

**Comment by Davoleo** [comment]
as stated on https://www.gnu.org/licenses/licenses.html GPL V3.0 and **older** GPL Versions are incompatible, they're considered  completly different licenses, hence I can say this mod is under the specific license GPL V3.0
Although I'm not sure what you're talking about saying GPL 3.0 or later, cause there is no more recent version of GPL than 3.0

**Comment by Bravarly** [comment]
The GNU team urges developers that use their licenses to specify even if newer versions of said license doesn't exist and highly probable to not be compatible: https://www.gnu.org/licenses/identify-licenses-clearly.en.html

**Comment by Bravarly** [comment]
Also since I'm starting the Fabric port (I was Terantai), any mods licensed under the GPL branch of the GNU licenses as is heavily discouraged for use of mods. The general consensus is that you would require an exception clause for Minecraft. Also, the general consensus was that GPL mods were incompatible for modpacks unless they were submitted to CF as CF's ToS apparently makes it legally possible for it to be included in CF modpacks. Due to the development of other CF alternatives like Diluv and Modrinth, there is no guarantee that their ToS will be like CF's ToS which can make it detrimental to the growth of both versions (Fabric and Forge) of the mod. Any derivative works must be under the GPL license or a more restictive, compatible license, which includes any work that references M4:R's code. I highly recommend that you relicense to LGPL as that is much more compatible and doesn't harm the detriment of M4:R nor its soon-to-be Fabric counterpart.

**Comment by Davoleo** [comment]
I should mention that I first decided to lincense Metallurgy 4: Reforged under GPL V3 being it a derivative work of Metallurgy 4, it had the same features and assets and so we decided to license it under a compatible one, at that time I wasn't aware that the original source code was under LGPL and seeing the project on curseforge I did assume it was GPL V3

Anyways, LGPL is usually just used in libraries that actually need to be included but are included in a large variety of works
and personally, I don't mind this mod to be only releasable on Curseforge
