### ISSUE TITLE
Angmallen integration with Tinker's?

### ISSUE THREAD

**Issue by LemADEC** [Davoleo/Metallurgy-4-Reforged#274]
### General Information

**Describe the bug:**
Unable to use Angmallen nuggets to repair Tinker's tool and Angmallen ingots have no effect.

**To Reproduce:**
1. Create an Angmallen tinker's pickaxe
2. Break a few block
3. Open a tinker's tool forge, try to use Angmallen nuggets to repair your pickaxe
=> no output is shown
4. Try to use Angmallen ingots to repair your pickaxe
=> output is shown but no repair actually happens
5. Try to use Angmallen reoair kit to repair your pickaxe
=> output is shown and repair actually happens

**Expected behavior:**
Nuggets should be accepted as repair material.
Nuggets & ingots should actually repair.

### Environment Versions
**Versions:**
- Metallurgy: Metallurgy-4-Reforged-1.0.2
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues: plustic-8.0.1.0 (xXx_MoreToolMats_xXx), TConstruct-1.12.2-2.13.0.183
- Forge: 14.23.5.2854
- Minecraft: 1.12.2
- Modpack (if available): 
Mantle-1.12-1.3.3.55
jei_1.12.2-4.15.0.297.
no other mods, single player 

### Logging Information
**Crash Report (if available):**
n/a

**Latest Log (if necessary):**
https://gist.github.com/LemADEC/3b23f7c1ab4884ae842d463a4d32fa1c

### Additional Information
**Screenshots (if available):**
n/a

**Additional context (optional):**
This could be a bug in PlusTIC. I didn't try other alloy materials from Metallurgy.

**Comment by Davoleo** [comment]
I think someone did mention this to me some time ago with another material, I wonder what's the issue behind it 🤔

**Comment by LemADEC** [comment]
Amordrine doesn't accept nuggets, doesn't repair with ingots.
Krik doesn't accept nuggets, doesn't repair with ingots.
Quicksilver doesn't accept nuggets, DOES repair with ingots.
Vulcanite doesn't accept nuggets, DOES repair with ingots.
so, I guess alloy materials aren't properly registered, causing the lack of repair with ingots?
That still doesn't explain the nuggets through...
