### ISSUE TITLE
Memory leak in EventUtils

### ISSUE THREAD

**Issue by LemADEC** [Davoleo/Metallurgy-4-Reforged#280]
### General Information

**Describe the bug:**
A new ArrayList is created for every player every tick
https://github.com/Davoleo/Metallurgy-4-Reforged/blob/20f1df9d6681b2a8e2c3df8ea10c05c487036dbf/src/main/java/it/hurts/metallurgy_reforged/util/EventUtils.java#L66
From a quick check, this is doubled depending on OsmiumLutetium availability?

**To Reproduce:**
Profiling & Code review

**Expected behavior:**
Avoid memory allocation in event handlers.

***

### Environment Versions
**Versions:**
- Metallurgy: 1.0.2
- Conflicting mod (if regarding mod integration): none
- Other mods you think could cause issues: none
- Forge: 14.23.5.2854
- Minecraft: 1.12.2
- Modpack (if available): https://www.curseforge.com/minecraft/modpacks/fsg-arcania-craft/files/3025855

***

### Logging Information

**Crash Report (if available):**
n/a

**Latest Log (if necessary):**
n/a

***

### Additional Information
**Screenshots (if available):**
n/a

**Additional context (optional):**
n/a

**Comment by Davoleo** [comment]
oof, that code has been there for quite a while, thanks for reporting it
