### ISSUE TITLE
Mekanism enrichment chamber rejects lutetium metallurgy ore

### ISSUE THREAD

**Issue by Klazkin** [Davoleo/Metallurgy-4-Reforged#290]
Mekanism enrichment chambers reject lutetium metallurgy ore. (I didn't test every ore, but it seems its only Lutetium)

this is probably on mekanism's side but still really wierd.

**Comment by Davoleo** [comment]
yeah both lutetium ore and lutetium dust have their respective oreDict entries
It's probably an edge case of Mekanism, but there's nothing I can do in our code to ease compatibility, nothing that I know of... 🤔 
![image](https://user-images.githubusercontent.com/24458276/94812700-5b63ba80-03f7-11eb-96a9-9e05d4ee5ae0.png)

and yes, Lutetium is the only ore that has this problem

**Comment by Davoleo** [comment]
Mekanism's not actively developing 1.12.2 and implementing some specific intergation code to fix this is not worth it compared to the severity of the consequences if this wasn't fixed, if anyone really wishes to have this back they can use a CraftTweaker script to achieve it
