### ISSUE TITLE
Ore braking texture missing 

### ISSUE THREAD

**Issue by disastercube** [Davoleo/Metallurgy-4-Reforged#292]
**Whenever you brake an ore there is a texture missing for the particles.**

![2020-10-04_10 15 35](https://user-images.githubusercontent.com/62697421/95010556-9863c300-062a-11eb-9a3f-8ec5f39ea973.png)
![2020-10-04_10 15 36](https://user-images.githubusercontent.com/62697421/95010558-9a2d8680-062a-11eb-88e0-b0321ca0ed4b.png)
![2020-10-04_10 15 41](https://user-images.githubusercontent.com/62697421/95010559-9b5eb380-062a-11eb-814f-309ea9027a9f.png)
![2020-10-04_10 15 42](https://user-images.githubusercontent.com/62697421/95010561-9d287700-062a-11eb-8f60-932b70460994.png)

**Comment by Davoleo** [comment]
Yeah this is already fixed in my dev env, I'll probably release the patch today

**Comment by Davoleo** [comment]
Commit Ref: https://github.com/Davoleo/Metallurgy-4-Reforged/commit/a0d7f7c2c5654fea0413ff782c8667dab91a9d6f
