### ISSUE TITLE
Vanilla texture replacement 

### ISSUE THREAD

**Issue by disastercube** [Davoleo/Metallurgy-4-Reforged#293]
I still remember when this mod in 1.6.4 used to replace vanilla tool and armor textures with their own variations / style.
It would be nice if this feature could be brought back, with the ability to toggle it in the config file. 

**Example:**
![aaaa](https://user-images.githubusercontent.com/62697421/95017729-64ed5c80-065b-11eb-8969-3a75da2c0191.png)

**Comment by Davoleo** [comment]
This won't be a priority, I'll assign it to the 1.4.0 milestone for now and we'll discuss this later
but we might choose to not implement this at all, since we're not overriding anything in vanilla right now in the mod and we may want to keep things like this

**Comment by SkyanUltra** [comment]
if anything, a resource pack could be made that is linked on the curseforge page, along with perhaps a vanilla styled resourcepack to change all the metallurgy stuff to be more akin to the vanilla art style.

**Comment by Klazkin** [comment]
> if anything, a resource pack could be made that is linked on the curseforge page, along with perhaps a vanilla styled resourcepack to change all the metallurgy stuff to be more akin to the vanilla art style.

Maybe, I will decided on how to go about it when I get to work on it, as this is not as important as some other things that still require work.
