### ISSUE TITLE
Unnecessary/Unexplainable Console Spam due-to Metallurgy 4: Reforged

### ISSUE THREAD

**Issue by XIPure** [Davoleo/Metallurgy-4-Reforged#304]
Hi there! 😄 

When I'm playing with many mods including Metallurgy 4: Reforged which is enabled/installed/fully-working (Of Course), I at some point whilst in the world will start to see the most unnecessary yet unexplainable console spam, a lot of **_7_** 's on My other monitor in MultiMC's Instance's Minecraft-Log and/or Console. Yeah, that's right, one single number spammed over and over again which I'm not gonna lie is a bit frustrating, lol. This can happen at COMPLETELY RANDOM TIMES WHEN IN A MINECRAFT WORLD OF ANY KIND, EVEN A NEWLY GENERATED ONE.

This occurs when I'm in-game, stood still or exploring the surrounding area(s) and in whatever gamemode (Survival/Creative/Spectator). This can also happen when I am e.g... typing something in Discord/Google-Chrome on My other monitor(s) whilst Minecraft is running + I'm in My inventory or in JEI or in the in-game-chat.

I have generated a lot of new worlds to be 100% sure that it wasn't a one-off type of bug, but nope, it's definitely an active bug with Metallurgy 4: Reforged. Why do I say this mod in particular? Because I've also been spending the past 4-5 hours disabling/enabling mods, one by one by one to see if the **_7_** spam was going to occur and it didn't (Whilst Metallurgy 4: Reforged was disabled) which was nice to see for once, haha. 

Or as someone I know on Discord phrased it, I "binary-searched" through all of the mods, haha lol 😂 (I'm not a mod-dev/coder so I hadn't heard of this term until recently!)

Anyway, going back to the bug:

**To Reproduce:**
I hate to say this and I know it doesn't really help from the developer's perspective/point-of-view and I would like to apologize in advance for this but, I don't really know if there is a way to physically reproduce this bug if I'm going to be brutally honest. I have provided pictures (x2) in advance which shows the unexpected behavior/console-spam.

**Expected behavior:**
For this to not happen **_at all_**..? 😅 

### Environment Versions
I'm not sure what "Environment Version(s)" means but I'd be happy to answer this question asap/whenever the developer(s) can explain to Me what this means 👍 I'd appreciate it!

**Versions:**
- Metallurgy: 4 Reforged: 1.2.0
- Conflicting mod (if regarding mod integration): N/A ?
- Other mods you think could cause issues: N/A ?
- Forge: 14.23.5.2854
- Minecraft: 1.12.2
- MultiMC 5 (Launcher): 0.6.11-1430
- Modpack (if available): N/A, It's My own thus far, I'm still adding mods bit by bit

### Logging Information
Here are some logs from a couple days ago: 
https://paste.ee/p/G9YUg#s=0&l=13679 <- I would like to refer You to Lines 13679 through to 13794 where this spam begins to take place in the Minecraft-Console. That's example 1.

https://paste.ee/p/z0Cuc#s=0&l=10401 <- I would like to refer You to Lines 10401 through to 10414 where this spam begins to take place in the Minecraft-Console. That's example 2.

### Additional Information
![image](https://user-images.githubusercontent.com/47751365/103393036-9f5e7c80-4b18-11eb-890a-d46b3b68be6a.png)
![image](https://user-images.githubusercontent.com/47751365/103393070-b00ef280-4b18-11eb-8625-698f231f9cc0.png)

**Additional context (optional):**
I'm very highly convinced that it's Metallurgy 4: Reforged that's causing this issue as I have had no console spam with the other mods whilst Metallurgy 4: Reforged was disabled via MultiMC, but when I re-enabled Metallurgy 4: Reforged, BAM, HERE COMES THE CONSOLE SPAM =/ Lol :3 

If You have any other questions, I'd be more than happy to answer them. The same goes for testing, if You want Me to test anything in particular, I'm fine with that! One final comment I would like to also make is that I have had 2 people via Discord test this for Me with the exact same config files / versions of the mods+forge, they had experienced similar issues aka console spam.

Thanks! I look forward to a reply / hope this can be fixed!
-XIPure

**Comment by Davoleo** [comment]
First of all, thanks for the big amount of testing,
Embarrassingly enough this is probably an oversight of mine that I introduced in this commit https://github.com/Davoleo/Metallurgy-4-Reforged/commit/852461a33948111ed92ef7e001a77f4c979824a4 on the 3rd of August 2020
Will be fixed in the next 1.2 patch version

**Comment by XIPure** [comment]
@Davoleo Hi, Haha no worries and thank you so so much, I've been trying to hunt down the main cause of this console spam for the past, like, 3-4 days even(?) because it's been bugging Me **_that much_**, lol. I should have wrote that above really, but oh well ¯\_(ツ)_/¯


When can I/The-public expect to see 1.2.2 (I assume it's being called this) for MC 1.12.2 on CurseForge roughly? In early JAN-2021? Or?


Thanks! 👍

**Comment by Davoleo** [comment]
I've just uploaded and has been approved about 4 mins ago, here's the link to it: https://www.curseforge.com/minecraft/mc-mods/metallurgy-4-reforged/files/3154342
Also had some features and fixes in the backlog, so the changelog contains those as well

**Comment by XIPure** [comment]
@Davoleo Nice one, thanks! ❤️ 
Upon further testing within the past 30 mins, I can confirm it's no longer happening with the rest of the mods which are now RE-ENABLED, so.. yeah, thanks for fixing that, I very heavily appreciate it! And I forgot to write this in My prev. comment but You're welcome 😄 for the big amount(s) of testing, haha lol
