### ISSUE TITLE
NPE with Desichalkos sword effect

### ISSUE THREAD

**Issue by LemADEC** [Davoleo/Metallurgy-4-Reforged#311]
### General Information

**Describe the bug:**
Tried to use the Desichalkos sword effect in SSP, client crashed on NPE

**To Reproduce:**
1. Hold Desichalkos sword
2. Target a block more than 10 m away
2. Right click

**Expected behavior:**
no crash

***

### Environment Versions

**Versions:**
- Metallurgy: 1.2.4
- Conflicting mod (if regarding mod integration): Unknown
- Other mods you think could cause issues: Unknown
- Forge: 1.12.2-14.23.5.2855
- Minecraft: 1.12.2
- Modpack (if available): https://www.curseforge.com/minecraft/modpacks/worldwarminecraft/files (11.7.0 in dev)

***

### Logging Information

**Crash Report (if available):**
https://gist.github.com/LemADEC/5be357cc8d1a49d601f112f710926f44

**Latest Log (if necessary):**
n/a

**Comment by Davoleo** [comment]
I can't seem to reproduce this in my dev env
The crash report also refers to line 82 which is the first line of the switch statement where I check the different cases of sideHit, for the code to cause NPE on that line the RayTraceResult variable should be null, but that can't be since I specifically exclude that case via the if statement above that line

**Comment by LemADEC** [comment]
The NPE comes from sideHit itself being NULL. Java doesn't support NULL inputs to switch statements.
Issue is reproduced with malisiscore-1.12.2-6.5.1 that notably changes the World::rayTraceBlocks() method.

**Comment by Davoleo** [comment]
mmh, what would be the situation when sideHit is null though?
when no blocks are found the RayTraceResult itself is null, but when a Block rayTraceResult exists there has to be one side of the block which was hit by the raytrace 🤔

**Comment by LemADEC** [comment]
Maybe adding a check for result.typeOfHit != Type.MISS would help here?

**Comment by Davoleo** [comment]
I guess so, it's hard to check whether that fixes the issue though since I haven't even been able to reproduce it in the first place.
I'll include it in the next patch version so you can tell me if you're still experiencing this issue

**Comment by LemADEC** [comment]
just add MalisisCore to your mods and it'll trigger when you target the sky. Or drop a patched version here?

**Comment by Davoleo** [comment]
oh, sorry yeah it's late and I didn't read your previous comment correctly, will investigate tomorrow really need to get some sleep now 😅

**Comment by LemADEC** [comment]
sleep first, no urgency :)
