### ISSUE TITLE
[1.12.2] Game crash

### ISSUE THREAD

**Issue by W1nter-isHere** [Davoleo/Metallurgy-4-Reforged#312]
### General Information
Game crash when launching might be something with effect registration after disabling them in the config.

**Describe the bug:**
Information above ^

**To Reproduce:**
I'm not entirely sure what I did to make it crash, but I've disabled all set effects in the config, disabled ore gen, I think that's about it.

**Expected behavior:**
The game should launch without a crash
***

### Environment Versions
Uh information below

**Versions:**
- Metallurgy: 1.2.5
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge:2854
- Minecraft:1.12.2
- Modpack (if available): N/A

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**
https://gist.github.com/W1nter-isHere/936a073738069b4ba3a5eca0b91aa819 Crashlog

**Crash Report (if available):**
Information above ^

**Latest Log (if necessary):**
N/A

***

### Additional Information
**Screenshots (if available):**
N/A

**Additional context (optional):**
N/a

**Comment by Davoleo** [comment]
Seems like the old 1.2.5 jar was corrupted; I've built the mod again without code changes and everything seems to work fine
I'll archive and re-upload 1.2.5.
Please update/reinstall the mod when you can!

**Comment by W1nter-isHere** [comment]
Thank you! I will try that

**Comment by W1nter-isHere** [comment]
Yep its working now, thank you so much!
