### ISSUE TITLE
Additional Configuration Options for Metallurgy's TiC Support

### ISSUE THREAD

**Issue by SkyanUltra** [Davoleo/Metallurgy-4-Reforged#315]
More config options for TiC support:
- Tweaks for metals and their minimum temperatures to be melted in the Smeltery/Melter (Works very well with Tinkers' Complement, and would allow modpack devs to gate ores behind things like the smeltery, which could be made harder to get and require using the melter/alloyer.
- Tweaks for the temperature of Thermite.

This would allow modpack devs to make a more concise progression line to block players from using things from Tinkers' Complement like the Melter and Alloyer, requiring that players progress towards getting a Smeltery.

**Comment by Davoleo** [comment]
Ok,
you can configure Thermite temperature from the Gadgets Config file from `1.2.8`

While you'll be able to configure a custom temperature for each metal in `1.2.10`, to do this just add a `temperature` property with the desired temperature (unit is Kelvin)
```json
{
  "name": "adamantine",
  "other": "properties",
  "temperature": 321,
  "other": "properties",
}
```
