### ISSUE TITLE
Crafttweaker Recipe Change Applies to Recipes it Shouldn't Be.

### ISSUE THREAD

**Issue by puncrafter** [Davoleo/Metallurgy-4-Reforged#317]
### General Information

**Describe the bug:**
I have a crafttweaker script that changes the recipe of the fancy gold blocks to use a different ingredient instead of gold. For some reason, it is also replacing gold in the alloyer recipes for electrum and angmallen to use the new ingredient as well! In this case, it's with an ore dictionary entry, but I imagine it would work with anything.

**To Reproduce:**
I have put the important slice of crafttweaker script down below. When I comment out this part of the script, it also removes the alloyer recipes, so I know it's this script causing it.

**Expected behavior:**
It shouldn't change recipes that I didn't tell it to.

***

### Environment Versions

**Versions:**
- Metallurgy: Metallurgy-4-Reforged-1.2.5
- Conflicting mod (if regarding mod integration): CraftTweaker2-1.12-4.1.20.618
- Forge: 14.23.5.2854
- Minecraft: 1.12.2

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**
N/A

**Latest Log (if necessary):**
I don't think this is necessary.

***

### Additional Information
**Screenshots (if available):**
N/A

**Additional context (optional):**
I hope this is a metallurgy issue and not a crafttweaker one!

> import crafttweaker.item.IItemStack;
import crafttweaker.recipes.ICraftingRecipe;
    var goldStuff = [
    <metallurgy:gold_reinforced_glass>, 
    <metallurgy:gold_large_bricks>, 
    <metallurgy:gold_hazard_block>,
    <metallurgy:gold_engraved_block>,
    <metallurgy:gold_crystals>,
    <metallurgy:gold_bricks>
] as IItemStack[];
for item in goldStuff {
    recipes.replaceAllOccurences(<minecraft:gold_ingot>, <ore:imitationGold>, item);
    recipes.replaceAllOccurences(<minecraft:gold_nugget>, <ore:imitationGoldNugget>, item);
}

**Comment by Davoleo** [comment]
except I had to add crafttweaker angular brackets to every item `<>` for the script to work, but it's doing its job correctly, with regular items
```zs
import mods.metallurgyreforged.Crusher;
import crafttweaker.item.IItemStack;
import crafttweaker.recipes.ICraftingRecipe;

var goldStuff = [
    <metallurgy:gold_reinforced_glass>,
    <metallurgy:gold_large_bricks>,
    <metallurgy:gold_hazard_block>,
    <metallurgy:gold_engraved_block>,
    <metallurgy:gold_crystals>,
    <metallurgy:gold_bricks>
] as IItemStack[];

for item in goldStuff {
    recipes.replaceAllOccurences(<minecraft:gold_ingot>, <minecraft:brown_mushroom>, item);
    recipes.replaceAllOccurences(<minecraft:gold_nugget>, <minecraft:egg>, item);
}
```
![image](https://user-images.githubusercontent.com/24458276/112756883-66cf2180-8fe7-11eb-9b5b-43cf2cc265dd.png)

and other recipes like electrum don't seem to be changed:
![image](https://user-images.githubusercontent.com/24458276/112756895-78b0c480-8fe7-11eb-8e6a-269ae5096a9e.png)

**Comment by Davoleo** [comment]
As a second test I've setup some fictional Oredictionary Entries to be able to test in the exact same condition as yours:
```zs
import mods.metallurgyreforged.Crusher;
import crafttweaker.item.IItemStack;
import crafttweaker.recipes.ICraftingRecipe;

//Setup Oredictionary entries
val imitationGold = <ore:imitationGold>;
val imitationGoldNugget = <ore:imitationGoldNugget>;
imitationGold.add(<minecraft:tallgrass>);
imitationGoldNugget.add(<minecraft:dirt>);

var goldStuff = [
    <metallurgy:gold_reinforced_glass>,
    <metallurgy:gold_large_bricks>,
    <metallurgy:gold_hazard_block>,
    <metallurgy:gold_engraved_block>,
    <metallurgy:gold_crystals>,
    <metallurgy:gold_bricks>
] as IItemStack[];

for item in goldStuff {
    recipes.replaceAllOccurences(<minecraft:gold_ingot>, <ore:imitationGold>, item);
    recipes.replaceAllOccurences(<minecraft:gold_nugget>, <ore:imitationGoldNugget>, item);
}
```
Even in this case recipes seem to be working correctly
![image](https://user-images.githubusercontent.com/24458276/112757107-9a5e7b80-8fe8-11eb-8373-a89c008e01b3.png)
and they're not conflicting with other things like electrum
![image](https://user-images.githubusercontent.com/24458276/112757124-ac401e80-8fe8-11eb-9d9c-5b0a1f581cb0.png)
if I lookup all the recipes that contain bushes only the correct ones appear
![image](https://user-images.githubusercontent.com/24458276/112757162-dbef2680-8fe8-11eb-8cf8-37215b01569f.png)

**Comment by puncrafter** [comment]
Well, that's strange... the bug stopped occuring once I removed gold ingots from the `imitationGold` oredict entry. As soon as I re-add gold ingots to the oredict entry, the problem returns. Try adding gold ingots to the entry and see if that lets you reproduce the issue.
