### ISSUE TITLE
Minetweaker machine recipes not working

### ISSUE THREAD

**Issue by Breadabix** [Davoleo/Metallurgy-4-Reforged#318]
### General Information

**Describe the bug:**
I am trying to remove the alloyer recipe for steel and replace it with one that makes thermal expansion steel, however no matter what I try the recipe changes arent working. I have followed the examples on github and even they dont work

**To Reproduce:**
1. Install latest versions of minetweaker and metallurgy
2. Use this script and load the game 
[Script.zip](https://github.com/Davoleo/Metallurgy-4-Reforged/files/6215609/Script.zip)

**Expected behavior:**
I would expect the recipe changes to work.

### Environment Versions

**Versions:**
- Metallurgy: Metallurgy-4-Reforged-1.2.5
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: 14.23.5.2855
- Minecraft: 1.12.2
- Modpack (if available):

**Comment by Davoleo** [comment]
looks like I can remove alloyer recipes without any issues in my dev env

Testing script:
```zs
import mods.metallurgyreforged.Alloyer;

Alloyer.removeRecipe(<metallurgy:steel_ingot> *2);

Alloyer.addRecipe(<minecraft:iron_ingot>, <metallurgy:manganese_ingot> * 2, <minecraft:brown_mushroom> * 2);
```
(I've just changed thermal foundation's steel with a mushroom because I don't have thermal in my env)

My first guess would be that there's something wrong with your setup, can you share you version of CraftTweaker and the contents of the crafttweaker log in the instance directory?

**Comment by Breadabix** [comment]
Ive found it is letting me remove and add the recipes, but whenever I add a recipe for thermal expansion ingots if there is a metallurgy equivalent it turns the recipe to that. I have just added the steel recipe for thermal expansion copper and its defaulted to metallurgy copper.

**Comment by Davoleo** [comment]
ok so, this might be related or totally the same as #317 
I'll test to see if the fix for that issue also fixed this one.
