### ISSUE TITLE
Sword's Abilities are Mixed Up

### ISSUE THREAD

**Issue by puncrafter** [Davoleo/Metallurgy-4-Reforged#319]
### General Information

**Describe the bug:**
The Deep Iron Sword increases the attack speed of the weapon when in water, but it also has Celengils's "Your kills make you feel Strong & Quick" ability. Also, the Celengil Sword has no ability. In addition to this, the Orichalcum Sword does not have its ability, and if another sword has it, I can't find which one.

**To Reproduce:**
It is evident once you kill things with the swords.

**Expected behavior:**
The swords should have their respective abilities.

***

### Environment Versions

**Versions:**
- Metallurgy: 1.2.5
- Conflicting mod (if regarding mod integration): N/A
- Other mods you think could cause issues: N/A
- Forge: 14.23.5.2854
- Minecraft: 1.12.2
- Modpack (if available): N/A

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**
N/A

**Latest Log (if necessary):**
N/A

***

### Additional Information
**Screenshots (if available):**
N/A

**Additional context (optional):**
N/A

**Comment by Davoleo** [comment]
whoops that's a big derp of mine

had this in the code
```java
		if (ModMetals.CELENEGIL != null)
			celenegilSword = ModMetals.DEEP_IRON.getTool(EnumTools.SWORD);
		if (ModMetals.ORICHALCUM != null)
			orichalcumSword = ModMetals.SHADOW_STEEL.getTool(EnumTools.SWORD);
```

Will be fixed in the next patch: `1.2.6`
