### ISSUE TITLE
Oregen doesn't seem to be respecting biome choices

### ISSUE THREAD

**Issue by puncrafter** [Davoleo/Metallurgy-4-Reforged#320]
### General Information

**Describe the bug:**
I set up the ore generation config to only spawn certain ores in certain biomes, and the ores are continuing to spawn wherever they please. However, the ores that I disabled aren't spawning, as expected.

**To Reproduce:**
See the additional context.

**Expected behavior:**
It shouldn't do that
***

### Environment Versions

**Versions:**
- Metallurgy: 1.2.5
- Conflicting mod (if regarding mod integration): N/A
- Other mods you think could cause issues: N/A
- Forge: 14.23.5.2854
- Minecraft: 1.12.2
- Modpack (if available): N/A

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**
N/A

**Latest Log (if necessary):**
N/A

***

### Additional Information
**Screenshots (if available):**
N/A

**Additional context (optional):**
The worldgen config is as [follows](https://pastebin.com/Lqk7Z2Xp). I can provide other configs if needed.

**Comment by PierKnight** [comment]
Fixed in commit 77c25eb
