### ISSUE TITLE
Crash with AW2

### ISSUE THREAD

**Issue by Thepigemperor2** [Davoleo/Metallurgy-4-Reforged#325]
### General Information

**Describe the bug:**
the game crashes when a combat npc from Ancient Warfare 2 tries to use the lemurite shield to block

**To Reproduce:**

1. spawn an AW2 combat npc 
2. equip the NPC with the lemurite shield
3. when the NPC uses the shield, the game will crash

***

### Environment Versions

**Versions:**
- Metallurgy: Metallurgy-4-Reforged-1.2.5.jar
- Conflicting mod (if regarding mod integration): ancientwarfare-1.12.2-2.7.0.1032.jar
- Other mods you think could cause issues:
- Forge: 14.23.5.2854
- Minecraft: 1.12.2
- Modpack (if available):

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

https://pastebin.com/HUUWfrRp

**Comment by Davoleo** [comment]
thanks for taking the time to report this, will be fixed in 1.2.7
commit ref: https://github.com/Davoleo/Metallurgy-4-Reforged/commit/28bc55bdf1607f684bbb285f2f7dd57c04475388
