### ISSUE TITLE
Midas tools is broken!!!

### ISSUE THREAD

**Issue by Evilerballon5** [Davoleo/Metallurgy-4-Reforged#328]
Hello, I have played this mod for so long and I never paid attention to this page but I would like to contribute a little about something that displeases me. When I go to the nether, I find this ore very fast and I did not give much importance to its use since it did not last long, but I realized that it doubled the ore blocks. Everything there normal, thinking that it was like the charm of luck, but I realized something broken.
 I was breaking blocks from another mod with my enchanted steel pickaxe but I didn't want it to break, so I changed for the Midas one, and when I broke it, I duplicated the object, it wasn't just any block, it was like an expensive crafting mechanism, as if it were the furnace of this mod but break it with the pickaxe and now I have 2 without spending more ingots.
So I went further, breaking iron blocks, and I got 2, I continued with the diamond ones, and still, I got between 2 or 3 rarely 4 blocks for 1-3 use of this pick, so I corrupted myself with Midas, I broke blocks and more blocks from Midas to get more picks and not to craft blocks from other mods to not spend ores and not to explore in the mines.
I got bored after 2-3 days of finding this peak and decided to erase the world as it was not the same as exploring.
What a sad story but hey, I hope nobody happens to him.

**Comment by Evilerballon5** [comment]
I just want you to know about this bug so it doesn't happen to you

**Comment by Evilerballon5** [comment]
I just want you to know about this bug so it doesn't happen to you

**Comment by Davoleo** [comment]
Not to sure about this, but I'm sure all tool and armor effects will be reworked in 1.3.0, so this will be addressed there for sure
