### ISSUE TITLE
Server crashes while client does not.

### ISSUE THREAD

**Issue by Karanime** [Davoleo/Metallurgy-4-Reforged#329]
Hi. Please let me know if there's a more appropriate place for bug reports. This custom pack works fine on single player, but a dedicated server crashes with this report.

`---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2021-05-30 06:46:27 EDT
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Metallurgy 4: Reforged (metallurgy)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle
    at it.hurts.metallurgy_reforged.effect.MetallurgyEffects.<clinit>(MetallurgyEffects.java:62)
    at it.hurts.metallurgy_reforged.util.SubEvent.init(SubEvent.java:38)
    at it.hurts.metallurgy_reforged.Metallurgy.preInit(Metallurgy.java:98)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.Particle
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 38 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@65ec8b24 from coremod FMLCorePlugin
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    ... 40 more
Caused by: java.lang.RuntimeException: Attempted to load class btf for invalid side SERVER
    at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
    ... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 4.15.0-124-generic
  Java Version: 1.8.0_282, Oracle Corporation
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 605845160 bytes (577 MB) / 1993867264 bytes (1901 MB) up to 5726797824 bytes (5461 MB)
  JVM Flags: 2 total; -Xms128M -Xmx6144M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 143 mods loaded, 143 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                | Version                  | Source                                         | Signature                                |
       |:----- |:--------------------------------- |:------------------------ |:---------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft                         | 1.12.2                   | minecraft.jar                                  | None                                     |
       | LCH   | mcp                               | 9.42                     | minecraft.jar                                  | None                                     |
       | LCH   | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                             | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | ivtoolkit                         | 1.3.3-1.12               | minecraft.jar                                  | None                                     |
       | LCH   | xaeroworldmap_core                | 1.12.2-1.0               | minecraft.jar                                  | None                                     |
       | LCH   | randompatches                     | 1.12.2-1.22.1.10         | randompatches-1.12.2-1.22.1.10.jar             | None                                     |
       | LCH   | tweakersconstruct                 | 1.12.2-1.6.1             | tweakersconstruct-1.12.2-1.6.1.jar             | None                                     |
       | LCH   | forgeendertech                    | 1.12.2-4.5.5.0           | ForgeEndertech-1.12.2-4.5.5.0-build.0561.jar   | None                                     |
       | LCH   | adhooks                           | 1.12.2-3.3.0.0           | AdHooks-1.12.2-3.3.0.0-build.0528.jar          | None                                     |
       | LCH   | akashictome                       | 1.2-12                   | AkashicTome-1.2-12.jar                         | None                                     |
       | LCH   | crafttweaker                      | 4.1.20                   | CraftTweaker2-1.12-4.1.20.646.jar              | None                                     |
       | LCH   | mtlib                             | 3.0.7                    | MTLib-3.0.7.jar                                | None                                     |
       | LCH   | modtweaker                        | 4.0.19                   | modtweaker-4.0.19.jar                          | None                                     |
       | LCH   | jei                               | 4.16.1.302               | jei_1.12.2-4.16.1.302.jar                      | None                                     |
       | LCH   | appleskin                         | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                    | None                                     |
       | LCH   | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                       | None                                     |
       | LCH   | ccm                               | 1.0                      | ccm-1.0.jar                                    | None                                     |
       | LCH   | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                         | None                                     |
       | LCH   | endercore                         | 1.12.2-0.5.76            | EnderCore-1.12.2-0.5.76.jar                    | None                                     |
       | LCH   | enderio                           | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                      | None                                     |
       | LCH   | enderiointegrationtic             | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                      | None                                     |
       | LCH   | quark                             | r1.6-179                 | Quark-r1.6-179.jar                             | None                                     |
       | LCH   | twilightforest                    | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar  | None                                     |
       | LCH   | tconstruct                        | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar               | None                                     |
       | LCH   | conarm                            | 1.2.5.10                 | conarm-1.12.2-1.2.5.10.jar                     | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
       | LCH   | armoryexpansion                   | 2.0.0-alpha              | armoryexpansion-2.0.0-alpha.jar                | None                                     |
       | LCH   | armoryexpansion-custommaterials   | 2.0.0-alpha              | armoryexpansion-2.0.0-alpha.jar                | None                                     |
       | LCH   | armoryexpansion-iceandfire        | 2.0.0-alpha              | armoryexpansion-2.0.0-alpha.jar                | None                                     |
       | LCH   | armoryexpansion-matteroverdrive   | 2.0.0-alpha              | armoryexpansion-2.0.0-alpha.jar                | None                                     |
       | LCH   | armoryexpansion-bitsandpieces     | 0.0.1                    | armoryexpansion-bitsandpieces-0.0.1.jar        | None                                     |
       | LCH   | autoreglib                        | 1.3-32                   | AutoRegLib-1.3-32.jar                          | None                                     |
       | LCH   | mmdlib                            | 1.0.0-rc2                | MMDLib-1.12-1.0.0-rc2.36.jar                   | None                                     |
       | LCH   | basemetals                        | 2.5.0-rc2                | BaseMetals-1.12-2.5.0-rc2.332.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | bettercaves                       | 1.12.2                   | bettercaves-1.12.2-2.0.4.jar                   | None                                     |
       | LCH   | bettermineshafts                  | 1.12.2-2.2.1             | BetterMineshaftsForge-1.12.2-2.2.1.jar         | None                                     |
       | LCH   | betterthanmending                 | 1.1.2                    | BetterThanMending-1.1.2.jar                    | None                                     |
       | LCH   | biomesoplenty                     | 7.0.1.2444               | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar  | None                                     |
       | LCH   | bonsaitrees                       | 1.1.4                    | bonsaitrees-1.1.4-b170.jar                     | None                                     |
       | LCH   | bountifulbaubles                  | 0.0.1                    | Bountiful Baubles-1.12.2-0.1.6.jar             | None                                     |
       | LCH   | buildinggadgets                   | 2.8.4                    | BuildingGadgets-2.8.4.jar                      | None                                     |
       | LCH   | carryon                           | 1.12.3                   | carryon-1.12.2-1.12.4.16.jar                   | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
       | LCH   | castle_dungeons                   | 1.3                      | castle_dungeons-2.2-1.12.2-forge.jar           | None                                     |
       | LCH   | chameleon                         | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                       | None                                     |
       | LCH   | geckolib3                         | 3.0.0                    | forge-1.12.2-geckolib-3.0.0-beta.7.jar         | None                                     |
       | LCH   | cqrepoured                        | 2.5.3B                   | Chocolate_Quest_Repoured-1.12.2-2.5.3B.jar     | None                                     |
       | LCH   | shadowmc                          | 3.8.0                    | ShadowMC-1.12-3.8.0.jar                        | None                                     |
       | LCH   | clipboard                         | @VERSION@                | Clipboard-1.12-1.3.0.jar                       | None                                     |
       | LCH   | clumps                            | 3.1.2                    | Clumps-3.1.2.jar                               | None                                     |
       | LCH   | codechickenlib                    | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | comforts                          | 1.4.1.3                  | comforts-1.12.2-1.4.1.3.jar                    | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCH   | extendedrenderer                  | v1.0                     | coroutil-1.12.1-1.2.37.jar                     | None                                     |
       | LCH   | coroutil                          | 1.12.1-1.2.37            | coroutil-1.12.1-1.2.37.jar                     | None                                     |
       | LCH   | configmod                         | v1.0                     | coroutil-1.12.1-1.2.37.jar                     | None                                     |
       | LCH   | cosmeticarmorreworked             | 1.12.2-v5a               | CosmeticArmorReworked-1.12.2-v5a.jar           | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCH   | craftingcraft                     | 6.1.3                    | CraftingCraft_1.12-6.1.3.jar                   | None                                     |
       | LCH   | crafttweakerjei                   | 2.0.3                    | CraftTweaker2-1.12-4.1.20.646.jar              | None                                     |
       | LCH   | dungeonmod                        | 1.0                      | Crawler 1.1.4.jar                              | None                                     |
       | LCH   | desirepaths                       | 1.12.1-1.2.8             | desirepaths-1.12.1-1.2.8.jar                   | None                                     |
       | LCH   | diethopper                        | 1.1                      | diethopper-1.1.jar                             | None                                     |
       | LCH   | disenchanter                      | 1.7                      | disenchanter[1.12]1.7.jar                      | None                                     |
       | LCH   | dldungeonsjbg                     | 1.13.2                   | DoomlikeDungeons-1.13.2-MC1.12.2.jar           | None                                     |
       | LCH   | gottschcore                       | 1.14.0                   | GottschCore-mc1.12.2-f14.23.5.2854-v1.14.0.jar | None                                     |
       | LCH   | dungeons2                         | 1.7.5                    | Dungeons2-mc1.12.2-f14.23.5.2768-v1.7.5.jar    | None                                     |
       | LCH   | sereneseasons                     | 1.2.18                   | SereneSeasons-1.12.2-1.2.18-universal.jar      | None                                     |
       | LCH   | orelib                            | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | dsurround                         | 3.6.2.1                  | DynamicSurroundings-1.12.2-3.6.2.1.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | reccomplex                        | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                   | None                                     |
       | LCH   | dynamictrees                      | 1.12.2-0.9.23            | DynamicTrees-1.12.2-0.9.23.jar                 | None                                     |
       | LCH   | dynamictreesbop                   | 1.12.2-1.5.1             | DynamicTreesBOP-1.12.2-1.5.1.jar               | None                                     |
       | LCH   | dynamictreesquark                 | 1.12.2-1.0.6             | DynamicTreesQuark-1.12.2-1.0.6.jar             | None                                     |
       | LCH   | dynamictreesttf                   | 1.12.2-1.2.3             | dynamictreesTheTwilightForest-1.12.2-1.2.3.jar | None                                     |
       | LCH   | dynamictreestconstruct            | 1.12.2-1.2.7             | DynamicTreesTinkersConstruct-1.12.2-1.2.7.jar  | None                                     |
       | LCH   | elevatorid                        | 1.3.14                   | ElevatorMod-1.12.2-1.3.14.jar                  | None                                     |
       | LCH   | enderiobase                       | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                      | None                                     |
       | LCH   | enderioconduits                   | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                      | None                                     |
       | LCH   | enderioconduitsappliedenergistics | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                      | None                                     |
       | LCH   | enderioconduitsopencomputers      | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                      | None                                     |
       | LCH   | enderioconduitsrefinedstorage     | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                      | None                                     |
       | LCH   | enderiointegrationforestry        | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                      | None                                     |
       | LCH   | enderiointegrationticlate         | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                      | None                                     |
       | LCH   | enderioinvpanel                   | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                      | None                                     |
       | LCH   | enderiomachines                   | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                      | None                                     |
       | LCH   | enderiopowertools                 | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                      | None                                     |
       | LCH   | enderstorage                      | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | fastleafdecay                     | v14                      | FastLeafDecay-v14.jar                          | None                                     |
       | LCH   | findme                            | 1.1.0                    | findme-1.12.2-1.1.0-8.jar                      | None                                     |
       | LCH   | forgelin                          | 1.8.4                    | Forgelin-1.8.4.jar                             | None                                     |
       | LCH   | globalxp                          | v1.4.10                  | globalxp-1.12.2-v1.4.10.jar                    | None                                     |
       | LCH   | hardcore_battle_towers_av_av      | 2.0.1                    | Hardcore Battle Towers AV 2.0.1.jar            | None                                     |
       | LCH   | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                    | None                                     |
       | LCH   | improvedbackpacks                 | 1.12.2-1.5.0.0           | ImprovedBackpacks-1.12.2-1.5.0.0.jar           | None                                     |
       | LCH   | initialinventory                  | 2.0.2                    | InitialInventory-3.0.0.jar                     | None                                     |
       | LCH   | inspirations                      | 1.12.2-0.2.9             | Inspirations-1.12.2-0.2.9.jar                  | None                                     |
       | LCH   | inventorytweaks                   | 1.64+dev.151.822d839     | InventoryTweaks-1.64+dev.151.jar               | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCH   | kleeslabs                         | 5.4.12                   | KleeSlabs_1.12.2-5.4.12.jar                    | None                                     |
       | LCH   | labyrinth                         | ${version}               | Labyrinth-1.12.2-1.0.jar                       | None                                     |
       | LCH   | slabmachines                      | 1.0.7                    | Slab_Machines-1.0.7.jar                        | None                                     |
       | LCH   | mcmultipart                       | 2.5.3                    | MCMultiPart-2.5.3.jar                          | None                                     |
       | LCH   | mctsmelteryio                     | 1.2.63                   | MCTSmelteryIO-1.12.2-1.2.63.jar                | None                                     |
       | LCH   | tbone                             | v1.6.8+mc1.12.2          | TBone-v1.6.8+mc1.12.2.jar                      | None                                     |
       | LCH   | metalchests                       | v6.1.0+mc1.12.2          | MetalChests-v6.1.0+mc1.12.2.jar                | None                                     |
       | LCE   | metallurgy                        | 1.3.0-alpha.2            | Metallurgy-4-Reforged-1.3.0-alpha.2.jar        | None                                     |
       | LC    | minicoal                          | 1.0                      | minicoal-1.12.2-1.0.jar                        | None                                     |
       | LC    | mmadd                             | 1.0.0                    | MMDD v0.9.jar                                  | None                                     |
       | LC    | testdummy                         | 1.12                     | MmmMmmMmmMmm-1.12-1.14.jar                     | None                                     |
       | LC    | modernmetals                      | 2.5.0-rc2                | ModernMetals-1.12-2.5.0-rc2.152.jar            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LC    | naturescompass                    | 1.8.5                    | NaturesCompass-1.12.2-1.8.5.jar                | None                                     |
       | LC    | netherportalfix                   | 5.3.17                   | NetherPortalFix_1.12.1-5.3.17.jar              | None                                     |
       | LC    | recipehandler                     | 0.13                     | NoMoreRecipeConflict-0.13(1.12.2).jar          | None                                     |
       | LC    | neid                              | 1.5.4.4                  | NotEnoughIDs-1.5.4.4.jar                       | None                                     |
       | LC    | nuggets_dungeons                  | 1.0.0                    | Nugget's Dungeons v1.2.jar                     | None                                     |
       | LC    | oreexcavation                     | 1.4.150                  | OreExcavation-1.4.150.jar                      | None                                     |
       | LC    | oeintegration                     | 2.3.4                    | oeintegration-2.3.4.jar                        | None                                     |
       | LC    | oreberries                        | 0.5.0                    | oreberries-1.12.x-0.5.0.jar                    | None                                     |
       | LC    | orespawn                          | 3.3.1                    | OreSpawn-1.12-3.3.1.179.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LC    | patchouli                         | 1.0-23.6                 | Patchouli-1.0-23.6.jar                         | None                                     |
       | LC    | pewter                            | 1.4.3                    | Pewter-1.4.3.jar                               | None                                     |
       | LC    | redstoneflux                      | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar        | None                                     |
       | LC    | xreliquary                        | 1.12.2-1.3.4.796         | Reliquary-1.12.2-1.3.4.796.jar                 | None                                     |
       | LC    | roguelike                         | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar             | None                                     |
       | LC    | ruins                             | 17.2                     | Ruins-1.12.2.jar                               | None                                     |
       | LC    | spartanshields                    | 1.5.4                    | SpartanShields-1.12.2-1.5.4.jar                | None                                     |
       | LC    | spartanweaponry                   | beta 1.3.8               | SpartanWeaponry-1.12.2-beta-1.3.8.jar          | None                                     |
       | LC    | spellboundspiretowers             | 1.1.1                    | SpellboundSpireTowers-2.0.0_for_1.12.2.jar     | None                                     |
       | LC    | stg                               | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                           | None                                     |
       | LC    | storagedrawers                    | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar                | None                                     |
       | LC    | structuresplus                    | 1.0.0                    | StructuresPlus.jar                             | None                                     |
       | LC    | tinkersaddons                     | 1.0.7                    | Tinkers' Addons-1.12.1-1.0.7.jar               | None                                     |
       | LC    | tcomplement                       | 1.12.2-0.4.3             | TinkersComplement-1.12.2-0.4.3.jar             | None                                     |
       | LC    | tinkersjei                        | 1.2                      | tinkersjei-1.2.jar                             | None                                     |
       | LC    | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar            | None                                     |
       | LC    | toolbelt                          | 1.9.13                   | ToolBelt-1.12.2-1.9.13.jar                     | None                                     |
       | LC    | torchmaster                       | 1.8.4.84                 | torchmaster_1.12.2-1.8.4.84.jar                | 5e9a436b366831c8f54a7e80b015784da69278c6 |
       | LC    | vanillafix                        | 1.0.10-150               | VanillaFix-1.0.10-150.jar                      | None                                     |
       | LC    | vials                             | 1.2.1.5                  | Vials-MC1.12-1.2.1.5.jar                       | None                                     |
       | LC    | wawla                             | 2.6.275                  | Wawla-1.12.2-2.6.275.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LC    | waystones                         | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                     | None                                     |
       | LC    | weather2                          | 1.12.1-2.6.12            | weather2-1.12.1-2.6.12.jar                     | None                                     |
       | LC    | wrd                               | 0.8.0                    | Wesley's Roguelike Dungeons V0.8.1.jar         | None                                     |
       | LC    | xaeroworldmap                     | 1.14.1                   | XaerosWorldMap_1.14.1_Forge_1.12.jar           | None                                     |
       | LC    | armoryexpansion-conarm            | 2.0.0-alpha              | armoryexpansion-2.0.0-alpha.jar                | None                                     |
       | LC    | tweakersconstructpostload         | 1.12.2-1.6.1             | tweakersconstruct-1.12.2-1.6.1.jar             | None                                     |
  Loaded coremods (and transformers): Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      TransformLoader (DynamicSurroundings-1.12.2-3.6.2.1.jar)
                                        
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      CorePlugin (ForgeEndertech-1.12.2-4.5.5.0-build.0561.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      Plugin (NotEnoughIDs-1.5.4.4.jar)
                                        ru.fewizz.neid.asm.Transformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      XaeroWorldMapPlugin (XaerosWorldMap_1.14.1_Forge_1.12.jar)
                                        xaero.map.core.transformer.ChunkTransformer
                                        xaero.map.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.map.core.transformer.EntityPlayerTransformer
                                        xaero.map.core.transformer.AbstractClientPlayerTransformer
                                        xaero.map.core.transformer.WorldClientTransformer
                                        xaero.map.core.transformer.PlayerListTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
  Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                              * Offline mode for dedicated servers is NOT supported by Ender IO.
                             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
            Authlib is : /home/container/minecraft_server.1.12.2.jar
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - wailaIntegration (Enabled/Not Forced)
                                   - quarkIntegration (Enabled/Not Forced)
  Pulsar/inspirations loaded Pulses: - InspirationsShared (Enabled/Forced)
                                     - InspirationsBuilding (Enabled/Not Forced)
                                     - InspirationsUtility (Enabled/Not Forced)
                                     - InspirationsTools (Enabled/Not Forced)
                                     - InspirationsRecipes (Enabled/Not Forced)
                                     - InspirationsTweaks (Enabled/Not Forced)
                                     - InspirationsShared (Enabled/Forced)
                                     - WailaPlugin (Enabled/Not Forced)
                                     - TwilightForestPlugin (Enabled/Not Forced)
  Pulsar/tcomplement loaded Pulses: - ModuleCommons (Enabled/Forced)
                                    - ModuleMelter (Enabled/Not Forced)
                                    - ModuleArmor (Enabled/Not Forced)
                                    - ModuleSteelworks (Enabled/Not Forced)
                                    - ToolLevelingPlugin (Enabled/Not Forced)
                                    - Oredict (Enabled/Forced)
  Suspected Mods: Metallurgy 4: Reforged (metallurgy)
  Profiler Position: N/A (disabled)
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)
`

**Comment by Breadabix** [comment]
Ive just come across this as well, just the server crashing.

**Comment by Davoleo** [comment]
This should be fixed in `1.3.0-beta.1`, thanks for reporting
