### ISSUE TITLE
Crash with fakeplayer

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [Davoleo/Metallurgy-4-Reforged#336]
On the newly released Beta version, crashes with what looks to me because of the fakeplayer from pneumaticraft:

https://paste.ee/p/s0Va1

here is the crash log

**Comment by Davoleo** [comment]
mmh, this looks like something wrong on Pneumaticcraft's side as the null pointer exception is generated in one of their DroneFakePlayer class methods

I'll see if I can patch it on my side anyways since it looks like pneumaticcraft is not getting updates for 1.12.2 since 2019

**Comment by ErnestoPeroPezzi** [comment]
Hey, thanks for patching it, much appreciated. Will check back if any other issues persist

**Comment by Davoleo** [comment]
just a reminder that the patch has not been released yet as I'm still waiting to pile up some more changes
