### ISSUE TITLE
Tinkers' Construct material will not show its localized name

### ISSUE THREAD

**Issue by DSLM** [Davoleo/Metallurgy-4-Reforged#342]
There is the screenshot of those material in Chinese language:
![image](https://user-images.githubusercontent.com/12635058/142234310-5ea8f5e9-052b-45c2-a26e-3dad4183a6c3.png)
They were translated: https://github.com/Davoleo/Metallurgy-4-Reforged/blob/master/src/main/resources/assets/metallurgy/lang/zh_cn.lang#L2-L40

For the original materials Pigiron and Knightslime, it show correctly:
![image](https://user-images.githubusercontent.com/12635058/142234402-9c3febec-1318-4890-8d06-b184c56e941d.png)

I guesses it caused by those code, which only read "material.%s.name" rather than "material.metallurgy.%s.name":
https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/library/materials/Material.java#L40-L41
https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/library/materials/Material.java#L434-L450

Maybe you can override getLocalizedName function?

**Comment by Davoleo** [comment]
Should be fixed now, a really old method was manipulating the registry names to hardcode them in the book.
![fixed](https://cdn.discordapp.com/attachments/531161173694087188/911671146238312458/unknown.png)
I've also added 2 new material name translations (Alduorite and Infuscolium) that were missing before, if you want to add those translations I'll gladly accept them (you can read the commit that closed this issue for information on the translation keys)
