### ISSUE TITLE
Would Life Steal heal player to max heath?

### ISSUE THREAD

**Issue by DSLM** [Davoleo/Metallurgy-4-Reforged#344]
https://github.com/Davoleo/Metallurgy-4-Reforged/blob/master/src/main/java/it/hurts/metallurgy_reforged/integration/tic/trait/MetallurgyTraitLifeSteal.java#L44-L50
It looks like do nothing if it can heal to max.

**Comment by DSLM** [comment]
Also, is it heal 15%?
https://github.com/Davoleo/Metallurgy-4-Reforged/blob/master/src/main/resources/assets/metallurgy/lang/en_us.lang#L1164

**Comment by Davoleo** [comment]
Changes:
- healed amount: 15% -> 40%
- chance: 20% + 20% * Luck Level
- Rewrote old terrible code that didn't allow for the player to be healed to max health
- Changed Tooltip description so it matches the new healed amount
