### ISSUE TITLE
[1.12.2] Dissolve Armor Set Effect oddity?

### ISSUE THREAD

**Issue by Z-Tunic** [Davoleo/Metallurgy-4-Reforged#346]
Minecraft: 1.12.2
Forge: 14.23.5.2860

Mods: 3
jei_1.12.2-4.16.1.302
Metallurgy-4-Reforged-1.3.0
overloadedarmorbar-1.0.4g

=====

It seems that the Armor Bonus from the Dissolve set effect is a bit iffy as when you have one potion effect active, your armor bar doesn't show the updated armor... however when I get another potion effect... my armor bar does update by about 2 points.

Full Set of Vyroxeres Armor gives you a total of 18 Armor. With 1 effect... it's still 18, with 2 effects, it became 20. With 3 effects it became 22.

If I drink a bucket of milk to clear my potion effects... my armor bar is at 20 and upon removing the Vyroxeres Armor Set... I apparently have 2 Armor even though I'm not wearing anything that gives me Armor.

Overloaded Armor Bar was used as it allows you to see your Armor Bar go above 20.

P.S.
Is there a cap of how many Potion Effects you can have in order to get Bonus Armor?

**Comment by Davoleo** [comment]
fixed in https://github.com/Davoleo/Metallurgy-4-Reforged/commit/52049fe019984baac7548a827e9e2e0c4f55eeca
