### ISSUE TITLE
[question/suggestion] option for disabling ore worldgen

### ISSUE THREAD

**Issue by Biviho** [Davoleo/Metallurgy-4-Reforged#351]
hi, i was browsing the config in search of a way to directly disable the worldgen of specific ore, but i noticed that there isn't one.

the only option i have found are rarity (wich have a min of 1, so no remove i suppose?) and the biome option, wich seems to behave like a "specific biome vs all biome" kind of thing, right?

is there a way with those option to disable ore worldgen?

if not, i wanted to suggest to add it, to give more freedom to modpack dev to tweak the pack

**Comment by Davoleo** [comment]
You can set the veinSize Parameter to 0, and the ore won't be generated anymore.
For example with this kind of configuration Astral silver shoulnd't generate in the world anymore:
![image](https://user-images.githubusercontent.com/24458276/154798341-c5052a70-57e3-40b8-8d0b-83e321f4f6cb.png)
