### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kasia1403** [Davoleo/Metallurgy-4-Reforged#358]
https://paste.ee/p/2iXcs

**Comment by Davoleo** [comment]
Duplicate of #357
this will be fixed in the next patch release that I'll release soon

**Comment by Kasia1403** [comment]
When will be this bugfix release ? I just can't wait !

**Comment by Kasia1403** [comment]
It also happens when I hit iron golem.

**Comment by Kasia1403** [comment]
Oh no, after downgrading to lower wersion this crash ( this time with Silent's Gems ) appears :

https://paste.ee/p/jhnyL

**Comment by Davoleo** [comment]
> When will be this bugfix release ? I just can't wait !

@Kasia1403 
Please be patient, I also have life and uni matters I should attend, I'll try to release a patch as soon as I can
