### ISSUE TITLE
Metamorphosis doesn't work on haderoth tools

### ISSUE THREAD

**Issue by KreloX** [Davoleo/Metallurgy-4-Reforged#361]
Describe the bug:
Haderoth tools just break instead of triggering the metamorphosis effect. Affects all tools but doesn't affect armor.

To Reproduce:
1. Launch a singleplayer world
2. Spawn some mobs to destroy the tools on
3. See the issue

Versions:
- Metallurgy: 1.3.3
- Forge: 14.23.5.2859
- Minecraft: 1.12.2

**Comment by Klazkin** [comment]
Haderoth and not tartarite? Weird

**Comment by Davoleo** [comment]
Pretty strange, I've been able to reproduce this issue while using the sword but all other tools seem to work fine
