### ISSUE TITLE
Inolashite's Time Cleave triggers on every hit

### ISSUE THREAD

**Issue by KreloX** [Davoleo/Metallurgy-4-Reforged#362]
Describe the bug:
Inolashite sword's Time Cleave ability triggers on every hit, even though the effect's description says it should only work sometimes.

To Reproduce:
1. Luanch creative singleplayer
2. Spawn some mobs
3. Attack them with an Inolashite Sword

Versions:
- Metallurgy: 1.3.3
- Forge: 14.23.5.2859
- Minecraft: 1.12.2

**Comment by Davoleo** [comment]
Fixed in https://github.com/Davoleo/Metallurgy-4-Reforged/commit/22d285438022a7abce755020d3e0cf3415895a40
