### ISSUE TITLE
Shields' abilities are annoying after eating

### ISSUE THREAD

**Issue by KreloX** [Davoleo/Metallurgy-4-Reforged#363]
This mainly applies to ceruclase shield but it could be done with the others too. The shields which have abilities should only trigger if the item in other hand isn't a food item.

When the player eats with shield in offhand the ability always activates when the player is satiated. This can be annoying in certain situations, mainly when playing multiplayer.

**Comment by Davoleo** [comment]
With this commit if you have something you can eat/drink in the opposite hand the shield will not be placed in world, that will not be the case if you empty/finish the stack of food/drinks, in that case the shield will still spawn and it's a fairly more complicated case to detect so, for the moment I decided to go for a simple fix, if it's still as annoying as before feel free to comment here below

[I'll be releasing a new patch soon]
