### ISSUE TITLE
[1.12.2] Aerodynamic via a Paragon Absorb doesn't seem to apply the speed boost.

### ISSUE THREAD

**Issue by Z-Tunic** [Davoleo/Metallurgy-4-Reforged#365]
Minecraft: 1.12.2
Forge: 14.23.5.2860

Mods: 2
HadEnoughItems_1.12.2-4.21.1
Metallurgy-4-Reforged-1.3.4

---

![2022-08-07 21-56-32](https://user-images.githubusercontent.com/36653806/183329629-15f719f5-1824-4ea0-b067-27bfb7dd761a.gif)

Aerodynamic from Quicksilver supposedly applies a speed boost when you hold the tool in your hand, however it seems that it doesn't apply if you have it on a Tartarite Tool/Sword... unless, maybe the ability is due to the speed attribute that the Quicksilver materials have which isn't being transferred over via Paragon Absorb?

Speaking of attributes, some of them don't transfer over when you Paragon Absorb their metals, such as Sangunite's +2 Max health which the tools normally have.

**Comment by Davoleo** [comment]
Fixed in: https://github.com/Davoleo/Metallurgy-4-Reforged/commit/886643462501e94bd33024c444bfe2d72393b0ea
