### ISSUE TITLE
Conarm Haderoth Armor unfixable

### ISSUE THREAD

**Issue by Honezt** [Davoleo/Metallurgy-4-Reforged#367]
### General Information

**Describe the bug:**

Construct armoury haderoth gear does not repair with the armour forge
**To Reproduce:**

1. wear haderoth gear (tinkers armoury version). you can obtain it in the creative tab.
2. get the gear damaged until it is broken
3. Use the armour forge and use the haderoth ingots to fix it
4. Expected: Fixed Armor  | Reality: Armor no fix

***

### Environment Versions

**Versions:**

- Metallurgy:1.3.4
- Conflicting mod (if regarding mod integration):  Construct's armoury: 1.2.5.10
- Other mods you think could cause issues: 
- Forge: 14.23.5.2860
- Minecraft: 1.12.2
- Modpack (if available): Custom

***

**Comment by Davoleo** [comment]
This is probably related to #282 and this means it wasn't actually fixed, I'll investigate more
