### ISSUE TITLE
Metallurgy 4 Quicksilver crashing

### ISSUE THREAD

**Issue by Desenrrollado** [Davoleo/Metallurgy-4-Reforged#369]
### General Information

**Describe the bug:**
Simply put the game crashes when you shoot a zombie wearing quicksilver armor with just a normal bow and arrow..

**To Reproduce:**
1. Use a normal bow with normal arrows.
2. Fire at a naturally generated zombie wearing quick silver armor.
3. Infinite crashing...
***

### Environment Versions
**Versions:**
- Metallurgy-4-Reforged-1.3.5
- Forge: 14.23.5.2860
- Minecraft: 1.12.2
- Modpack (if available): Custom made by me.

***

### Logging Information

**Crash Report 
[crash-2022-11-16_11.03.03-server.txt](https://github.com/Davoleo/Metallurgy-4-Reforged/files/10024624/crash-2022-11-16_11.03.03-server.txt)

**Latest Log 
[latest.log](https://github.com/Davoleo/Metallurgy-4-Reforged/files/10024623/latest.log)

**Addition Info:
I have no idea. I know I can probably stop the crashing if I uninstall Metallurgy most likely. Though I'm wondering if anything else is causing this. If it's an isolated incident or if it's one of the many mods I have included.

**Comment by Dove-Bren** [comment]
This hit our modpack today, too.

Issue seems to be the QuickSilver's **cancelLavaDamage** method doesn't null check the _EffectDataProvider.PLAYER_EFFECT_DATA_CAPABILITY_ before trying to use it like the other quicksilver effects do.

**Comment by Davoleo** [comment]
That is definitely the case, thanks for reporting, I'll be pushing a patch soon
