### ISSUE TITLE
Sanguinite Doesn't Respect Biome Configuration

### ISSUE THREAD

**Issue by puncrafter** [Davoleo/Metallurgy-4-Reforged#373]
### General Information

**Describe the bug:**
Sanguinite does not respect the config option that dictates which biome it spawns in. Every single other Nether ore respects this config option.

**To Reproduce:**

1. Install Metallurgy 4 and a mod that adds biomes to the nether. (I am using NetherEX)
2. Configure Sanguinite to only spawn in one specific biome (I chose `netherex:fungi_forest`)
3. Fly around and notice that Sanguinite spawns in other biomes.

***

### Environment Versions

**Versions:**

- Metallurgy: 1.3.6
- Conflicting mod (if regarding mod integration): NetherEX 2.2.5
- Forge: 14.23.5.2860
- Minecraft: 1.12.2

***

### Logging Information

**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some
other log sharing service**

**Crash Report (if available):** It doesn't crash

**Latest Log (if necessary):** I am pretty sure the log is unnecessary, I crtl-f'ed it for Sanguinite and found nothing.

***

### Additional Information

**Screenshots (if available):** Sanguinite as seen in the Ruthless Sands biome, which is not the one I configured it to spawn in. 
![2023-02-21_14 15 05](https://user-images.githubusercontent.com/53954921/220438053-28e20d99-404e-409d-84ca-24a52f2cab57.png)

**Additional context (optional):** Nothing I can think of.

**Comment by Davoleo** [comment]
I was able to find the cause of this issue in code, I'll change it so that biome filters actually work, just know that the rarity modifiers related to the [sanguinite's special oregen](https://github.com/Davoleo/Metallurgy-4-Reforged/wiki/Ores#special-ore-generation) will still apply: so it will spawn with rare rarity unless near a nether fortress structure.
