### ISSUE TITLE
Manganese Ore unobtainable with Diamond pickaxe

### ISSUE THREAD

**Issue by Jmbkpo** [Davoleo/Metallurgy-4-Reforged#49]
I was mining a Manganese ore and i cannot destroy it with a Diamond pickaxe (harvest level 4) but with a Damascus Steel (harvest level 4) i can

![2018-11-26_21 01 55](https://user-images.githubusercontent.com/45374820/49049708-f0277c80-f1be-11e8-9654-b43ad6a84385.png)
![2018-11-26_21 01 58](https://user-images.githubusercontent.com/45374820/49049709-f0277c80-f1be-11e8-9ed0-915117da0ac1.png)
![2018-11-26_21 02 00](https://user-images.githubusercontent.com/45374820/49049710-f0c01300-f1be-11e8-94eb-1a3322c1d9ba.png)
![2018-11-26_21 02 03](https://user-images.githubusercontent.com/45374820/49049711-f0c01300-f1be-11e8-9c3c-f02b97911e65.png)

**Comment by HurtsAsHell** [comment]
We fixed the manganese harvest level, it's now set to 3 (equals to Obsidian harvest level) [harvestable by a diamond pickaxe]
