### ISSUE TITLE
Typo in Wiki

### ISSUE THREAD

**Issue by Jmbkpo** [Davoleo/Metallurgy-4-Reforged#51]
In Harvest Level of Metals Block and Ores Block, there are typos in

Ore Harvestability: 
1. "Zinco Ore"

4. "Rubracacium Ore"

**Comment by Collecter128** [comment]
There is also a typo in “Alloyer recipes” where bronze needs bronze to make

**Comment by HurtsAsHell** [comment]
Resolved typo, for now :triumph:
