### ISSUE TITLE
Unable to climb stairs or slabs

### ISSUE THREAD

**Issue by Jmbkpo** [Davoleo/Metallurgy-4-Reforged#52]
I go directy to a staircase or slab, running or walking, and i can't "use it", the hitbox is like always, but the character would not "climb" it                       (maybe it is related to the Sneaking bug?)
![2018-11-27_07 33 59](https://user-images.githubusercontent.com/45374820/49076339-84253280-f217-11e8-9909-775999279f71.png)
![2018-11-27_07 34 29](https://user-images.githubusercontent.com/45374820/49076340-84bdc900-f217-11e8-931c-1dd629883934.png)
![2018-11-27_07 36 06](https://user-images.githubusercontent.com/45374820/49076341-84bdc900-f217-11e8-9373-11af9e9265f8.png)
![2018-11-27_07 37 03](https://user-images.githubusercontent.com/45374820/49076342-84bdc900-f217-11e8-81ae-75632a5d42f0.png)
![2018-11-27_07 37 05](https://user-images.githubusercontent.com/45374820/49076343-84bdc900-f217-11e8-830e-358d803eff8a.png)
(I'm going forward but i'm only sliding to the right)

**Comment by PierKnight100** [comment]
this bugs are already fixed,the cause is the stepHeight,that is the method to set height that a player can climb
@Jmbkpo

**Comment by Jmbkpo** [comment]
Ok thanks Pier
