### ISSUE TITLE
Deep Iron Sword effect 

### ISSUE THREAD

**Issue by Jmbkpo** [Davoleo/Metallurgy-4-Reforged#53]
The Deep Iron Sword would be especially good for mining because you go deep into the caves and you got extra damage for the mobs you could find there, it would work like detecting the actual layer or place (like that thing that triggers the cave sounds).

**Comment by Davoleo** [comment]
_could be integrated with some other effect on the deep iron pickaxe_
for instance the pick being able to mine at regular speed underwater

[could even be nerfed by some side-effects, faster hunger increase, higher durability damage]

**Comment by Jmbkpo** [comment]
If Deep Iron is gonna have handicap, i think the others sets would need to. for example the Adamantine armor has a very powerful effect (Well fed) and you can't nerf "Well fed" so a side-effect would be nice for balancing that

**Comment by Davoleo** [comment]
I agree with the fact that Adamantine armor is really OP
I felt that when I was testing the first alpha...

However yes, indeed some tools/armors would need some side effects, but some others don't really [example: midasium sword]

**Comment by Jmbkpo** [comment]
Yes, i don't believe that everything deserves a handicap

**Comment by Jmbkpo** [comment]
I'm feeling that Black Steel deserves more the effect, making it more worthy the alloy, plus Deep Iron alone is easy to find.
