### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by TheCastes** [Davoleo/Metallurgy-4-Reforged#57]
When I start the game minecraft loads for a second and just crashes giving me the error "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail".
Here is the   ##Crashlog
[crash-2018-11-28_21.06.24-client.txt](https://github.com/Davoleo/Metallurgy-4-Reforged/files/2626421/crash-2018-11-28_21.06.24-client.txt)

**Comment by Davoleo** [comment]
Could you please list the steps needed to reproduce this bug?

**Comment by TheCastes** [comment]
- put the mod in the mods folder

- Open the launcher

- start the game with forge

- game crashes

**Comment by Davoleo** [comment]
are there other mods you're playing with, other than Metallurgy?

**Comment by TheCastes** [comment]
no

**Comment by TheCastes** [comment]
also, if you click on more details after the crash it gives you this "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Metallurgy 4: Reforged (m5)"

**Comment by Davoleo** [comment]
![image](https://user-images.githubusercontent.com/24458276/49179873-8ee4e200-f353-11e8-8fdb-ace1554ae688.png)
I'm unable to reproduce it, both on default Minecraft launcher and in my modding environment 🤔 :hyperthonk:

you sure that your launcher is ok and not corrupt right?

Also pinging @HurtsAsHell in case he finds out about it

Anyways the crash log says that forge doesn't find the method that registers tile entities, making the whole game to crash

**Comment by TheCastes** [comment]
I tried running another mod with the same version and is fine, i don't honestly know why metallurgy is not working

**Comment by Klazkin** [comment]
Could be the version of forge or java. Also, try cleaning your configs folder.

**Comment by TheCastes** [comment]
I'll try

**Comment by Ikarsu** [comment]
clean out configs, and change your forge to at least 27xx to keep this mod stable. 26xx forge will crash.

**Comment by TheCastes** [comment]
sure

**Comment by Davoleo** [comment]
now that I think about it, it's probably going to be forge version 🤔 
because if it didn't find a method, probably it's been renamed after some of the latest versions

Not 100% sure though

**Comment by Klazkin** [comment]
@Davoleo If it ends up being the case, can you add a forge version dependency after this?

**Comment by Ikarsu** [comment]
I done tests and 26xx and below forge will crash when attempting to load this mod. It needs 27xx+ to load properly. Thank you for your patience.

**Comment by Davoleo** [comment]
yeah, I'll do it, I actually think there's already one, but it may be not enough

**Comment by TheCastes** [comment]
yes it was the version, version 27xx only supported i guess...

**Comment by Davoleo** [comment]
really confused now
https://github.com/Davoleo/Metallurgy-4-Reforged/blob/5e66200cccb881722db0af867b52cf141569ac33/src/main/java/it/hurts/metallurgy_reforged/Metallurgy.java#L29

**Comment by Ikarsu** [comment]
[https://imgur.com/a/9yAFtu0](url)

to help clear up confusion. 2700 can run metallurgy... but any other mods installed will require proper updates to forge 27xx. 

Metallurgy does not have any known dependencies, which the line after the = can be completely disregarded.

**Comment by Davoleo** [comment]
the issue here is that, even if they have an older version of forge the forge dependency on the line I highlighted there doesn't stop the client from loading, and that makes it crash
