### ISSUE TITLE
Various Effect Ideas

### ISSUE THREAD

**Issue by PierKnight100** [Davoleo/Metallurgy-4-Reforged#58]
Ideas for new effects are listed here (obviously these ideas can be changed):

1. **-Carmot Armor Effect:** Adds break block speed without haste effect and makes player actions (like eating,drinking,bow usage) much faster,but everytime the player makes one of these actions he will lose hunger

2. **-Cenelegil Armor Effect:** Player Absorbs damage by using xp(example:1 Heart for  0,2 of XP) 

3. **-New Armor Effect (Neutrion):** The player will not be affected by potion effects.(applied to good and bad potion effects)

4. **-Sanguinite Armor Effect:** Damage resistance against living mobs(not undead mobs)

**Comment by HurtsAsHell** [comment]
Shadow Iron Armor Effect: increase in attack speed based on light (light = 0, Attack speed = 0.12 for example)

**Comment by HurtsAsHell** [comment]
Deep Iron Pickaxe digs faster in water

**Comment by Jmbkpo** [comment]
Quicksilver Sword gives weakness to the mobs

**Comment by Luke616** [comment]
HELP I accidentally spent way too long writing weapon/armor ideas. Much of this was adapted from design notes I made back when I was putting together a pack with metallurgy and wanted to give weapons/armor custom bonuses using mods. I think you've already incorporated some of these, but here are more ideas for weapon/tool effects and armor-set bonuses for nether metals. Use them if you think they sound cool:

**Base Metals**
- Steel
    - Sword: 25% armor piercing effect
    - Armor: increased knockback resistance

**Precious Metals**
- Silver
   - Sword: increased damage vs. undead mobs
   - Armor: undead mobs take thorns damage
   - Both: take less damage from undead mobs

**Nether Metals**
- Ignatius
   - Sword: chance to inflict burn on hit
   - Armor: low-level fire resistance (similar to vanilla enchantment - not true fire immunity like potion)
       - TAN mod integration - grants low-level cold resistance
   - Both: chance to burn increased
- Shadow Iron
   - Sword: chance to inflict blindness on hit
   - Armor: grants blindness immunity
   - Both: chances are increased
- Shadow Steel
   - Sword: increased attack speed based on light (darker is better)
   - Armor: grants blindness immunity, increased toughness based on light
   - Tools: increased mining speed based on light
   - Both: increased attack damage based on light
- Midasium
   - Sword: enemies sometimes drop gold nuggets when killed
   - Armor: grants an increase in luck
   - Tools: ores sometimes drop gold nuggets when broken
   - Both: higher chance to drop nuggets
- Ceruclase
   - Sword: chance to inflict slowness on hit
   - Armor: chance to inflict slowness on attackers when hit
       - TAN mod integration - grants heat resistance
   - Both: inflicts slowness II
- Vyroxeres
   -  Sword: chance to inflict poison on hit
   -  Armor: chance to inflict poison on attackers when hit
   -  Both: inflicts poison II
- Inolashite
   - Sword: chance to inflict poison or slowness on hit
   - Armor: grants poison immunity
       - alternatively/additionally, slowness immunity?
   - Both: chances are increased
- Kalendrite
   - Sword: chance to recover health on hit
   - Armor: small chance to gain regeneration when hit
   - Both: chances are increased
- Amordrine
   - Sword: heals for a flat 25% of damage dealt
   - Armor: small chance to be saved from death (like: angelheart vial from reliquary)
   - Both: heals for 50% of damage dealt
- Vulcanite
   - Sword: chance to burn on hit
   - Armor: high chance to inflict burn on attackers when hit, fire immunity (but not lava) 
       - TAN mod integration - grants high-level cold resistance
   - Tools: automatically smelts anything mined
   - Both: chances are increased
- Sanguinite
   - Sword: chance to inflict wither on hit
   - Armor: grants immunity to wither
   - Both: inflicts wither II

**Fantasy Metals**
- Prometheum
   - Sword: increased damage based on durability (less is better)
   - Armor: increased toughness based on durability
   - Tools: increased mining speed based on durability
   - Both: chance not to consume durability
- Deep Iron
   - Sword: inflicts higher damage against aquatic mobs (squid, guardians, 1.13 new mobs)
   - Armor: breath drains much slower in water
   - Tools: mines in water at normal speed
   - Both: faster movement speed in water
- Black Steel
   - Sword: increased swing speed based on world height (deeper is better)
   - Armor: increased toughness based on world height
   - Tools: increased mining speed based on world height
   - Both: increased attack damage based on world height
- Oureclase
   - Sword: build-in knockback I
   - Armor: built-in haste I
   - Tools: mine stone much faster
   - Both: built-in knockback II
- Astral Silver
   - Sword: chance for any hit to deal critical damage
   - Armor: chance for ranged attacks to reflect back at attackers
       - alternatively: increased damage for ranged attacks
   - Both: critical hits deal more damage
- Carmot
   - Sword: built-in looting I
   - Armor: grants a bonus to luck
   - Tools: built-in fortune I
   - Both: built-in fortune/looting II
- Quicksilver
   - Sword: inflicts weakness on mobs
   - Armor: increased movement speed
   - Both: increased weapon swing speed
- Mithril
   - Sword: inflicts its damage as magic damage
   - Armor: magic deals more damage
   - Both: increased magic damage
- Haderoth
   - Sword: inflicts increased damage vs. magic users (witches, evokers, vexes?)
   - Armor: take less damage from magic sources (magic shielding)
   - Both: take even less damage from magic sources
- Orichalcum
   - Sword: gain strength I for 7 sec on kills
   - Armor: increased melee weapon damage & knockback
   - Both: strength effect lasts longer
- Celenegil
   - Sword: gain speed I for 7 sec on kills
   - Armor: increased ranged weapon damage & knockback
   - Both: gains speed II on kills
- Adamantium
   - Sword: 50% armor-piercing effect
   - Armor: full knockback immunity, bonus to armor toughness
   - Both: 75% armor-piercing
- Atlarus
   - Sword: built-in smite III, lights undead on fire
   - Armor: undead attackers are lit on fire and take thorns damage
   - Both: further increased damage vs. undead
- Tartarite
   - Sword: gain strength for 12 sec on kills
   - Armor: chance to gain resistance for 7 sec when hit
   - Both: bonuses are strength II and resistance II

**End Metals**
- Eximite
    - Sword: deals increased damage vs. end mobs (endermen, dragon, shulkers)
    - Helmet: endermen are not aggressive when looked at (like pumpkin)
    - Armor Set: grants night vision
    - Both: further increased damage vs. end mobs
- Desichalkos
    - Sword: chance to inflict a random negative effect on hit
    - Helmet: endermen are not aggressive when looked at
    - Armor Set: chance to teleport melee attackers a short distance away
    - Both: random effect chance increased

**Comment by Jmbkpo** [comment]
@Luke616 now that's what i'm talking about! i like the Thorns suggestion, i didn't thought about that

**Comment by Luke616** [comment]
@Pierknight100 yep, that's exactly what I meant! Not sure if that's an idea you guys would like to pursue or not, thought it might be neat.

**Comment by PierKnight100** [comment]
do you like the idea that if it's near light the shadow steel armor lose resistance? @Luke616

**Comment by Luke616** [comment]
@PierKnight1000 Personally no, I'd rather it just be bonuses since I wouldn't want the player to feel like that armor set might be a liability in the wrong conditions

**Comment by Karanime** [comment]
A handful of these already have TiC entries via either Moar Tinkers or PlusTiC, so it might be a good idea to have the abilities match what they would be if they were in a Tinker tool or a Construct armor set. I've seen steel, silver, quicksilver, and mithril. I do like the idea of having bonuses for full armor + sword of the same material, especially because it gives a reason to NOT go the Tinkers route. I like varied strategic choices like that.

Are you guys planning on using a lot of the same abilities the metals had in previous versions of the mod?

**Comment by Davoleo** [comment]
We added some effects from the old versions, but we don't plan on founding everything on the original effects since we're trying to make the mod as unique as possible

Remember that here we're discussing about effects from classic armor and tools not about traits from TCon, but yeah, the more original the effects are the more unique the mod becomes

**Comment by HurtsAsHell** [comment]
@Luke616 Thanks for your help, we have added some of your effects to mod. We will improve them later, now we are concentrating on tinker.

Happy New Year
