### ISSUE TITLE
(Suggestion) (Bug?) Unable to find Silver ore

### ISSUE THREAD

**Issue by Jmbkpo** [Davoleo/Metallurgy-4-Reforged#60]
So i had been exploring a lot at different layers and it was impossible to find some silver for the Crusher recipe, i found Copper very easily of course, Oureclase with quite easiness too but silver was impossible. Is Silver ore very rare or it doesn't spawn?

**Comment by Jmbkpo** [comment]
I had this problem since the first version, and i generated new chunks with the 0.0.2 version

**Comment by HurtsAsHell** [comment]
It was a bug, as soon as possible we will release the version with the fix
