### ISSUE TITLE
(Suggestion) Buff blast resistance of ores

### ISSUE THREAD

**Issue by Jmbkpo** [Davoleo/Metallurgy-4-Reforged#62]
Playing around the caves i discover that a Creeper explosion could break and drop some high tier minerals, so i decide to experiment and recreate that with TNTs. Is not very hard, you only have to learn the blast resistance of the different ores and you could get around a 50% chance of dropping it with a explosion, i feel this is very OP because you can skip tiers with simple TNT, maybe some will say "that's like a twisted idea, it its rare that someone will think about that and take advantage" but i believe that wouldn't a weird idea because of the Utility ores, that would encourage people to make use of the ores and make Gunpowder, so they could make TNT and try that, even if this is a very rare trick i think the cheap way of making TNT will make it real

This is me testing this cheat
![2018-12-02_05 01 36](https://user-images.githubusercontent.com/45374820/49338114-90850300-f5fc-11e8-8358-6b959abba36b.png)
![2018-12-02_05 01 45](https://user-images.githubusercontent.com/45374820/49338115-90850300-f5fc-11e8-9442-71620e0efe6d.png)
![2018-12-02_05 12 54](https://user-images.githubusercontent.com/45374820/49338116-911d9980-f5fc-11e8-8778-e8be65a3d1f8.png)

(Carmot pickaxe gotten without a enough tier to pick it, along with Adamantine and Orichalcum)
![2018-12-02_05 12 57](https://user-images.githubusercontent.com/45374820/49338117-911d9980-f5fc-11e8-9051-2572f343c6e0.png)

(Smelting Astral Silver that i got with only TNTs)
![2018-12-02_05 13 03](https://user-images.githubusercontent.com/45374820/49338118-911d9980-f5fc-11e8-8cf7-14e8c8bde954.png)

(The high tier ores i got)
![2018-12-02_06 40 58](https://user-images.githubusercontent.com/45374820/49338236-9b8c6300-f5fd-11e8-8fdd-c94108bad35f.png)

**Comment by HurtsAsHell** [comment]
oh, you're right, we'll solve it right away. Thanks
