### ISSUE TITLE
(Bug)(v0.0.2) Typo Astral Silver in-game

### ISSUE THREAD

**Issue by Jmbkpo** [Davoleo/Metallurgy-4-Reforged#63]
![2018-12-02_06 46 18](https://user-images.githubusercontent.com/45374820/49338293-2f5e2f00-f5fe-11e8-9fa2-3c638e010607.png)
![2018-12-02_06 46 21](https://user-images.githubusercontent.com/45374820/49338295-2ff6c580-f5fe-11e8-82bc-2855dc0dec30.png)
![2018-12-02_06 46 31](https://user-images.githubusercontent.com/45374820/49338296-2ff6c580-f5fe-11e8-818c-de228012ecfc.png)

**Comment by HurtsAsHell** [comment]
I hate myself

**Comment by Ikarsu** [comment]
the text within the armor pieces needs the full set to be active.

**Comment by Davoleo** [comment]
huh?

**Comment by HurtsAsHell** [comment]
Sorry

**Comment by Davoleo** [comment]
I mean, what does it have to do with this issue? 😅 @Ikarsu
