### ISSUE TITLE
XML config detect name for Metallurgy 4: Reforged

### ISSUE THREAD

**Issue by Remuron** [Davoleo/Metallurgy-4-Reforged#69]
Hello this is double post from Customoregen (COG) mod hope you can help with it. https://github.com/lawremi/CustomOreGen/issues/222

Basically i need name of Metallurgy 4: Reforged for COG which game uses when it loads Metallurgy 4: Reforged so other mods can spot it by this name. For metallurgy4 it was metallurgy but it does not work.
I dont know if i explained it right. Hope you understand.

**Comment by Davoleo** [comment]
you mean the Mod ID?

**Comment by Remuron** [comment]
Maybe of its in a form similar of "metallurgy" name.

**Comment by HurtsAsHell** [comment]
you mean the Mod ID?

**Comment by Davoleo** [comment]
do you need the string you put in the game to give yourself items of that mod? @Remuron

**Comment by Remuron** [comment]
No not at all.
It works this way. COG has xml config files for each mod that adds some ores. So for example simple ores are separated from metallurgy because you have 2 separated xml config files. COG checks on MC startup if the mod is loaded. In these xml files you have defined the name thats is shown for players and in menu. Than there is other name thats used to detect if the mod is present in game. If it is present COG loads the corespondenting config xml file and starts to handle ore generation for corespondenting mod eg. metalurgy in this case.
And problem here is that it does not detect metallurgy 4: reforged because the second name has changed and i dont know what to or where to look for it.

**Comment by Davoleo** [comment]
well, the `name` you mean probably isn't there at all, since this mod is completely rewritten, and the original's last version is for 1.7.10

I'll keep this issue open until we sort it out, by the way this is an issue on their side, so can't do anything more than asking what string you need

**Comment by HurtsAsHell** [comment]
Our mod to work needs to create an xml (and I think you know), so you should create a kind of integration between the two mods. I can tell you the possible names of the mod (since I have not yet understood what you're looking for).

NAME = "Metallurgy 4: Reforged"
MODID = "m5"

You need tests and let us know if it works

**Comment by Davoleo** [comment]
It's the modid they need, check issue 222 @HurtsAsHell

**Comment by Remuron** [comment]
Hell yeah guys! It works! Thank you very much.
