### ISSUE TITLE
JEI sword bug - Negative Attack Speed

### ISSUE THREAD

**Issue by HurtsAsHell** [Davoleo/Metallurgy-4-Reforged#72]
Visual glitch where all of the swords will show up as having -2.4 attack speed in JEI

By **ThatOneMediaGuy**

**Comment by Davoleo** [comment]
ok this is a vanilla bug, but Mojang doesn't seem to consider it a bug, so LexManos from the forge team decided to keep it as it is

Pull Request Reference: https://github.com/MinecraftForge/MinecraftForge/pull/5244

Closing this issue
