### ISSUE TITLE
Request - Tinkers Support

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Davoleo/Metallurgy-4-Reforged#73]
I love this mod but in this day and age to fit with most packs private or otherwise, it is a staple to add support for Conarm and Tinkers Construct.

**Comment by HurtsAsHell** [comment]
I'm glad you like the mod and that you're supporting us ... but look at the [beta release checklist](https://github.com/Davoleo/Metallurgy-4-Reforged/issues/47). 

Unfortunately for us we are not bot then, give us some time, one thing at a time.

**Comment by P3rf3ctXZer0** [comment]
Everything takes time - I can wait I just thought you may want to raise that is a semi-important objective. Its interesting who would of thought tinkerers construct could be so popular.
