### ISSUE TITLE
New tool forging system

### ISSUE THREAD

**Issue by kuroyure** [Davoleo/Metallurgy-4-Reforged#74]
I suggest casting the metal partels of a Tool in their shape then using leather to cover the handle, also a grindstone to sharpen swords so they Deal more dammage but lose durability

**Comment by Karanime** [comment]
I love that grindstone idea. I think casting ought to be handled by Tinkers.

**Comment by Davoleo** [comment]
A new metal processing system is going to be introduced with 1.14, closing this issue
