### ISSUE TITLE
2 ore = 2 dust (JEI BUG)

### ISSUE THREAD

**Issue by HurtsAsHell** [Davoleo/Metallurgy-4-Reforged#75]
In the new version of the mod in jei the recipes will be seen as 2 ore = 2 dust, in reality it is equal to 1 ore = 2 dust.

**Comment by Davoleo** [comment]
fixed in https://github.com/Davoleo/Metallurgy-4-Reforged/commit/51c363a15734b306f486982a691277473182d968
