### ISSUE TITLE
TiC Integration: Electrum Effect

### ISSUE THREAD

**Issue by Klazkin** [Davoleo/Metallurgy-4-Reforged#78]
Electrum - 
**Natural Flux Capacitor** - Replaces tools durability with RF Flux. 
This means that tools that have this trait can be recharged using RF Flux or other compatible energy sources from industrial themed mods. There used to be a modifier in older versions of TiC that did this, now that it's gone this might be a good opportunity to bring it back

**Comment by Davoleo** [comment]
We'll talk about it since TCon already has a trait for electrum
