### ISSUE TITLE
Metal Suggestion 

### ISSUE THREAD

**Issue by Klazkin** [Davoleo/Metallurgy-4-Reforged#83]
![f1d2f7036ce058c9c7d3ff0ba958a80e](https://user-images.githubusercontent.com/44501483/50546956-955bc780-0c39-11e9-8cd1-e07d7e394067.png)

Blue **(0;0;255)** Metal, there is a lot of metals that are shades of blue but not a single one that is pure blue.
Only suggesting to add this so as to complete the rainbow :P 

Possible Names:

- Cobalt - makes sense but the metal is already used by tinkers
- Saphron - a combination of Sapphire and iron 
- Skögul - means high-towering in Old Norse, often related to Valkyries and Gods.
- Neptunium - something to do with water, I think.
- ...

(And any other better suggestions not by me)

**Comment by HurtsAsHell** [comment]
Skögul - means high-towering in Old Norse, often related to Valkyries and Gods.

**Comment by PierKnight100** [comment]
And what if this metal can be a really cold netal? Similar to ice

**Comment by Klazkin** [comment]
@PierKnight100 Don't know, this deep blue doesn't seem like it would fit cold theme. Usually "cold" colors are a lot more muted and less saturated than this.

**Comment by Davoleo** [comment]
Skögul Ideas:
Underwater generated high tower, decorated with blocks of this metal 
_Maybe tools or armor_
A throwable weapon / wind effect weapon
Sudying the ingot gathered from the block could unlock a new way to make this material

**Comment by HurtsAsHell** [comment]
Added to checklist
