### ISSUE TITLE
[Balancing] Minor changes and suggestions.

### ISSUE THREAD

**Issue by Klazkin** [Davoleo/Metallurgy-4-Reforged#86]
![104ac367a27f6e569a60245da7a68c1e](https://user-images.githubusercontent.com/44501483/50573733-32596480-0de2-11e9-88ad-db63587fda72.png)
- Roads in the "Machines" tab? 🤔 

- Inolashites armours durability should have a chance to take off 1 durability each time you punch. 

- Overpowered swords
 > Vanilla iron sword +5 damage
 > Our bronze sword +8 damage
 > Vanilla diamond sword +6 damage
 > Our **COPPER** sword + **8** damage
 >etc...

- Underpowered axes
 >Vanilla iron axe +8 damage
 >Our tartarite axe +3 damage
 >etc...

- Roads can be broken instantly with any tool (including bare arms), but only drop when broken with pickaxes, I suggest changing it so people don't accidentally break it while just running around.

**Comment by HurtsAsHell** [comment]
Checklist for @Davoleo :
- [ ] #86
  - [ ] Fix the road in the tabs
  - [ ] Decrease the damage of sword
  - [ ] Fix breaking the road

_For the moment we will do these things, the vanilla is made in its own way and our mod can't and mustn't follow it, in any case the copper is too advanced as damage. We will check to see what to weaken and what to upgrade_

**Comment by Davoleo** [comment]
Going to change the tab name to a more general one

Don't really know what's going on with the tartarite axe, but I'll check it

The road is a minor bug, and I'll fix it as soon as possible

**Comment by Klazkin** [comment]
@Davoleo, pretty sure it is not just tartarite axe, but all axes. Axes generally should have higher damage than swords (about +1/+2) and lower attack speed (don't know the exact value). I know we try to not follow vanilla, but axe being a proper weapon should not be something we get rid of either since, unlike swords axes can penetrate armor (which helps balance out new ridiculous armors that we may or may not have already added).

**Comment by HurtsAsHell** [comment]
We will not follow the vanilla dynamics

**Comment by Klazkin** [comment]
Sucks to be me since I use axes as a weapon over swords xd

**Comment by Davoleo** [comment]
I get what you were telling me, I think +3 as a damage for an axe is too low, even if we don't follow how vanilla works, axe is indeed a weapon and should give a higher damage, at least than the pickaxe

**Comment by Davoleo** [comment]
I'll buff it slightly, so that people can still use it as a weapon, but not too much as to make @HurtsAsHell angry

**Comment by Klazkin** [comment]
Honestly if we don't want to follow vanilla then maybe give all tools a potential in battles, then me drawing textures for hoes wouldn't feel like such a waste of time. But alright axes getting is enough to suffice. xd
