### ISSUE TITLE
Tile Entities not dropping experience

### ISSUE THREAD

**Issue by Davoleo** [Davoleo/Metallurgy-4-Reforged#9]
Tile Entity not spawning experience after the result is picked up by a player

**Comment by Davoleo** [comment]
Missing implementation

**Comment by Davoleo** [comment]
here's the commits about this bug @carbotaniuman ^

**Comment by carbotaniuman** [comment]
Addressed in pull request #18

**Comment by Davoleo** [comment]
Fixed in #18
