### ISSUE TITLE
Suggestion: Silent Gems Integration

### ISSUE THREAD

**Issue by renadi** [Davoleo/Metallurgy-4-Reforged#90]
If you are already gathering modifiers for TiCon could you look into also adding similar traits to Silent's Gear, which is a similar modular tool system, but natively supports armor, and also enchanting.

**Comment by HurtsAsHell** [comment]
thanks for the advice but we want to avoid imitating or copying

**Comment by HurtsAsHell** [comment]
Maybe I misunderstood. my team tells me that maybe you meant an integration with another mod, is that correct? @renadi

**Comment by renadi** [comment]
Yes, that is what I meant.

Silent's Gear is a mod similar to Tinker's Construct.

It would be nice if the planned Tinker's Construct material modifiers could
be used in Silent's Gear somehow, though that may take communication with
their dev @SilentChaos512.

**Comment by HurtsAsHell** [comment]
Now it makes a lot more sense to me. We could try but only **after** having published _the first version_ of the mod **with the tinker**

**Comment by Collecter128** [comment]
There is another Silent's Gems Addon called "Extra Parts" that might be related. I'm not sure how useful this info will be until the time after you finish the other things, but I hope it may help.

**Comment by stillg0ld** [comment]
Is this still in the works? It sounds like it was be an awesome integration for metallurgy!
