### ISSUE TITLE
Nerf Adamantine Armor and Haderoth gadget idea [Suggestion and Balancing]

### ISSUE THREAD

**Issue by Klazkin** [Davoleo/Metallurgy-4-Reforged#92]
Since technically your holding 2 weapons at once you deal twice as much damage twice as fast than any other ordinary weapon from any other mod. Which is a bit op. Iron golem has 100 HP and it takes a bit over 2 seconds to kill him (AND THEY AREN'T EVEN ENCHANTED), that's anywhere between 30-40 DPS. 

The other reason is so we can potentially later add slightly better haderoth gauntlets (or something similar, like claws), makes sense since haderoth is made from rubaracium. It would also be really cool to draw since haderoth is blue and red, so we can make one hand blue and the other red. :PPP

**Comment by PierKnight100** [comment]
@Klazkin to balance this power,every punch costs 1 food

**Comment by HurtsAsHell** [comment]
moreover it will always be considered as a single object

**Comment by HurtsAsHell** [comment]
we'll do a nerf to the adamantine armor, the fists are okay. Making changes does not make sense

**Comment by HurtsAsHell** [comment]
Added to checklist
