### ISSUE TITLE
new ore/alloy ideas

### ISSUE THREAD

**Issue by Late-Night** [Davoleo/Metallurgy-4-Reforged#99]
unsure of a name, but a plant-based alloy/ore, with regenerative properties

again, unsure of names, but more ender ores/alloys

Glintite: gold-glowstone alloy, full armor set gives night vision, durability of steel, right-click with pickaxe places torches if in inventory

Titanite: Ignatius-Deep Iron alloy, stats and etc. undecided

Imperial Gold: Midasium-gold-Lemurite alloy, does extra damage to undead

unnamed packed ice-iron alloy

Octiron: Eximite-Shadow Iron alloy. stats, etc undecided

Reardenite: Redstone-Glowstone-Steel alloy. 1.5x the stats of steel, with the trait of every third block broken/tilled/mob slain not taking durability

Yosarite: unsure if it should be an ore or an alloy. if alloy, Sanguinite-Vyroxeres alloy. if ore, nether ore

**Comment by HurtsAsHell** [comment]
Thanks

**Comment by Davoleo** [comment]
**unsure of a name: ** the overall idea is nice, although something similar is added by other mods
**Glintite** : too similar to EnderIO's Energetic alloy, also night vision effect is already handled by platinum
**Titanite:**  the idea is too vague, furthermore it's an existing material
**Imperial gold: ** Extra damage to undead is already implemented by silver, also the idea  is vague and similar to Midasium
**unnamed:** too vague
**Octiron:** too vague and general
**Reardenite:** similar to Energetic alloy from EnderIO
**Yosarite:** vague and general

**Comment by Late-Night** [comment]
> 
> 
> **unsure of a name:** the overall idea is nice, although something similar is added by other mods
> **Glintite** : too similar to EnderIO's Energetic alloy, also night vision effect is already handled by platinum
> **Titanite:** the idea is too vague, furthermore it's an existing material
> **Imperial gold:** Extra damage to undead is already implemented by silver, also the idea is vague and similar to Midasium
> **unnamed:** too vague
> **Octiron:** too vague and general
> **Reardenite:** similar to Energetic alloy from EnderIO
> **Yosarite:** vague and general

i'm being vague so you can fill in the gaps
you're the creator after all

**Comment by Davoleo** [comment]
First thing: @HurtsAsHell is the creator of the mod, I'm just a developer (co-owner)
Second thing: suggestions are made to be specific about some kind of material that you would like to be in the game, because, well everyone can be vague about things, but creating something that is characterized and original is difficult

**Comment by Davoleo** [comment]
closing this issue as the suggestions are not really complete neither specific
We appreciate more one feature but original and characterised than multiple features that are described so vaguely
